src/publickey.js
test/publickey.test.js

fix: PublicKey.toBuffer() now zero pads correctly

---

package-lock.json
package.json

The SDK was only downloaded and installed once, after that even if the SDK was updated npm would not re-install it.  Because the SDK tarball is not versioned this change installs a fresh copy of the SDK everytime 'npm install' is called.

fix: Update sdk everytime

---

bin/bpf-sdk-install.sh
bin/localnet.sh
bin/testnet-default-channel.js
package.json

@jackcmay, once this lands from tic-tac-toe we'll be able to run `solana-bpf-sdk-install` to refresh the bpf-sdk without having to ship a new solana-web3.js

fix: add `solana-bpf-sdk-install` command to permit users to easily update their bpf-sdk

---

package-lock.json
package.json
rollup.config.js

Fix rollup dependency conflict

---

module.flow.js
src/connection.js
test/connection.test.js

Follow on to https://github.com/solana-labs/solana/pull/4774/
I *think* I hit all of the spots.  Tests pass anyway
I did have to remove `--serial` from https://github.com/solana-labs/solana-web3.js/blob/master/package.json#L58 to get `npm run ok` to not complain about thinking it's an invalid option.  I couldn't find any documentation for that flag, but the scripts seemed to run sequentially.

Expose `getTotalSupply` RPC method

---

test/connection.test.js

CI tests have been failing since credit-only accounts landed on solana (https://github.com/solana-labs/solana/pull/4691), as system transfer credits only get committed on slot boundary

fix: Fix transaction live test for credit-only accounts

---

module.flow.js
package-lock.json
package.json
src/connection.js
test/connection.test.js

Depends on https://github.com/solana-labs/solana/pull/4876
(CI will also fail until #385 lands)
I went ahead and removed `--serial` from https://github.com/solana-labs/solana-web3.js/blob/master/package.json#L58 to run `npm run ok` (see #370 )

fix: Expose getProgramAccounts RPC method

---

src/index.js
src/system-program.js
src/transaction.js
test/system-program.test.js

cc: @sunnygleason 
Feedback definitely wanted, if there's a more elegant way to do this.

fix: add transaction instruction data-parsing functionality for system-instructions

---

src/connection.js
test/connection.test.js

Problem:
* grant/grant_term were removed from RPC by https://github.com/solana-labs/solana/pull/5936
Solution:
* update web3js to not include those attributes
* extend tests so we could have caught this pre-release w/ integration tests

fix: remove grant/grant_term from inflation

---

src/vote-account.js
test/connection.test.js

Updates VoteAccount class and layout to match https://github.com/solana-labs/solana/pull/6072
Also fixes live test; localnet node does not appear to be voting, and so shows up on the `delinquent` list of vote accounts. This might indicate an issue upstream, but I don't think this test needs to depend on that.
Fixes #490

Vote Account fixes

---

src/connection.js

PROBLEM:
* the new `rootSlot` field is breaking stuff
SOLUTION:
* add an optional field definition until we figure out something like #527

feat: add optional rootSlot parameter

---

src/bpf-loader.js
src/loader.js
test/bpf-loader.test.js

Clients have no way of determining how many lamports will be required to upload a program.  
The loader doesn't know for sure due to retries, but can at least provide an estimate of the minimum number of signatures required given how many signatures it needs per transaction and how many chunks it plans to send.  The client can then use the `feeCalculator` to calculate the total fees.

fix: loader report minimum number of signatures required

---

module.flow.js
src/budget-program.js
src/loader.js
src/system-program.js
src/transaction.js
test/bpf-loader.test.js
test/connection.test.js
test/system-program.test.js

Solana upstream no longer uses credit-only/credit-debit, but readonly/writable.
Update solana-web3 terminology, and (more importantly) make sure transaction account metadata is correct.
Closes #542

fix: update accounts to readonly/writable

---

examples/budget-timestamp.js
examples/budget-two-approvers.js
module.flow.js
src/connection.js
src/util/send-and-confirm-raw-transaction.js
src/util/send-and-confirm-transaction.js
test/bpf-loader.test.js
test/connection.test.js
test/mockrpc/get-recent-blockhash.js
test/transaction-payer.test.js

Fixes: https://github.com/solana-labs/solana-web3.js/issues/546
Other related changes:
* Allow specifying a default commitment level for a `Connection` instance
* Add new `sendAndConfirmRecentTransaction` convenience method
* Fix broken examples
* Fix live tests
* Add test for max commitment

feat: add commitment param to JSON RPC API requests

---

src/connection.js
src/transaction.js
test/connection.test.js

Also sneaks in a naming fix for isCreditDebit() -> isWriteable()

fix: add getBlocksSince Connection method

---

examples/budget-common.js
examples/budget-timestamp.js
examples/budget-two-approvers.js
src/budget-program.js

* Calculate fees for budget-timestamp (it was failing due to insufficient funds)
* Share code between budget examples
* Make `to` writable in applyTimestamp to fix:
```
== Witness contract
Error: Transaction 4e8vERadgTyTRpXGBy31q97n32F2i8uLWbkEsUnX7eE2TBaoaVggatko2FMUwToPsGUQiV2yeksvAqXSVQJCtKoE failed ({"Err":{"InstructionError":[0,"ReadonlyLamportChange"]}})
```

fix: budget program examples

---

src/connection.js

We shouldn't mark the rpc client as disconnected when it isn't explicitly closed. The rpc client framework will automatically reconnect according to a configurable interval (default 1s)

fix: use the jsonrpc framework reconnect interval

---

src/connection.js
src/transaction.js
test/connection.test.js

Fixes https://github.com/solana-labs/solana-web3.js/issues/558
Fixes CI so the next release can go out 😄

feat: Add getConfirmedBlock api

---

test/transaction.test.js

Test coverage took a hit from this last change: https://github.com/solana-labs/solana-web3.js/pull/562

chore: add test for Transaction.fromRpcResult

---

module.flow.js
src/connection.js
test/connection.test.js

PROBLEM:
* clients would like realtime slot notifications (e.g. for fork visualization)
* see solana-labs/solana#7114 for latest problem description
SOLUTION:
* hook up the websocket slot notification API

feat: slot change callback (provides real-time fork information)

---

src/connection.js

`epoch_credits` was recently added to the `getVoteAccounts` RPC endpoint but the SDK does not expect it.
* Add an optional `epoch_credits` value to `getVoteAccounts`

fix: Add epoch_credits value to getVoteAccounts RPC call

---

bin/localnet.sh

First check the parent's package.json for which channel to use for localnet

fix: use parent packages channel

---

src/connection.js

Fixes up CI failures: https://travis-ci.org/solana-labs/solana-web3.js/jobs/628935451

fix: add balances fields to GetConfirmedBlockRpcResult

---

flow-typed/hasha.js
module.flow.js
package-lock.json
package.json
src/config-program.js
src/index.js
src/instruction.js
src/layout.js
src/loader.js
src/publickey.js
src/stake-program.js
src/system-program.js
src/sysvar-rent.js
src/sysvar.js
src/vote-account.js
test/connection.test.js
test/publickey.test.js
test/stake-program.test.js

@mvines , fyi, and one question:
I wrote `delegate`, `authorize`, `split`, `withdraw`, and `deactivate` on the assumption that the client would use a non-stake-account authorized keypair to sign/execute the transaction. This seems like the most common downstream use case to me, so it is a convenient short-cut. Should I rework now to offer something like the solana-stake-program's `with_signer()`?
Toward https://github.com/solana-labs/solana/issues/7583

Add stake program

---

bin/bpf-sdk-install.sh

Use the calling packages testnetDefaultChannel and not the SDK itself

fix: use testnetDefaultChannel when install bpf-sdk

---

src/system-program.js
src/transaction.js

Rename nonce instructions to match main code base
Depends on https://github.com/solana-labs/solana/pull/7775

Rename nonce instructions with VerbNoun scheme

---

module.flow.js
src/connection.js

Encode raw transaction as base58 string. I also included a `Connection.sendEncodedTransaction()` method, as I thought it might be helpful for users.
CI depends on https://github.com/solana-labs/solana/pull/7913 in solana docker image

fix: update rpc sendTransaction format

---

src/connection.js
test/connection.test.js

A healthy node may return a (successful) result of `null` for rpc method `getConfirmedBlock` if the node has not yet reached that block or has pruned that block from its ledger.
This PR makes that result mode explicit, instead of just failing mysteriously in `GetConfirmedBlockRpcResult`

fix: better handling if confirmed block not found on node

---

src/connection.js

`updateSubscriptions` was await-ing while iterating over keys to subscribe to. If a key is removed before being subscribed, an error will be thrown. This situation is admittedly a bit unlikely to happen in practice, but feels worthy of fixing anyways
* Synchronously subscribe to keys

fix: race condition in rpc subscribe

---

src/connection.js

Fixes: https://github.com/solana-labs/solana-web3.js/issues/669
https://github.com/solana-labs/solana/pull/8128 added a new field to the getConfirmedBlock api response and it's causing live test failures

fix: add rewards to getConfirmedBlock api

---

.eslintrc.js
module.d.ts
module.flow.js
package-lock.json
package.json
src/index.js
src/stake-program.js
src/system-program.js
test/__mocks__/rpc-websockets.js
test/stake-program.test.js
test/system-program.test.js

* StakeInstruction is not exposed in type definitions
* Instruction layouts are not exposed in type definitions
* Instruction types are not exposed in type definitions
* No dev friendly way to get a human readable name of an instruction type
* It's not safe to pull out particular account keys from stake instructions (stake key, authorized key, etc)
* Fix flow type linting
* Exposed above types in definitions
* Refactored system and stake instruction classes to expose instruction type names
* Added nullable getter methods for pulling out the stake and authorized pubkeys from a stake instruction (similar to how we handle system instructions)

feat: expose instruction types and refactor

---

module.d.ts
module.flow.js
src/instruction.js
src/stake-program.js
test/stake-program.test.js
test/transaction.test.js

* The sdk doesn't provide a way to decode stake instruction data
* Stake instruction API methods have lots of parameters and can be easily misused
* Remove `StakeInstruction.from` method in favor of `StakeInstruction.decode...` methods.
* Refactor `StakeProgram` methods to accept a typed param object rather than a list of params
* Add methods to decode stake instructions into the typed param objects they were created with

feat: add API for decoding stake instructions

---

module.d.ts
module.flow.js
src/budget-program.js
src/loader.js
src/stake-program.js
src/system-program.js
test/connection.test.js
test/get-confirmed-block.test.js
test/nonce.test.js
test/stake-program.test.js
test/system-program.test.js
test/transaction-payer.test.js
test/transaction.test.js

* The sdk doesn't provide a way to decode the finer details of system instruction data (especially nonce instructions)
* System instruction API methods have lots of parameters and can be easily misused
* Remove `SystemInstruction.from` method in favor of `SystemInstruction.decode`... methods.
* Refactor `SystemProgram` methods to accept a typed param object rather than a list of params
* Add methods to decode system instructions into the typed param objects they were created with
* Add more tests for peace of mind (and @CriesofCarrots's peace of mind!)

feat: add API for decoding system instructions

---

src/transaction.js

Transaction population checks for `programIndex` when it should be checking for `programIdIndex`. This error caused all instructions to have the system program id (and thus evading detecting by our tests)

fix: getConfirmedBlock instruction programId parsing

---

module.d.ts
module.flow.js
src/connection.js
test/connection.test.js
test/transaction-payer.test.js

We moved the recent API changes for `getSignatureStatus` over to `getSignatureStatuses`
* rename `Connection.getSignatureStatusBatch` to `Connection.getSignatureStatuses`
* switch rpc method name from `getSignatureStatus` to `getSignatureStatuses`
Waiting on edge docker image for https://github.com/solana-labs/solana/pull/9228

feat: use new getSignatureStatuses endpoint and naming

---

module.d.ts
module.flow.js
src/connection.js
test/connection.test.js
test/nonce.test.js
test/system-program.test.js

Related to: https://github.com/solana-labs/solana-web3.js/issues/779
Many of our APIs return null if a queried object is not found. This makes it easy to distinguish between a network errors and missing objects. However, `getAccountInfo` and `getNonce` throw an error if they do not find results and forces users to parse error messages (not fun) to distinguish the two cases.
Change `getAccountInfo` and `getNonce` return types to `<T | null>`

feat: return null when account info not found

---

module.d.ts
module.flow.js
src/connection.js
src/util/send-and-confirm-raw-transaction.js
src/util/send-and-confirm-transaction.js
test/connection.test.js
test/transaction-payer.test.js

https://github.com/solana-labs/solana/pull/9314 has removed `commitment` from the config and introduced `searchTransactionHistory` to the config for the `getSignatureStatuses` RPC endpoint and this PR addresses that API change.

feat: update getSignatureStatus methods

---

src/system-program.js

For consistency with all of the others, and because it has tripped up partner developers

Declare System Program ID in base58

---

module.d.ts
module.flow.js
src/bpf-loader.js
test/bpf-loader.test.js

It's not possible to load a program into a particular account
* Add `program: Account` param to the `BpfLoader.load(..)` method

feat: specify program account when using bpf loader

---

module.d.ts
module.flow.js
src/transaction.js
test/transaction.test.js

The `Transaction` type assumes it will handle creating all signatures and as a result keeps many of the facilities to do so private.  This makes it more involved than it needs to be to sign `Transactions` externally, such as with a Ledger wallet
Expose `Transaction._getSignData()` as `Transaction.signData`
Add a helper for adding externally created `PublicKey`/`Signature` pairs to `Transaction`s
Test!
Fixes: https://github.com/solana-labs/solana-web3.js/issues/570

Allow external signing of `Transaction`s

---

module.d.ts
module.flow.js
src/index.js
src/message.js
src/transaction.js

- No way to map account ids from confirmed transaction metadata balances to transaction accounts because `Message` was not exposed
- Not easy to determine which accounts in a transaction are readonly
- Create `Message` class and move some serialization logic from `Transaction`
- Add `MessageHeader` and `CompiledInstruction` types
- Add `Transaction.compileMessage()` method to expose message data
- Add `Message.isAccountWritable()` convenience method

feat: expose transaction message publicly

---

module.d.ts
module.flow.js
src/system-program.js
test/nonce.test.js
test/system-program.test.js

Not possible to create a nonce account using a derived address
* Allow passing `basePubkey` and `seed` fields to `SystemProgram.createNonceAccount`

feat: allow passing seed to createNonceAccount

---

module.d.ts
module.flow.js
src/system-program.js
test/connection.test.js
test/system-program.test.js

Fixes: https://github.com/solana-labs/solana-web3.js/issues/866
* Adds support for creating and decoding the following instruction types:
- Allocate
- AllocateWithSeed
- AssignWithSeed
* Renamed the assign param from `fromPubkey` to `accountPubkey`

feat: add support for more system instructions

---

src/system-program.js

Valid system / stake instructions require a minimum number of keys but there is no max (beyond the size of a transaction). The web3 decode api was incorrectly enforcing a max number of keys.

fix: key length check when decoding instructions

---

src/bpf-loader.js
src/loader.js
test/bpf-loader.test.js

The program loader and BPF loader was recently modified to take a program account in which to load the module but still return's that accounts public key.  The return value is unnecessary since callers can use the `publicKey` member of `Account` directly.  Returning the public key may also be confusing as it might lead callers to think that the returned key represents something different than the key of the program account passed in.

fix: remove return value from load, unnecessary

---

package.json

Problem
Test fixtures are not cleaned before installing a new version of the BPF SDK which led to noop-rust build failures.
Proposed solution
- Add a script to clean the test fixtures
- Clean the test fixtures before installing a new bpf-sdk

fix: clean fixtures

---

module.d.ts
module.flow.js
src/connection.js
src/index.js
src/loader.js
src/util/send-and-confirm-raw-transaction.js
src/util/send-and-confirm-transaction.js
test/bpf-loader.test.js
test/connection.test.js
test/nonce.test.js
test/stake-program.test.js
test/system-program.test.js
test/transaction-payer.test.js

Fixes: https://github.com/solana-labs/solana-web3.js/issues/792
Fixes: https://github.com/solana-labs/solana-web3.js/issues/793
Fixes: https://github.com/solana-labs/solana-web3.js/issues/892
RPC has new commitment levels and the behaviour of the `getSignatureStatuses` endpoint has shifted to represent cluster confirmations rather than the incorrect notion of node votes as "confirmations".
This felt like a good time to clean up our apis around transaction confirmation
* Removed `Connection.confirmTransactionAndContext` API
* Updated `Connection.confirmTransaction` to poll the `getSignatureStatuses` RPC API until a specified confirmation count has been reached or the transaction fails
* Added `confirmations` param to both `sendAndConfirmTransaction` and `sendAndConfirmRawTransaction` to …

Add new commitment levels and update tx confirmation apis

---

module.d.ts
module.flow.js
src/connection.js
test/connection.test.js

Fixes: https://github.com/solana-labs/solana-web3.js/issues/904
RPC API supports commitment param but the sdk doesn't provide a way to pass it

feat: add commitment param to subscription apis

---

module.d.ts
module.flow.js
package-lock.json
package.json
src/connection.js
src/loader.js
src/util/send-and-confirm-raw-transaction.js
src/util/send-and-confirm-transaction.js
test/bpf-loader.test.js
test/connection.test.js
test/nonce.test.js
test/stake-program.test.js
test/system-program.test.js
test/transaction-payer.test.js

- Reverted 2 rogue dependabot commits that didn't pass CI but merged anyways
- Added `skipPreflight` option to transaction sending APIs
- Updated `getInflation` to `getInflationGovernor`
- Use max commitment blockhashes when sending transactions
- Added `getFeeCalculatorForBlockhash` method (needed for a test)

Fix CI, add skipPreflight, update inflation api

---

module.d.ts
module.flow.js
src/connection.js
test/connection.test.js
test/nonce.test.js
test/transaction-payer.test.js

The `requestAirdrop` method on the RPC API service used to wait until a status was available at the specified `commitment` level before returning a response. But after https://github.com/solana-labs/solana/pull/10446, it only uses the `commitment` param to determine which blockhash to use for the airdrop transaction.
There's no reason I can think of that a developer would want to use a more recent blockhash so I think it's best to remove this parameter from the `Connection.requestAirdrop` API to avoid confusion and encourage best practices.
- Remove `commitment` param from `requestAirdop`
- Fix failing CI

feat: remove commitment param from requestAirdrop method

---

module.d.ts
module.flow.js
src/connection.js
src/message.js
src/transaction.js
test/transaction.test.js

No method in transaction type definitions for constructing a transaction from an RPC response. 
- Tweaked `MessageArgs` type (used to construct `Message`) in order to remove `fromRpcResult` method
- Removed `Transaction.fromRpcResult`
- Made `Transaction.populate` method public

feat: make Transaction.populate method public and tweak MessageArgs

---

.mergify.yml

Cribbed from https://github.com/solana-labs/solana/pull/30097

chore: Remove 'remove outdated reviews' rule, Github now supports this natively

---

packages/library-legacy/package.json
pnpm-lock.yaml

To address https://github.com/solana-labs/solana-web3.js/security/dependabot/64

chore: update `node-fetch` to 2.6.7

---

packages/test-config/jest-lint.config.ts
packages/test-config/jest-prettier.config.ts
packages/test-config/jest-unit.config.browser.ts
packages/test-config/jest-unit.config.common.ts
packages/test-config/jest-unit.config.node.ts

This will prevent me from continually adding properties to these configs that actually belong in the root config.

test: repair the type of the Jest project configs

---

packages/library-legacy/package.json
pnpm-lock.yaml

At long last, we've found a clear-cut source of socket state corruption in `rpc-websockets` and were able to fix it in https://github.com/elpheria/rpc-websockets/pull/138.
This pulls the new version into `@solana/web3.js`. Now, when our library make an _explicit_ reconnection attempt, it will no longer cause the socket state to get corrupted by `rpc-websocket's` _implicit_ reconnection machinery.
Fixes #1106.

fix: update to 7.5.1 of `rpc-websockets`; fixes socket state corruption related to automatic reconnections

---

.npmrc

Related: https://github.com/dhoulb/multi-semantic-release/issues/129#issuecomment-1250013235

chore: get `semantic-release` not to try to bump the version of private workspace package references

---

packages/build-scripts/tsup.config.browser.ts

chore: create a build config that _only_ makes a browser build
Summary: We will need this to build browser-only forks of modules like `fetch-impl`.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1193).
* #1194
* __->__ #1193
* #1192

chore: create a build config that _only_ makes a browser build

---

packages/build-scripts/tsup.config.browser.ts
packages/test-config/jest-unit.config.common.ts
packages/test-config/package.json
packages/test-config/setup-fetch-mock.ts
pnpm-lock.yaml

chore: mock `fetch` in tests
Summary: `jsdom` does not supply a polyfill for `fetch`; we have to do it ourselves
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1192).
* #1194
* #1193
* __->__ #1192

chore: mock `fetch` in tests

---

packages/rpc-core/src/rpc.ts
packages/rpc-core/src/types/jsonRpcApi.d.ts
packages/rpc-core/src/types/rpc-methods/getAccountInfo.d.ts
packages/rpc-core/src/types/rpc-methods/getBlockHeight.d.ts
packages/rpc-core/src/types/rpc-methods/getBlocks.d.ts

@joncinque pointed out in #1190 that the Typescript types of `@solana/rpc-core` relied on a cast through `unknown` to work. The more I thought about it the more I realized that the `transport` shouldn't form part of the typespec for the RPC.
In this PR we remove it from the source types, and map it back in where it's needed in the implementation..

[experimental] Remove the concept of the transport from the types of the RPC

---

turbo.json

chore: build typedefs for all packages before typechecking
Sometimes package A depends on package B, and needs to read its typedefs to be able to typecheck _itself_. This implies that typedefs need to be built _before_ typechecking. This PR adds `compile:typedefs` as a dependency of `test:typecheck`.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1202).
* #1201
* #1200
* __->__ #1202

chore: build typedefs for all packages before typechecking

---

packages/library-legacy/package.json
packages/library-legacy/test/url.ts
packages/library-legacy/test/websocket.test.ts
turbo.json

test: don't rely on `localhost` being an alias for 127.0.0.1 in tests
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1200).
* #1201
* __->__ #1200
* #1202

test: don't rely on `localhost` being an alias for 127.0.0.1 in tests

---

packages/library-legacy/package.json
packages/library-legacy/test/connection.test.ts
packages/library-legacy/test/url.ts
packages/library-legacy/test/websocket.test.ts
turbo.json

test: extend timeout for ‘get leader schedule’ test
This test seems to timeout a lot in CI these days. Let's try extending the timeout.
```shell
pnpm test:live-with-test-validator
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1201).
* __->__ #1201
* #1200
* #1202

test: extend timeout for ‘get leader schedule’ test

---

turbo.json

Now that packages are starting to depend upon one another, we have to enforce that dependencies get built _first_ before typechecking or testing a given library for tree-shakability, since the dependencies will play a role in those outcomes.
CI run.

chore: build dependent packages when typechecking and testing tree-shakeability

---

packages/fetch-impl-browser/package.json
packages/keys/package.json
packages/library/package.json
packages/rpc-core/package.json
packages/rpc-transport/package.json
packages/test-config/jest-unit.config.common.ts
packages/test-config/package.json
packages/test-config/setup-fetch-mock.ts
pnpm-lock.yaml

test: Make `fetch` mocks in Jest compatible with auto-resetting
I want all mocks to restored after each test run, so that no state or implementation bleeds between tests. This is incompatible with `jest-mock-fetch`. The solution is to manually restore the fetch mock for each and every test.
```
pnpm dev
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1209).
* #1210
* #1205
* #1204
* __->__ #1209

test: Make `fetch` mocks in Jest compatible with auto-resetting

---

packages/fetch-impl-browser/package.json
packages/keys/package.json
packages/library/package.json
packages/rpc-core/package.json
packages/rpc-transport/package.json
packages/rpc-transport/src/__tests__/params-patcher-test.ts
packages/rpc-transport/src/params-patcher.ts
packages/test-config/jest-unit.config.common.ts
packages/test-config/package.json
packages/test-config/setup-fetch-mock.ts
pnpm-lock.yaml

[experimental] A function to patch up JSON RPC params that are destined for the Solana JSON RPC
`u64` values, in the Solana JSON RPC, are implemented as JavaScript numbers. This means that any number greater than `Number.MAX_SAFE_INTEGER` (9007199254740991) can't be trusted. This is tracked in https://github.com/solana-labs/solana/issues/30741.
In this PR we create a serializer that converts `bigint` values coming in from `@solana/rpc-core` to JavaScript `number`, as a concession.
```shell
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1204).
* #1210
* #1205
* __->__ #1204
* #1209

[experimental] A function to patch up JSON RPC params that are destined for the Solana JSON RPC

---

packages/fetch-impl-browser/package.json
packages/keys/package.json
packages/library/package.json
packages/rpc-core/package.json
packages/rpc-core/src/__tests__/rpc-test.ts
packages/rpc-core/src/types/rpc-methods/common.d.ts
packages/rpc-core/src/types/rpc-methods/getAccountInfo.d.ts
packages/rpc-core/src/types/rpc-methods/getBlockHeight.d.ts
packages/rpc-transport/package.json
packages/rpc-transport/src/__tests__/params-patcher-test.ts
packages/rpc-transport/src/json-rpc-transport.ts
packages/rpc-transport/src/params-patcher.ts
packages/test-config/jest-unit.config.common.ts
packages/test-config/package.json
packages/test-config/setup-fetch-mock.ts
pnpm-lock.yaml

[experimental] Type the RPC API with `bigint` at the edge
The _correct_ thing to do is be to use `bigint` wherever the Solana JSON RPC specfies `u64`. This PR endeavours to do that.
*Note*: This isn't _actually_ safe, Because of an error in the design of the RPC. See #1204 for more information.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1205).
* #1210
* __->__ #1205
* #1204
* #1209

[experimental] Type the RPC API with `bigint` at the edge

---

packages/rpc-transport/src/__tests__/json-rpc-transport-test.ts
packages/rpc-transport/src/json-rpc-transport.ts
packages/rpc-transport/src/params-patcher.ts

[experimental] A handler you can supply to transports in the event of integer overflows
The JSON RPC was designed to communicate JavaScript `Numbers` over the wire, which puts values over `Number.MAX_SAFE_INTEGER` at risk of rounding errors. In this PR we add a hook that fires in the event of such an overflow. Implementers of that hook can decide to do whatever they want: throw, warn, or allow.
```shell
```

[experimental] A handler you can supply to transports in the event of integer overflows

---

.github/ISSUE_TEMPLATE/config.yml

Add links to Stack Exchange and Discord on the ‘create an issue’ page
Sometimes people create issues when all they want is to ask a usage question.
I learned you can do this from the Typescript GitHub: https://github.com/microsoft/TypeScript/issues/new/choose

Add links to Stack Exchange and Discord on the ‘create an issue’ page

---

packages/rpc-transport/package.json
packages/rpc-transport/src/__tests__/json-rpc-transport-params-patcher-test.ts
packages/rpc-transport/src/__tests__/json-rpc-transport-test.ts
packages/rpc-transport/src/index.ts
packages/rpc-transport/src/json-rpc-transport-types.ts
packages/rpc-transport/src/json-rpc-transport.ts
pnpm-lock.yaml

[experimental] Invert the responsibilities of the transport and rpc
Previously, the RPC API was responsible for:
* exposing RPC methods using a JavaScript proxy
* formatting params for delivery to an RPC server
* calling `send()` on a supplied transport
What I discovered was that this made a whole bunch of things _really_ hard.
* supplying a per-call cancellation signal
* bundling calls in a batch
In this PR, we inside out this design.
* the RPC package is now exclusively made up of types
* the transport features a generic that accepts that type, exposing all of its methods
* the transport now ‘collects’ calls until you call `send()` or `sendBatch()`
* the ‘send’ methods are a logical place to configure a cancellation signal, and more.
Look at the tests to see how this works in practice, …

[experimental] Invert the responsibilities of the transport and rpc

---

packages/library-legacy/test/program-tests/compute-budget.test.ts

test: disable live compute budget tests
These are busted by 1.16. Skipping this test to get the release train going again. Following up in #1237 and #1238.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1236).
* #1237
* __->__ #1236

test: disable live compute budget tests

---

packages/library/package.json
packages/library/src/__tests__/rpc-test.ts
packages/library/src/index.ts
packages/library/src/rpc-default-config.ts
packages/library/src/rpc.ts
pnpm-lock.yaml

refactor(experimental): introduce a `createDefaultRpc()` method to the library
You can use this to create a transport with default config. Supply only a URL.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1227).
* #1241
* #1239
* #1232
* #1231
* #1230
* #1229
* #1228
* __->__ #1227

refactor(experimental): introduce a `createDefaultRpc()` method to the library

---

packages/library/package.json
packages/library/src/__tests__/rpc-test.ts
packages/library/src/index.ts
packages/library/src/rpc-default-config.ts
packages/library/src/rpc.ts
packages/test-config/package.json
packages/test-config/test-validator-setup.js
packages/test-config/test-validator-teardown.js
pnpm-lock.yaml

refactor(experimental): jest setup/teardown functions for test validator
Any test that relies on a test validator running on localhost can use these Jest setup/teardown functions. They take care of starting the validator, waiting for it to come alive, and tearing it down at the end of the test.
See the first PR that makes use of it.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1228).
* #1241
* #1239
* #1232
* #1231
* #1230
* #1229
* __->__ #1228
* #1227

refactor(experimental): jest setup/teardown functions for test validator

---

packages/library/package.json
packages/library/src/__tests__/rpc-test.ts
packages/library/src/index.ts
packages/library/src/rpc-default-config.ts
packages/library/src/rpc.ts
packages/rpc-transport/src/json-rpc-transport/json-rpc-errors.ts
packages/test-config/package.json
packages/test-config/test-validator-setup.js
packages/test-config/test-validator-teardown.js
pnpm-lock.yaml

refactor(experimental): add JSON-RPC error codes
This PR adds in the custom error codes that our RPC throws. We can consider exporting this in a future PR, but for now we'll just use it internally, in tests.
See first PR where this enum is used.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1229).
* #1241
* #1239
* #1232
* #1231
* #1230
* __->__ #1229
* #1228
* #1227

refactor(experimental): add JSON-RPC error codes

---

packages/library/package.json
packages/library/src/__tests__/rpc-test.ts
packages/library/src/index.ts
packages/library/src/rpc-default-config.ts
packages/library/src/rpc.ts
packages/rpc-transport/package.json
packages/rpc-transport/src/json-rpc-transport/__tests__/json-rpc-method-get-block-height-test.ts
packages/rpc-transport/src/json-rpc-transport/json-rpc-errors.ts
packages/test-config/package.json
packages/test-config/test-validator-setup.js
packages/test-config/test-validator-teardown.js
pnpm-lock.yaml

refactor(experimental): added tests for the `getBlockHeight` method
This is the first of many tests against the local test validator's RPC. In particular, this one exists to demonstrate that the library right now _fails_ to return a `bigint` to the caller.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1230).
* #1241
* #1239
* #1232
* #1231
* __->__ #1230
* #1229
* #1228
* #1227

refactor(experimental): added tests for the `getBlockHeight` method

---

packages/library/package.json
packages/library/src/__tests__/rpc-test.ts
packages/library/src/index.ts
packages/library/src/rpc-default-config.ts
packages/library/src/rpc.ts
packages/rpc-transport/package.json
packages/rpc-transport/src/__tests__/response-patcher-test.ts
packages/rpc-transport/src/json-rpc-transport/__tests__/json-rpc-method-get-block-height-test.ts
packages/rpc-transport/src/json-rpc-transport/json-rpc-errors.ts
packages/rpc-transport/src/response-patcher.ts
packages/test-config/package.json
packages/test-config/test-validator-setup.js
packages/test-config/test-validator-teardown.js
pnpm-lock.yaml

refactor(experimental): a function to patch numeric values coming from the RPC
For the time being, we are going to need to convert numbers as they come off the RPC into `bigint`. In a follow up PR we'll allowlist certain methods/keypaths as allowed to be numbers. This will be one of the few places that we have to enumerate all RPC methods, but the damage will be minimal because _most_ values are u64.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1231).
* #1241
* #1239
* #1232
* __->__ #1231
* #1230
* #1229
* #1228
* #1227

refactor(experimental): a function to patch numeric values coming from the RPC

---

packages/rpc-transport/src/__tests__/response-patcher-test.ts
packages/rpc-transport/src/response-patcher-allowed-numeric-values.ts
packages/rpc-transport/src/response-patcher-types.ts
packages/rpc-transport/src/response-patcher.ts
packages/test-config/jest-dev.config.ts

refactor(experimental): add a numeric value allowlist to the response patcher
Most of the values that come from the RPC are supposed to be `u64` (ie. must be represented as JavaScript `bigint`, eventually). Some are legitimately `usize` or `u8` though.
In this PR we create an allowlist for those method/path pairs. Any value at that path for that method will not be upcast.
```
cd packages/rpc-transport
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1239).
* #1241
* #1232
* __->__ #1239

refactor(experimental): add a numeric value allowlist to the response patcher

---

packages/rpc-transport/src/__tests__/response-patcher-test.ts
packages/rpc-transport/src/json-rpc-transport/__tests__/json-rpc-method-get-block-height-test.ts
packages/rpc-transport/src/json-rpc-transport/__tests__/json-rpc-transport-response-patcher-test.ts
packages/rpc-transport/src/json-rpc-transport/__tests__/json-rpc-transport-test.ts
packages/rpc-transport/src/json-rpc-transport/index.ts
packages/rpc-transport/src/response-patcher-allowed-numeric-values.ts
packages/rpc-transport/src/response-patcher-types.ts
packages/rpc-transport/src/response-patcher.ts
packages/test-config/jest-dev.config.ts

refactor(experimental): install the response patcher into the RPC transport
The patcher will operate over the response, converting numbers to `bigint` as it goes. Eventually we will teach it which numbers to leav alone, since there are some values in RPC responses that are legitimately `u8` or `usize`.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1232).
* #1241
* __->__ #1232
* #1239

refactor(experimental): install the response patcher into the RPC transport

---

package.json
turbo.json

Moving these into the Turborepo config, formally, lets _other_ steps share them. That is to say if a subpackage calls `turbo build` then it will get all this stuff for free.

chore: move the build deps into the Turborepo config

---

packages/keys/package.json
packages/library/package.json
packages/rpc-core/package.json
packages/rpc-transport/package.json
pnpm-lock.yaml
turbo.json

This is a bit of a #yolo, but I think this will
* version the experimental packages with the current git commit ref
* publish them under the `experimental` tag on NPM
Let's see.

chore: build experimental packages on every commit

---

packages/library-legacy/src/connection.ts
packages/library-legacy/test/connection.test.ts

feat: add getRecentPrioritizationFees API

---

packages/build-scripts/getBaseConfig.ts
packages/fetch-impl-browser/package.json
packages/fetch-impl-browser/tsconfig.json
packages/rpc-transport/package.json
packages/rpc-transport/src/http-request.ts
pnpm-lock.yaml
turbo.json

chore: don't build typedefs with the build of every package
The existing build config builds the typedefs with every package built, and also builds every package every time you build the typedefs. Let's stop that.
CI run

chore: don't build typedefs with the build of every package

---

packages/rpc-core/src/index.ts
packages/rpc-core/src/rpc-methods/__tests__/get-balance-test.ts
packages/rpc-core/src/rpc-methods/common.ts
packages/rpc-core/src/rpc-methods/getBalance.ts
scripts/fixtures/4nTLDQiSTRHbngKZWPMfYnZdWTbKiNeuuPcX7yFUpSAc.json
scripts/start-shared-test-validator.sh

Add the `getBalance` API and unit tests
Note that we currently only test for a zero balance, as we haven't implemented any RPC methods that will give a non-zero balance
```
```
Note that since we don't have keygen yet, I've just hardcoded an address which is assumed to have a zero balance in the local validator. See also https://xkcd.com/221/

refactor(experimental): add the `getBalance` RPC method

---

packages/rpc-core/package.json
packages/rpc-core/src/rpc-methods/__tests__/get-balance-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-block-height-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-inflation-reward-test.ts
packages/rpc-transport/package.json
packages/rpc-transport/src/__tests__/http-transport-test.ts
packages/rpc-transport/src/http-request.ts
packages/rpc-transport/src/json-rpc-transport/index.ts
packages/rpc-transport/src/json-rpc-transport/json-rpc-transport-types.ts
packages/test-config/package.json
packages/test-config/setup-fetch-mock.ts
packages/tsconfig/base.json
pnpm-lock.yaml

refactor(experimental): introduce the ability to be able to cancel rpc requests
The `send()` and `sendBatch()` APIs give us a logical per-request API surface to pass in an `AbortSignal`. Whenever that signal is triggered, we can pass it to the underlying transport implementation (in this case, `fetch`).
```
```

refactor(experimental): introduce the ability to be able to cancel rpc requests

---

packages/rpc-transport/src/__tests__/http-transport-test.ts
packages/rpc-transport/src/http-request.ts

refactor(experimental): Send the content length along with each request
After `JSON` stringifying the payload, count its byte length and include that as the `Content-Length` header. Also mark the `Content-Type` as `UTF-8`
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1264).
* #1266
* #1265
* __->__ #1264

refactor(experimental): Send the content length along with each request

---

packages/rpc-transport/src/__tests__/http-transport-test.ts
packages/rpc-transport/src/http-request.ts

refactor(experimental): only accept `application/json` encoding through the RPC
That's all we understand.
```
pnpm turbo test:unit:browser test:unit:node
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1265).
* #1266
* __->__ #1265

refactor(experimental): only accept `application/json` encoding through the RPC

---

packages/library/src/__tests__/rpc-test.ts
packages/library/src/rpc.ts
packages/rpc-transport/src/__tests__/http-request-headers-test.ts
packages/rpc-transport/src/__tests__/http-transport-test.ts
packages/rpc-transport/src/http-request-headers.ts
packages/rpc-transport/src/http-request.ts
packages/rpc-transport/src/json-rpc-transport/__tests__/json-rpc-transport-test.ts
packages/rpc-transport/src/json-rpc-transport/index.ts
packages/rpc-transport/src/json-rpc-transport/json-rpc-transport-types.ts
packages/test-config/global.d.ts
packages/test-config/jest-unit.config.common.ts
packages/test-config/setup-dev-mode.ts

refactor(experimental): allow the RPC to be configured with custom headers
Pains were taken to prevent forbidden headers from being configured on a transport, and to prevent headers necessary for the operation of the JSON-RPC from being overwritten, but otherwise you're free to supply your own custom headers.
```ts
const rpc = createDefaultRpc({url: 'https://api.devnet.solana.com', headers: {'My-Custom-Header': 'customValue'}});
rpc.getBlockHeight().send();
```
```
```

refactor(experimental): allow the RPC to be configured with custom headers

---

packages/rpc-transport/src/transports/http/__tests__/http-transport-agent-test.ts
packages/rpc-transport/src/transports/http/http-transport.ts

refactor(experimental): you can now configure an HTTP agent on a trasnport
Notably we are _not_ going to create one by default. Agent configuration is RPC specific and can change over time. We do not want to be prescriptive here.
```
```

refactor(experimental): you can now configure an HTTP agent on a trasnport

---

packages/rpc-transport/src/__tests__/json-rpc-test.ts
packages/rpc-transport/src/json-rpc-types.ts
packages/rpc-transport/src/json-rpc.ts

refactor(experimental): delete the batch API
I had a long discussion with RPC providers about the JSON-RPC batch API.
In summary,
* it causes problems with resource exhaustion,
* makes it difficult to balance load,
…on top of having the user-facing drawbacks of,
* blowing the entire request up if even one method fails,
* making the entire batch take as long as the slowest request
For all of these reasons, and the detail that I go into [here](https://twitter.com/steveluscher/status/1532443998488363008), we're going to eliminate the batch API as designed here.
*This doesn't mean that you can't still batch in Solana apps*.
1. In fact, you can use the API that remains to do _proper_ batching using JavaScript primitives,
2. We're going to commit to delivering HTTP/2 pipelining in web3.js in …

refactor(experimental): delete the batch API

---

packages/library/package.json
turbo.json

What I really want to happen here is for the new `web3.js` library to be published such that anyone can install it by doing `npm install @solana/web3.js@experimental`.
Finally put in the work on the build system to do that.

chore: create a special publish step just for the experimental package

---

packages/build-scripts/package.json
packages/fetch-impl/package.json
packages/fetch-impl/tsconfig.declarations.json
packages/rpc-transport/package.json
pnpm-lock.yaml

refactor(experimental): downgrade to a version of `node-fetch` that's compatible with CJS

refactor(experimental): downgrade to a version of `node-fetch` that's compatible with CJS

---

packages/keys/src/base58.ts
packages/rpc-core/src/rpc-methods/__tests__/get-balance-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-block-production-test.ts

refactor(experimental): allow literal `Base58EncodedAddress` types
If you want to not only assert that something is a base58 address, but a _particular_ base58 address you can make use of this new optional type parameter.
```ts
const memoProgramV2Address = 'MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr';
assertIsBase58EncodedAddress(memoProgramV2Address);
memoProgramV2Address as Base58EncodedAddress; // OK
memoProgramV2Address as Base58EncodedAddress<'MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr'>; // OK
memoProgramV2Address as Base58EncodedAddress<'Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo'>; // ERROR
```

refactor(experimental): allow literal `Base58EncodedAddress` types

---

packages/rpc-core/src/rpc-methods/__tests__/get-epoch-info-test.ts
packages/rpc-core/src/rpc-methods/getEpochInfo.ts
packages/rpc-core/src/rpc-methods/index.ts

Adds the `getEpochInfo` RPC method
Note that [the current docs](https://docs.solana.com/api/http#getepochinfo) are incorrect, this method doesn't take an address parameter. Fix in https://github.com/solana-labs/solana/pull/31651

refactor(experimental): add the `getEpochInfo` RPC method

---

packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-recent-performance-samples-test.ts
packages/rpc-core/src/rpc-methods/getRecentPerformanceSamples.ts
packages/rpc-core/src/rpc-methods/index.ts

Adds the `getRecentPerformanceSamples` RPC method which returns the latest performance samples
Currently the performance sample rate is 60s, so we don't have any data for the first 60s. This makes it impossible to meaningfully unit test this for now. We'll need to find a way to create performance samples without waiting 60s.

Refactor (experimental): add the `getRecentPerformanceSamples`  RPC method

---

packages/rpc-core/src/__tests__/unix-timestamp-test.ts
packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-block-time-test.ts
packages/rpc-core/src/rpc-methods/common.ts
packages/rpc-core/src/rpc-methods/getBlockTime.ts
packages/rpc-core/src/rpc-methods/index.ts
packages/rpc-core/src/unix-timestamp.ts

Adds the `getBlockTime` RPC method
Note that I think [the current docs](https://docs.solana.com/api/http#getblocktime) are slightly incorrect, this method doesn't return null. It either returns the block time or an error. Fix in https://github.com/solana-labs/solana/pull/31653
Note that tests here are limited. I think there are 3 responses:
- Returns the block time for an available block. For this to be reliable in tests we need to either get an available block (eg using `getFirstAvailableBlock` when implemented), or be able to control the ledger so that a certain block is guaranteed to be available
- Returns an error when a block has been cleaned up. For this to be performant in tests we'll need a way to control the ledger so that a block is cleaned up, without waiting however long that …

refactor(experimental): add the `getBlockTime` RPC method

---

packages/rpc-core/src/rpc-methods/__tests__/get-supply-test.ts
packages/rpc-core/src/rpc-methods/getSupply.ts
packages/rpc-core/src/rpc-methods/index.ts

Adds the `getSupply` RPC method which returns the circulating/total SOL. It also returns `nonCirculatingAccounts`, which is a list of non-circulating account addresses. When called with `excludeNonCirculatingAccountsList: true`, this is an empty list.
I've found that in the test validator we start with no non-circulating accounts, and then quickly get a lot of them. But for now I've skipped the tests that require a non-empty list to be returned.

Refactor (experimental): add getSupply RPC method

---

packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-vote-accounts.ts
packages/rpc-core/src/rpc-methods/getVoteAccounts.ts
packages/rpc-core/src/rpc-methods/index.ts

Adds the `getVoteAccounts` RPC method which returns the current + delinquent voting accounts
I've found that in the test validator we start with no vote accounts, and then get 1 current one. To test this in more depth we'll need a way to create active + delinquent ones and modify their stakes.
Note that when called with `votePubkey` the response is narrowed a bit, but I haven't modeled this in the types. This is because there are 3 possible responses:
- `current` with length 1 and `delinquent` with length 0, if the `votePubkey` is active
- `current` with length 0 and `delinquent` with length 1, if the `votePubkey` is not active
- `current` with length 0 and `delinquent` with length 0, if the pubkey is not a vote account, or if it's filtered out by `keepUnstakedDelinquents`
I don't think …

refactor(experimental): add the `getVoteAccounts` RPC method

---

packages/library/package.json
packages/library/src/__tests__/rpc-request-coalescer-test.ts
packages/library/src/__tests__/rpc-request-deduplication-test.ts
packages/library/src/rpc-request-coalescer.ts
packages/library/src/rpc-request-deduplication.ts
packages/library/src/rpc-transport.ts
pnpm-lock.yaml

refactor(experimental): coalesce requests with identical in-flight requests
Throwback to #1208. There, we implemented something I call ‘request coalescing’ at the request of @Jac0xb. He was doing a _ton_ of transaction confirmations in a long-running process, all of them using the blockheight-based confirmation strategy. This resulted in a _ton_ of `getBlockHeight` requests to their RPC infra.
We decided that because the block height depends on nothing but time, essentially, that there was no point in firing off multiple of these requests at the same time. Instead we coalesced all calls into a single request; we either started a new request or associated our request with the currently-in-fight request. This ensured that there was only one request for the same arguments in flight at any …

refactor(experimental): coalesce requests with identical in-flight requests

---

packages/library-legacy/src/loader.ts

fix: wait until the slot after a program is deployed
https://github.com/solana-labs/solana/pull/29654 introduced a delay between the slot a program is deployed and when it can be called. Let's build this into the loader now so as to remove a footgun from folks trying to call programs immediately after deploying them.
```
pnpm test:live-with-test-validator
```

fix: wait until the slot after a program is deployed

---

packages/library-legacy/src/connection.ts
packages/library-legacy/test/connection.test.ts

feat: add `withContext` flag to `getProgramAccounts`
This was missing. When supplied, the RPC wraps the result in a context object.
Fixes #1285.
```
pnpm test:live-with-test-validator
```

feat: add `withContext` flag to `getProgramAccounts`

---

packages/library-legacy/src/transaction/legacy.ts

Need deterministic pubkey sorting that is not dependent on browser locale
Supply the default options listed on [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator) and specify a static locale (`'en'`).
Fixes #1094.

fix: locale independent sort

---

packages/library-legacy/src/connection.ts

when using `connection.getProgramAccounts(<public-key>)`, without a config argument, the return type is `RpcResponseAndContext<GetProgramAccountsResponse>` while configOrCommitment is false so it does not run the function returning the context. This result into an error at runtime for anyone trying to access `value`.

fix: Fix getPA type when config is undefined

---

packages/rpc-core/src/rpc-methods/__tests__/get-epoch-schedule-test.ts
packages/rpc-core/src/rpc-methods/getEpochSchedule.ts
packages/rpc-core/src/rpc-methods/index.ts

Nice straightforward RPC method for once! Used in the `ClusterProvider` in explorer, which would be good to migrate to new web3js!

refactor(experimental): add the getEpochSchedule RPC method

---

packages/rpc-core/src/__tests__/stringified-bigint-test.ts
packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-token-largest-accounts-test.ts
packages/rpc-core/src/rpc-methods/getTokenLargestAccounts.ts
packages/rpc-core/src/rpc-methods/getTransaction.ts
packages/rpc-core/src/rpc-methods/index.ts
packages/rpc-core/src/stringified-bigint.ts
pnpm-lock.yaml

This PR adds the `getTokenLargestAccounts` RPC method. This is used by the shared `MintsProvider` in explorer, which we should migrate to new web3js
We can't test this on the local validator yet, since we have no way to create a token mint + accounts. But I have tested on devnet using this test:
```ts
it('manual test with devnet', async () => {
const tokenMint = '4HZCNvobxtDA3uezTGmDAEqVLp7oo73UrnbxNeUMszd4' as Base58EncodedAddress;
const tokenAccounts = await rpc.getTokenLargestAccounts(tokenMint).send().then(r => r.value);
expect(tokenAccounts.length).toEqual(20);
expect(tokenAccounts[0]).toMatchObject({
address: expect.any(String),
amount: expect.any(String),
decimals: expect.any(Number),
uiAmount: expect.any(Number),
uiAmountString: expect.any(String)
});
});
```

refactor(experimental): add the getTokenLargestAccounts RPC method

---

packages/transactions/package.json
packages/transactions/src/blockhash.ts
packages/transactions/src/durable-nonce.ts
packages/transactions/src/index.ts
pnpm-lock.yaml

refactor(experimental): types that describe the lifetime of a transaction
There are two ways to describe the lifetime of a transaction: either with a ‘recent’ blockhash or with a durable nonce. This PR introduces the types that describe those two lifetimes.
Observe this is a type error because there is no `AdvanceNonce` instruction.
```ts
const tx: BaseTransaction & IDurableNonceTransaction = {
lifetimeConstraint: {
nonce: 'abc',
},
instructions: [],
version: 0,
};
```
Observe this typechecks:
```ts
const tx: BaseTransaction & IDurableNonceTransaction = {
instructions: [
{
accounts: [
{
address: 'abc' as Base58EncodedAddress,
isSigner: false,
isWritable: true,
},
{
address:
'SysvarRecentB1ockHashes11111111111111111111' as Base58EncodedAddress<'SysvarRecentB1ockHashes11111111111111111111'>, …
```

refactor(experimental): types that describe the lifetime of a transaction

---

packages/transactions/src/index.ts
packages/transactions/src/signatures.ts

refactor(experimental): basic types for transactions with signatures
This PR introduces just the very basic types that describe whether a transaction has signatures or not, including an opaque type that we can use to denote a transaction which is _fully_ signed.
None yet.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1348).
* #1351
* #1350
* #1349
* __->__ #1348

refactor(experimental): basic types for transactions with signatures

---

packages/transactions/src/__tests__/instructions-test.ts
packages/transactions/src/index.ts
packages/transactions/src/instructions.ts

refactor(experimental): a helper to add instructions to a transaction
This helper takes care of appending instructions to the list, and unsetting the signatures each time a new instruction is added.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1350).
* #1351
* __->__ #1350

refactor(experimental): a helper to add instructions to a transaction

---

packages/transactions/package.json
packages/transactions/src/serializers/__tests__/transaction-version-test.ts
packages/transactions/src/serializers/transaction-version.ts
pnpm-lock.yaml

refactor(experimental): a serializer for the transaction version header
This is the very first transaction serializer. It demonstrates how we'll use the serializer from Metaplex's Umi library to define custom serializers for transactions.
```
```

refactor(experimental): a serializer for the transaction version header

---

packages/instructions/package.json
packages/instructions/src/__tests__/roles-test.ts
packages/instructions/src/accounts.ts
packages/instructions/src/index.ts
packages/instructions/src/roles.ts

refactor(experimental): convert signer-writability flags on accounts into `role` enum
Instead of tweaking `isSigner` and `isWritable` flags on account metadata, let's create one enum to describe all four combinations. This enables us to finally treat account metadata as a discriminated union in TypeScript. That is to say that checking an account's `role` will now refine its type down to the type containing that role.
* Makes code less verbose, particularly tests
* Makes it less tempting to mutate an object in-place by twiddling the boolean of `isSigner` or `isWritable`
See next PRs.

refactor(experimental): convert signer-writability flags on accounts into `role` enum

---

packages/transactions/src/__tests__/compile-lifetime-token-test.ts
packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/compile-lifetime-token.ts
packages/transactions/src/message.ts

refactor(experimental): a function to compile a transaction's lifetime into a message
This is the beginning of the message compiler. In this step, we process the transaction's lifetime constraint into a simple lifetime _token_ of the message.
* for transactions whose lifetimes are constrained by a recent blockhash, the token becomes the blockhash
* for transactions whose lifetimes are constrained by a durable nonce, the token becomes the nonce
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1359).
* #1365
* #1364
* #1363
* #1362
* #1361
* #1360
* __->__ #1359

refactor(experimental): a function to compile a transaction's lifetime into a message

---

packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/message.ts

refactor(experimental): a function to compile a transaction's version into a message
This code compiles a transaction's version into a message data structure.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1360).
* #1365
* #1364
* #1363
* #1362
* #1361
* __->__ #1360

refactor(experimental): a function to compile a transaction's version into a message

---

packages/transactions/src/__tests__/accounts-test.ts
packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/accounts.ts
packages/transactions/src/message.ts

refactor(experimental): a function to compile a transaction into an ordered list of accounts
There is a very particular way in which accounts are laid out in Solana transactions that get sent to the network. Signers before non signers. Writable accounts before readonly accounts. Static accounts before lookup table accounts. Invoked accounts may sign transactions but may never be writable. The list goes on.
In this PR, we encode all of this logic and write copious tests for it. What results is a function that can take in a transaction (fee payer + instructions) and produce an ordered list of accounts ready to be serialized into a transactions wire format.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). …

refactor(experimental): a function to compile a transaction into an ordered list of accounts

---

packages/transactions/src/__tests__/compile-instructions-test.ts
packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/compile-instructions.ts
packages/transactions/src/message.ts

refactor(experimental): a function to compile a transaction's instructions into a message
Over the wire, transaction instructions don't carry the addresses that they refer to, but rather the _indices_ of those addresses in a sidecar address table. This function takes in the ordered addresses and the instructions, and returns the instructions with the addresses replaced with indices.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1363).
* #1372
* #1371
* #1370
* #1369
* #1368
* #1365
* #1364
* __->__ #1363

refactor(experimental): a function to compile a transaction's instructions into a message

---

packages/transactions/src/__tests__/compile-instructions-test.ts
packages/transactions/src/__tests__/compile-static-accounts.ts
packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/compile-instructions.ts
packages/transactions/src/compile-static-accounts.ts
packages/transactions/src/message.ts

refactor(experimental): a function to compile a transaction's static accounts into a message
In this PR we simply map over the ordered accounts and output the address associated with each, but only for static accounts.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1364).
* #1372
* #1371
* #1370
* #1369
* #1368
* #1365
* __->__ #1364
* #1363

refactor(experimental): a function to compile a transaction's static accounts into a message

---

packages/transactions/src/__tests__/compile-address-table-lookups-test.ts
packages/transactions/src/__tests__/compile-instructions-test.ts
packages/transactions/src/__tests__/compile-static-accounts.ts
packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/compile-address-table-lookups.ts
packages/transactions/src/compile-instructions.ts
packages/transactions/src/compile-static-accounts.ts
packages/transactions/src/message.ts

refactor(experimental): a function to compile a transaction's address table lookups into a message
Once we have an ordered list of accounts, producing the address table lookups for a transaction is a matter of rolling them up into a `Vec<MessageAddressTableLookup>`. This PR implements that.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1365).
* #1372
* #1371
* #1370
* #1369
* #1368
* __->__ #1365
* #1364
* #1363

refactor(experimental): a function to compile a transaction's address table lookups into a message

---

packages/keys/package.json
packages/keys/src/__tests__/base58-test.ts
packages/keys/src/base58.ts
packages/rpc-core/package.json
packages/rpc-core/src/__tests__/blockhash-test.ts
packages/rpc-core/src/__tests__/transaction-signature-test.ts
packages/rpc-core/src/blockhash.ts
packages/rpc-core/src/transaction-signature.ts
pnpm-lock.yaml

refactor(experimental): bye bye `bs58`
This library is very frustrating in that it's large, not tree-shakable, and esm-only. Let's switch it out for Umi's slimmed down implementation.
```
```

refactor(experimental): bye bye `bs58`

---

packages/transactions/package.json
packages/transactions/src/serializers/__tests__/transaction-version-test.ts
packages/transactions/src/serializers/transaction-version.ts
packages/transactions/src/serializers/unimplemented.ts
pnpm-lock.yaml

refactor(experimental): set up a pattern for splitting the serializers into co/dec/codec slices
Most use cases for these serializers will only ever need to encode or decode, never both. This PR sets up a standard for splitting serializers into a version that encodes, decodes, or does both. Import the one you need, and let your build system tree-shake the other one away.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1368).
* #1374
* #1373
* #1372
* #1370
* #1369
* __->__ #1368

refactor(experimental): set up a pattern for splitting the serializers into co/dec/codec slices

---

packages/transactions/src/serializers/__tests__/header-test.ts
packages/transactions/src/serializers/header.ts

refactor(experimental): a serializer for the transaction message header
This simple data structure tracks the count of signer, readonly-signer, and readonly-nonsigner addresses the parser should expect to find in the static accounts list.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1369).
* #1374
* #1373
* #1372
* #1370
* __->__ #1369

refactor(experimental): a serializer for the transaction message header

---

packages/transactions/src/serializers/__tests__/address-test.ts
packages/transactions/src/serializers/__tests__/instruction-test.ts
packages/transactions/src/serializers/address.ts
packages/transactions/src/serializers/instruction.ts

refactor(experimental): a serializer for transaction instructions
This serializer commutes between `IInstruction` and the wire format of program-index/compact-account-address-indices/compact-array-of-data.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1372).
* #1374
* #1373
* __->__ #1372
* #1370

refactor(experimental): a serializer for transaction instructions

---

packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/message.ts

refactor(experimental): disambiguate between legacy and versioned messages in the message compiler
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1375).
* #1374
* #1373
* #1376
* __->__ #1375

refactor(experimental): disambiguate between legacy and versioned messages in the message compiler

---

packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/message.ts
packages/transactions/src/serializers/__tests__/instruction-test.ts
packages/transactions/src/serializers/instruction.ts

refactor(experimental): omit properties when deserializing instructions without addresses or data
Loris showed me a good way to do this. Now we don't have to suffer with present-but-undefined properties.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1376).
* #1374
* #1373
* __->__ #1376
* #1375

refactor(experimental): omit properties when deserializing instructions without addresses or data

---

packages/transactions/src/serializers/__tests__/address-table-lookup-test.ts
packages/transactions/src/serializers/address-table-lookup.ts
packages/transactions/src/serializers/address.ts

refactor(experimental): a seriailzer for address table lookups
An address table lookup forms part of v0 transactions. Each one contains the address of the lookup table account itself, the indices of the accounts within that should be write-locked, and the indices of the accounts that should be read-only.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1373).
* #1374
* __->__ #1373

refactor(experimental): a seriailzer for address table lookups

---

packages/transactions/src/serializers/__tests__/address-table-lookup-test.ts
packages/transactions/src/serializers/__tests__/message-test.ts
packages/transactions/src/serializers/address-table-lookup.ts
packages/transactions/src/serializers/address.ts
packages/transactions/src/serializers/message.ts

refactor(experimental): a serializer for the compiled message of a transaction
This is the big one. This brings together every serializer into one codec for a transaction message. These are the bytes that will be signed by the signers' private keys. Given this, and the signatures, we will have a transaction that can be landed on the network.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1374).
* __->__ #1374
* #1373

refactor(experimental): a serializer for the compiled message of a transaction

---

packages/rpc-core/src/index.ts

These types are intended to be exported, so that apps can create/pass them around. They follow the same pattern as `blockhash` which is exported.

Export some more required types from rpc-core

---

packages/rpc-core/src/rpc-methods/__tests__/is-blockhash-valid-test.ts
packages/rpc-core/src/rpc-methods/index.ts
packages/rpc-core/src/rpc-methods/isBlockhashValid.ts

Add the IsBlockhashValid API + unit tests
Testing wise i can see other methods sometimes only expect the type, do we want a true/false for this API? It will have to depend on read from another API if we want to exercise `true`

refactor(experimental): Add IsBlockhashValid API

---

packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-account-info-test.ts
scripts/fixtures/CSg2vQGbnwWdSyJpwK4i3qGfB6FebaV3xQTx4U1MbixN.json
scripts/fixtures/GQE2yjns7SKKuMc89tveBDpzYHwXfeuB2PGAbGaPWc6G.json

This PR adds unit tests for the `getAccountInfo` RPC call. I'm probably going to end up refactoring this a bit to add `getMultipleAccounts` and `getProgramAccounts` so I want some tests first
Note that I've been unable to test the `jsonParsed` fully. I tried copying the data from a mainnet stake account (where `jsonParsed` works) into a fixture, but requesting `jsonParsed` encoding just returns the base64 encoding. I'm not sure if the test validator is missing the parsers?

refactor(experimental): add unit tests for getAccountInfo RPC method

---

packages/rpc-core/src/rpc-methods/__tests__/get-slot-leaders-test.ts
packages/rpc-core/src/rpc-methods/getSlotLeaders.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getSlotLeaders` RPC method
I've used `minimumLedgerSlot` which we already have implemented to find a valid start slot for the test
Note that the docs mistakenly say these params are optional but they're required, see docs PR: https://github.com/solana-labs/solana/pull/32376

refactor(experimental): add the getSlotLeaders RPC method

---

packages/test-config/jest-unit.config.common.ts
packages/test-config/jest-unit.config.node.ts
packages/test-config/setup-node-crypto.ts
packages/test-config/setup-webcrypto.ts

refactor(experimental): shim `Crypto` in both browser and Node environments
The idea here is that we're going to _presume_ that the browser has an Ed25519-compatible key generator, then polyfill it otherwise. From that perspective, the tests should just presume that it's present, and we should leave the testing of the polyfill up to the polyfill tests.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1392).
* #1400
* #1399
* #1398
* #1397
* #1396
* #1395
* #1394
* #1379
* #1393
* __->__ #1392

refactor(experimental): shim `Crypto` in both browser and Node environments

---

packages/keys/src/__tests__/guard-test.ts
packages/keys/src/guard.ts
packages/keys/tsconfig.json
packages/test-config/jest-unit.config.common.ts
packages/test-config/jest-unit.config.node.ts
packages/test-config/setup-node-crypto.ts
packages/test-config/setup-webcrypto.ts

refactor(experimental): assertion functions that you can use to determine whether Ed25519 is supported
It's just nice to have these well tested, and all in one place. These will only become more complicated, so it's best to get them out of the code.
Only thing is, I wish that TypeScript could assert about globals: https://stackoverflow.com/q/76657623/802047
```
cd packages/keys/
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1393).
* #1400
* #1399
* #1398
* #1397
* #1396
* #1395
* #1394
* #1379
* __->__ #1393
* #1392

refactor(experimental): assertion functions that you can use to determine whether Ed25519 is supported

---

packages/keys/README.md
packages/keys/src/__tests__/guard-test.ts
packages/keys/src/__tests__/key-pair-test.ts
packages/keys/src/guard.ts
packages/keys/src/index.ts
packages/keys/src/key-pair.ts
packages/keys/tsconfig.json
packages/test-config/jest-unit.config.common.ts
packages/test-config/jest-unit.config.node.ts
packages/test-config/setup-node-crypto.ts
packages/test-config/setup-webcrypto.ts

refactor(experimental): a function for generating secret keys
This PR introduces `generateSecretKey()`. You might need to use this when you need to sign for the creation of an account, for instance.
Instead of vending the _bytes_ of a secret key, however, we use JS-native `CryptoKey` instances. These are opaque tokens that you can return at a later time to perform some action, like deriving the public key for the secret they represent, or signing a message.
The idea is that you can freely pass these `CryptoKey` instances around your application without worrying about accidentally logging the key material itself – ie. to Sentry or to the browser console.
The only environments that support Ed25519 key generation at the moment:
* Node >=17.4
* Safari 17
For other environments, we'll supply a …

refactor(experimental): a function for generating secret keys

---

packages/keys/README.md
packages/keys/src/__tests__/pubkey-test.ts
packages/keys/src/index.ts
packages/keys/src/pubkey.ts

refactor(experimental): a function to convert a public key into a base 58 encoded address
This is useful in cases where you, yourself, generated a keypair, and now you need to display the public key in your UI. Otherwise, you will typically already have the `Base58EncodedAddress` object.
```
cd packages/keys/
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1394).
* #1400
* #1399
* #1398
* #1397
* #1396
* #1395
* __->__ #1394

refactor(experimental): a function to convert a public key into a base 58 encoded address

---

packages/library-legacy/src/utils/cluster.ts

This commit adds a small tweak to the documentation that explicitly states the possible choices that clusterApiUrl can take on.

Make Docs Explicitly state the possible options that clusterApiUrl can take on

---

packages/webcrypto-ed25519-polyfill/src/__tests__/secrets-test.ts
packages/webcrypto-ed25519-polyfill/src/secrets.ts

refactor(experimental): a function that tells you whether a `CryptoKey` belongs to the polyfill or not
Only keys produced with the polyfill's `generateKey` method are usable with its other methods. Having been produced with the polyfill keygen is the same as ‘being present in the key store,’ hence this simple test.
```
cd packages/webcrypto-ed25519-polyfill
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1396).
* #1416
* #1415
* #1414
* #1413
* #1412
* #1400
* #1399
* #1398
* #1397
* __->__ #1396

refactor(experimental): a function that tells you whether a `CryptoKey` belongs to the polyfill or not

---

packages/webcrypto-ed25519-polyfill/README.md
packages/webcrypto-ed25519-polyfill/src/__tests__/index-test.ts
packages/webcrypto-ed25519-polyfill/src/__tests__/secrets-test.ts
packages/webcrypto-ed25519-polyfill/src/index.ts
packages/webcrypto-ed25519-polyfill/src/secrets.ts

refactor(experimental): a polyfill for `SubtleCrypto#verify`
Given a key that was created with `generateKeyPolyfill`, this method will verify that the supplied signature was produced by sigining the supplied data with the private key associated with the supplied public key.
```ts
cd packages/webcrypto-ed25519-polyfill
pnpm test:node:browser
pnpm test:node:node
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1400).
* #1422
* #1421
* #1424
* #1420
* #1419
* #1416
* #1415
* #1414
* #1413
* #1412
* __->__ #1400

refactor(experimental): a polyfill for `SubtleCrypto#verify`

---

packages/keys/src/__tests__/guard-test.ts
packages/keys/src/__tests__/key-pair-test.ts
packages/keys/src/__tests__/pubkey-test.ts
packages/keys/src/__tests__/signatures-test.ts
packages/test-config/jest-unit.config.browser.ts
packages/test-config/setup-secure-context.ts
packages/webcrypto-ed25519-polyfill/src/__tests__/index-test.ts

refactor(experimental): make `true` the default for `isSecureContext` in tests
This makes tests much more simple.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1412).
* #1422
* #1421
* #1420
* #1419
* #1416
* #1415
* #1414
* #1413
* __->__ #1412

refactor(experimental): make `true` the default for `isSecureContext` in tests

---

packages/rpc-core/src/rpc-methods/__tests__/request-airdrop-test.ts
packages/rpc-core/src/rpc-methods/index.ts
packages/rpc-core/src/rpc-methods/requestAirdrop.ts

refactor(experimental): an rpc method to request airdrops
Use this method anywhere but mainnet to request that an account be credited with some small number of lamports.
```
cd packages/rpc-core/
```

refactor(experimental): an rpc method to request airdrops

---

packages/library-legacy/src/keypair.ts
packages/library-legacy/src/transaction/legacy.ts
packages/library-legacy/src/utils/cluster.ts

This pull request adds some minor JSDoc to the legacy keypair, transaction, and clusterApiUrl API so that they actually show up in the dev's LSP hover instead of having to dig through the documentation themselves.

Update JSDoc of the legacy keypair, transaction, and clusterApiUrl API

---

packages/transactions/src/__tests__/blockhash-test.ts
packages/transactions/src/__tests__/compile-lifetime-token-test.ts
packages/transactions/src/blockhash.ts
packages/transactions/src/durable-nonce.ts

refactor(experimental): a function that you can use to apply a blockhash to a transaction
Use this function to apply a blockhash lifetime constraint to a transaction, unsetting the signatures if there are any and widening the type in case the transaction used to be a durable nonce transaction.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1432).
* #1436
* #1435
* #1434
* #1433
* __->__ #1432

refactor(experimental): a function that you can use to apply a blockhash to a transaction

---

packages/transactions/src/blockhash.ts
packages/transactions/src/fee-payer.ts
packages/transactions/src/instructions.ts
packages/transactions/src/unsigned-transaction.ts

refactor(experimental): extract `getUnsignedTransaction` logic into helper
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1433).
* #1436
* #1435
* #1434
* __->__ #1433

refactor(experimental): extract `getUnsignedTransaction` logic into helper

---

packages/transactions/src/blockhash.ts
packages/transactions/src/fee-payer.ts
packages/transactions/src/instructions.ts
packages/transactions/src/signatures.ts
packages/transactions/src/unsigned-transaction.ts

refactor(experimental): update type of `signatures` record to `Record`
This is so that it can be indexed by `Base58EncodedAddress`
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1434).
* #1436
* #1435
* __->__ #1434
* #1433

refactor(experimental): update type of `signatures` record to `Record`

---

packages/transactions/src/__tests__/durable-nonce-test.ts
packages/transactions/src/blockhash.ts
packages/transactions/src/durable-nonce.ts
packages/transactions/src/fee-payer.ts
packages/transactions/src/instructions.ts
packages/transactions/src/signatures.ts
packages/transactions/src/unsigned-transaction.ts

refactor(experimental): an assertion function that refines the type of a transaction to `IDurableNonceTransaction`
Given a transaction of an unknown shape, use this Typescript assertion method to narrow its type to `IDurableNonceTransaction` or throw.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1435).
* #1436
* __->__ #1435
* #1434
* #1433

refactor(experimental): an assertion function that refines the type of a transaction to `IDurableNonceTransaction`

---

packages/fetch-impl/src/index.node.ts
packages/library-legacy/src/connection.ts
packages/library-legacy/src/fetch-impl.ts

fix: use the native `fetch()` in Node wherever supported
Folks are having trouble using the `node-fetch` polyfill with certain RPC providers that:
* use chunked-transfer encoding
* don't send a zero-sized chunk before closing the socket
`node-fetch` doesn't like this, and fatals.
One easy thing we can do while we figure this all out is to use the _native_ `fetch()` API included in Node 18+ by default and 17.5+ behind an experimental flag.
Fixes #1418 in Node 18+.
CI run.

fix: use the native `fetch()` in Node wherever supported

---

packages/addresses/README.md
packages/addresses/src/__tests__/program-derived-address-test.ts
packages/addresses/src/index.ts
packages/addresses/src/program-derived-address.ts

refactor(experimental): a function to compute program derived addresses
Given a program address and a series of string or bytearray seeds, this function will compute the off-chain program derived address (PDA) corresponding to both.
```
cd packages/addresses
```

refactor(experimental): a function to compute program derived addresses

---

packages/rpc-core/src/rpc-methods/index.ts

- We use `Commitment` as part of the input config for many calls, so it's useful to export it so that consumers can pass it around/create it in their code. Otherwise you need to hardcode a compliant string value in code for each RPC call
- It's not feasible to use `Parameters ` or similar to obtain this type because it's usually optional and nested in a config object
I've also checked the other inputs for RPC methods and I can't see anything else likely to cause issues.
Tested by compiling `@packages/rpc-core` and then seeing `import type { Commitment } from '@solana/rpc-core` in a dependent package no longer errors.

Export Commitment type to consumers

---

packages/rpc-core/src/rpc-methods/__tests__/get-block-commitment-test.ts
packages/rpc-core/src/rpc-methods/getBlockCommitment.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getBlockCommitment` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): Add the `getBlockCommitment` RPC method

---

packages/rpc-core/src/rpc-methods/__tests__/get-cluster-nodes-test.ts
packages/rpc-core/src/rpc-methods/getClusterNodes.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the getBlockCommitment RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): Add the `getClusterNodes` RPC method

---

packages/rpc-core/src/rpc-methods/__tests__/get-highest-snapshot-slot-test.ts
packages/rpc-core/src/rpc-methods/getHighestSnapshotSlot.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getHighestSnapshotSlot` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getHighestSnapshotSlot` API method

---

packages/rpc-core/src/rpc-methods/__tests__/get-genesis-hash-test.ts
packages/rpc-core/src/rpc-methods/getGenesisHash.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getGenesisHash` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getGenesisHash` API method

---

packages/rpc-core/package.json
packages/rpc-core/src/rpc-methods/__tests__/get-blocks-with-limit-test.ts
packages/rpc-core/src/rpc-methods/getBlocksWithLimit.ts
packages/rpc-core/src/rpc-methods/index.ts
pnpm-lock.yaml

This PR adds the `getBlocksWithLimit` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449 
---
I will say adding this method pointed out some strange behavior with the RPC that I'm curious about:
- If you provide a valid slot number and a limit of `0`, you get an empty array
- If you provide a slot number greater than the current slot, you get an empty array
The behavior of getting an empty array rather than an error seems strange, no?

refactor(experimental): Add the `getBlocksWithLimit` RPC method

---

packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/__tests__/wire-transaction-test.ts
packages/transactions/src/compile-instructions.ts
packages/transactions/src/serializers/__tests__/instruction-test.ts
packages/transactions/src/serializers/__tests__/message-test.ts
packages/transactions/src/serializers/instruction.ts

refactor(experimental): repair bad address index compilation
The code had `addressIndices` in some places and `accountIndices` in others, and I missed it in the wire serialization test. This consolidates on `accountIndices`
```
```

refactor(experimental): repair bad address index compilation

---

packages/rpc-core/src/rpc-methods/__tests__/get-genesis-hash-test.ts

This PR fixes the regex for grabbing the genesis hash from the validator logs. The length specifier previously used (44) is likely to fail whenever the raw bytes produce a shorter base58 encoding

test: fix genesis hash regex

---

packages/rpc-core/src/rpc-methods/__tests__/get-recent-prioritization-fees-test.ts
packages/rpc-core/src/rpc-methods/common.ts
packages/rpc-core/src/rpc-methods/getRecentPrioritizationFees.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the`getRecentPrioritizationFees` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getRecentPrioritizationFees` method

---

packages/rpc-core/src/rpc-methods/__tests__/get-signature-statuses-test.ts
packages/rpc-core/src/rpc-methods/getSignatureStatuses.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds`getSignatureStatuses` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getSignatureStatuses` method

---

packages/rpc-core/src/rpc-methods/__tests__/get-stake-activation-test.ts
packages/rpc-core/src/rpc-methods/getStakeActivation.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getStakeActivation` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getStakeActivation` API method

---

packages/rpc-core/src/rpc-methods/__tests__/get-fee-for-message-test.ts
packages/rpc-core/src/rpc-methods/getFeeForMessage.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getFeeForMessage` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getFeeForMessage` API method

---

packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-inflation-rate-test.ts
packages/rpc-core/src/rpc-methods/getInflationRate.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getInflationRate` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449 
---
Hyper-relevant to this PR is #1488. You can see I'm using number in place of what would be an ideal floating-point number handler for `f64`

refactor(experimental): add `getInflationRate` API method

---

packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-token-supply-test.ts
packages/rpc-core/src/rpc-methods/getTokenSupply.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getTokenSupply` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getTokenSupply` API method

---

packages/rpc-core/src/rpc-methods/__tests__/get-slot-leader-test.ts
packages/rpc-core/src/rpc-methods/getSlotLeader.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds`getSlotLeader` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getSlotLeader` method

---

packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-token-account-balance-test.ts
packages/rpc-core/src/rpc-methods/getTokenAccountBalance.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getTokenAccountBalance` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getTokenAccountBalance` API method

---

packages/rpc-core/src/rpc-methods/__tests__/get-identity-test.ts
packages/rpc-core/src/rpc-methods/getIdentity.ts
packages/rpc-core/src/rpc-methods/index.ts
packages/rpc-core/tsconfig.json

This PR adds the `getIdentity` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getIdentity` API method

---

packages/rpc-core/src/rpc-methods/getSignatureStatuses.ts

Sorry, this parameter should be required. It's labeled as optional in the docs, but I've changed it in my PR to the docs repo

refactor(experimental): Make signatures param for getSignaturesStatus required

---

packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-cluster-nodes-test.ts

Turns out these ports change!
Also added the `number` response fields to the bigint exemptions

refactor(experimental): Fix getClusterNodes test

---

packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/rpc-methods/__tests__/get-account-info-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-multiple-accounts-test.ts
packages/rpc-core/src/rpc-methods/getAccountInfo.ts
packages/rpc-core/src/rpc-methods/getMultipleAccounts.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds `getMultipleAccounts` to experimental web3js. The API code, numeric patcher exceptions and tests are based on `getAccountInfo`
Note that the change to `get-account-info-tests.ts` is just formatting: moving more tests into the when called with jsonParsed encoding > for an account with parse-able JSON data block 
Ref #1449

refactor(experimental): add `getMultipleAccounts` API method 

---

packages/rpc-core/src/rpc-methods/__tests__/get-largest-accounts-test.ts
packages/rpc-core/src/rpc-methods/getLargestAccounts.ts
packages/rpc-core/src/rpc-methods/index.ts

This PR adds the `getLargestAccounts` RPC method to the new experimental Web3 JS's arsenal.
Ref #1449

refactor(experimental): add `getLargestAccounts` API method

---

packages/rpc-core/src/rpc-methods/__tests__/get-genesis-hash-test.ts

We instead use a read stream to process the file in chunks
This avoids a bug where when validator.log gets too big locally the `fs.readFileSync` would fail
Fixes #1517

Fix: remove fs.readFileSync from genesis hash test

---

packages/addresses/README.md
packages/addresses/src/__tests__/public-key-test.ts
packages/addresses/src/public-key.ts
packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/signatures.ts

refactor(experimental): rename `getBase58AddressFromPublicKey` to `getAddressFromPublicKey`
@2501babe mentioned this being sort of unweildy to type for something that's going to be used a lot, so let's shorten it now.
Not changed:
* the `assertIs*` method
* the `get*Codec` method
* the `get*Comparator` method
CI run

refactor(experimental): rename `getBase58AddressFromPublicKey` to `getAddressFromPublicKey`

---

package.json

currently `pnpm build` runs the full test suite, which is very not conducive to working with the library as an external dependency. it makes it hard to tell when the compile is actually done and the rest can be aborted, and also it kills any `solana-test-validator` running and leaves behind its own after SIGINT
this changes the build command to just build

refactor(experimental): better build command

---

packages/rpc-core/src/rpc-methods/__tests__/get-genesis-hash-test.ts

test: get genesis hash from logfile with `readLines` API

test: get genesis hash from logfile with `readLines` API

---

packages/rpc-core/src/rpc-methods/common.ts
packages/rpc-core/src/rpc-methods/getTokenAccountBalance.ts
packages/rpc-core/src/rpc-methods/getTokenLargestAccounts.ts
packages/rpc-core/src/rpc-methods/getTokenSupply.ts
packages/rpc-core/src/rpc-methods/getTransaction.ts
packages/rpc-core/src/rpc-methods/getVersion.ts

This PR tightens up use of common types such as `TokenAmount` from `rpc-methods/common.ts`

refactor(experimental): tighten up types

---

package.json
packages/addresses/package.json
packages/assertions/package.json
packages/fetch-impl/package.json
packages/keys/package.json
packages/library/package.json
packages/rpc-core/package.json
packages/rpc-transport/package.json
packages/test-config/jest-unit.config.common.ts
packages/test-config/package.json
packages/webcrypto-ed25519-polyfill/package.json
pnpm-lock.yaml

refactor(experimental): force newest version of JSDOM (22+)
This version has, for instance, `AbortSignal#throwIfAborted` whereas the ancient version supported by Jest (JSDOM 20) does not.
```
pnpm turbo test:unit:browser
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1545).
* #1546
* __->__ #1545

refactor(experimental): force newest version of JSDOM (22+)

---

packages/rpc-core/src/rpc-methods/__tests__/get-cluster-nodes-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-genesis-hash-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-identity-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-leader-schedule-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-version-test.ts

test: close file descriptors after reading data in tests
Prevents:
```
(node:3268) Warning: Closing file descriptor 22 on garbage collection
```

test: close file descriptors after reading data in tests

---

.gitignore
scripts/setup-test-validator.sh
scripts/start-shared-test-validator.sh

This PR isolates the install for the test validator we use to run the test suite. 
This way, it won't override any local install you might have already.

refactor(experimental): isolate test validator install

---

packages/rpc-core/src/rpc-methods/__tests__/get-fee-for-message-test.ts
packages/rpc-core/src/rpc-methods/getFeeForMessage.ts
packages/transactions/src/serializers/message.ts
packages/transactions/src/types.ts

This PR adds an opaque type for serialized transaction messages.
You can see there's one type for serialized bytes in binary format (`Uint8Array`) and there's another for `base64`.

refactor(experimental): add opaque type for serialized message

---

packages/addresses/src/__tests__/computed-address-test.ts
packages/addresses/src/computed-address.ts
packages/addresses/src/index.ts

doing this now because its a blocker for me. straightforward reimpl of `createWithSeed`:
```
static async createWithSeed(
fromPublicKey: PublicKey,
seed: string,
programId: PublicKey,
): Promise<PublicKey> {
const buffer = Buffer.concat([
fromPublicKey.toBuffer(),
Buffer.from(seed),
programId.toBuffer(),
]);
const publicKeyBytes = sha256(buffer);
return new PublicKey(publicKeyBytes);
}
```
not ready to merge as-is, pls let me know:
* how to run `lint:fix`, theres no command for it so i have no idea
* if you want this in a new file
* any style complaints, i tried to copy existing code as much as possible

refactor(experimental): implement getBase58EncodedAddressForSeed

---

package.json
packages/addresses/package.json
packages/assertions/package.json
packages/fetch-impl/package.json
packages/instructions/package.json
packages/keys/package.json
packages/library/package.json
packages/rpc-core/package.json
packages/rpc-transport/package.json
packages/transactions/package.json
packages/webcrypto-ed25519-polyfill/package.json
packages/ws-impl/package.json
turbo.json

this creates a toplevel command to run the linters, feel free to chastize me if ive invoked to tools in a scurrilous manner

refactor(experimental): add lint:fix

---

packages/rpc-core/src/rpc-methods/simulateTransaction.ts

The docs specify that `simulateTransaction` returns a payload wrapped within an RPC Response type. The current implementation in our library does not.
https://docs.solana.com/api/http#simulatetransaction
This PR adds that wrapped response.

fix: add rpc response to simulate transaction

---

packages/rpc-transport/package.json
packages/ws-impl/package.json
pnpm-lock.yaml

refactor(experimental): add `ws` and `fetch-impl` peer dependencies to `rpc-transport`
Because these get built _in_ to `rpc-transport`, the `peerDependencies` config needs to be in `rpc-transport` in order to propagate to downstream dependencies.
```ts
require('@solana/web3.js/dist/index.node.cjs'); // No more missing deps
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1580).
* #1586
* #1585
* #1584
* #1583
* #1582
* #1581
* __->__ #1580

refactor(experimental): add `ws` and `fetch-impl` peer dependencies to `rpc-transport`

---

packages/transactions/src/blockhash.ts
packages/transactions/src/fee-payer.ts

This PR introduces some changes to `setTransactionFeePayer` because the original type configuration was always returning a union for a provided base transaction.
With separated overloads, TypeScript can successfully resolve the return type based on the transaction provided.

refactor(experimental): revise `setFeePayer` overloads

---

packages/rpc-core/src/__tests__/lamports-test.ts
packages/rpc-core/src/index.ts
packages/rpc-core/src/lamports.ts
packages/rpc-core/src/rpc-methods/__tests__/request-airdrop-test.ts
packages/rpc-core/src/rpc-methods/__typetests__/get-block-type-test.ts
packages/rpc-core/src/rpc-methods/common.ts
packages/rpc-core/src/rpc-methods/getBalance.ts
packages/rpc-core/src/rpc-methods/getBlock.ts
packages/rpc-core/src/rpc-methods/getBlockCommitment.ts
packages/rpc-core/src/rpc-methods/getInflationReward.ts
packages/rpc-core/src/rpc-methods/getLargestAccounts.ts
packages/rpc-core/src/rpc-methods/getMinimumBalanceForRentExemption.ts
packages/rpc-core/src/rpc-methods/getStakeMinimumDelegation.ts
packages/rpc-core/src/rpc-methods/getSupply.ts
packages/rpc-core/src/rpc-methods/getTransaction.ts
packages/rpc-core/src/rpc-methods/requestAirdrop.ts

This is required because the `requestAirdrop` RPC call requires it as an input.
So as with our other branded inputs we need to be able to write code like:
```ts
const address = 'abc' as Base58EncodedAddress
const lamports = 1_000_000n
assertIsLamports(lamports)
await rpc.requestAirdrop(address, lamports).send()
// or just cast it
await rpc.requestAirdrop(address, 1_000_000n as LamportsUnsafeBeyond2Pow53Minus1).send()
```
Any BigInt that is greater than zero and is less than u64::MAX is valid as a number of lamports and will succeed in `assertIsLamports`.

Export LamportsUnsafe type and add an assertion function

---

packages/rpc-transport/package.json
packages/rpc-transport/src/transports/transport-types.ts
packages/rpc-transport/src/transports/websocket/__tests__/websocket-connection-test.ts
packages/rpc-transport/src/transports/websocket/__tests__/websocket-transport-test.ts
packages/rpc-transport/src/transports/websocket/websocket-transport.ts
packages/ws-impl/package.json
pnpm-lock.yaml

refactor(experimental): bring the HTTP transport and the WebSocket closer together, spiritually
The HTTP transport returns a method that you can call to perform requests and to return responses. My initial version of the WebSocket transport did not fit this interface; instead it returned an object that encapsulated a send method and an iterator of the connection's messages.
Let's bring these spiritually closer together. After this PR you will instead get a method that behaves like a ‘one shot’ request function. When you call it, it creates a WebSocket connectio, sends your payload down it, then returns the connection iterator _and_ the send method.
Now you can more easily write wrapper transports around it that do stuff like:
* Connection persistence
* Auto-pinging
* Payload/response …

refactor(experimental): bring the HTTP transport and the WebSocket closer together, spiritually

---

packages/rpc-transport/src/transports/websocket/__tests__/websocket-transport-test.ts

test: use Jest fake timers properly in WebSocket transport test
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1582).
* #1604
* #1603
* #1598
* #1586
* #1585
* #1584
* #1583
* __->__ #1582

test: use Jest fake timers properly in WebSocket transport test

---

packages/rpc-transport/package.json
packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
packages/rpc-transport/src/index.ts
packages/rpc-transport/src/json-rpc-subscription.ts
packages/rpc-transport/src/json-rpc-types.ts
packages/rpc-transport/src/json-rpc.ts
packages/rpc-transport/src/transports/websocket/__tests__/websocket-transport-test.ts
pnpm-lock.yaml

refactor(experimental): RPC subscriptions
This new subscriptions API uses async iterables to vend subscription notifications, rather than a callback API.
```ts
// Subscribe for account notifications
const accountNotifications = await rpc
.accountNotifications(address, {encoding: 'jsonParsed'})
.subscribe();
// The subscription is now set up. Consume notifications.
try {
for await (const notification of accountNotifications) {
// Loops forever.
console.log(notification);
}
} catch(e) {
// The subscription failed.
// Use this `catch` to decide how/whether to re-establish it.
} finally {
// Whether the subscription failed or was aborted,
// you can run additional cleanup logic here.
}
```
Subscriptions respond to your app's regular abort controllers, so you can unsubscribe them automatically …

refactor(experimental): RPC subscriptions

---

packages/rpc-core/src/__tests__/response-patcher-test.ts
packages/rpc-core/src/index.ts
packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/response-patcher.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/index-test.ts
packages/rpc-core/src/rpc-subscriptions/index.ts
packages/rpc-transport/package.json
packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
packages/rpc-transport/src/index.ts
packages/rpc-transport/src/json-rpc-subscription.ts
packages/rpc-transport/src/json-rpc-types.ts
packages/rpc-transport/src/json-rpc.ts
packages/rpc-transport/src/transports/websocket/__tests__/websocket-transport-test.ts
pnpm-lock.yaml

refactor(experimental): An RPC API creator
These are the types and the builder for the subscriptions API itself – basically the piece that commutes between the name of the notification and the name of the subscribe/unsubscribe methods.
Developers can supply their own concrete implementations of this to do more complex conversions and input/output value transformations. See `packages/library` for one such set of custom functionality.
```
cd packages/rpc-core
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1584).
* #1604
* #1603
* #1598
* #1586
* #1585
* __->__ #1584
* #1583
* #1582

refactor(experimental): An RPC API creator

---

packages/library/src/index.ts
packages/library/src/rpc-websocket-transport.ts
packages/library/src/rpc.ts
packages/rpc-core/src/__tests__/response-patcher-test.ts
packages/rpc-core/src/index.ts
packages/rpc-core/src/response-patcher-allowed-numeric-values.ts
packages/rpc-core/src/response-patcher.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/index-test.ts
packages/rpc-core/src/rpc-subscriptions/index.ts
packages/rpc-transport/package.json
packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
packages/rpc-transport/src/index.ts
packages/rpc-transport/src/json-rpc-subscription.ts
packages/rpc-transport/src/json-rpc-types.ts
packages/rpc-transport/src/json-rpc.ts
packages/rpc-transport/src/transports/websocket/__tests__/websocket-transport-test.ts
pnpm-lock.yaml

refactor(experimental): export the subscriptions API from the main web3.js library
This code lets you create a subscriptions API object.
```ts
const rpcSubscriptions = createSolanaRpcSubscriptions({
transport: createDefaultRpcSubscriptionsTransport({
url: 'https://api.devnet.solana.com',
}),
});
const slotNotifications = await rpcSubscriptions
.slotNotifications()
.subscribe();
for await (const notif of slotNotifications) {
console.log(notif);
}
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1585).
* #1604
* #1603
* #1598
* #1586
* __->__ #1585
* #1584
* #1583
* #1582

refactor(experimental): export the subscriptions API from the main web3.js library

---

packages/library/src/rpc.ts
packages/rpc-core/src/response-patcher.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__typetests__/slot-notifications-type-test.ts
packages/rpc-core/src/rpc-subscriptions/index.ts
packages/rpc-core/src/rpc-subscriptions/slot-notifications.ts

refactor(experimental): The slot notifications API
Use this method to subscribe for a notification every time the slot advances.
```
cd packages/rpc-core
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1586).
* #1604
* #1603
* #1598
* __->__ #1586

refactor(experimental): The slot notifications API

---

packages/library/src/__tests__/rpc-websocket-autopinger-test.ts
packages/library/src/rpc-websocket-autopinger.ts
packages/library/src/rpc.ts
packages/rpc-core/src/response-patcher.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__typetests__/slot-notifications-type-test.ts
packages/rpc-core/src/rpc-subscriptions/index.ts
packages/rpc-core/src/rpc-subscriptions/slot-notifications.ts

refactor(experimental): An autopinging transport
Wrap this around a transport to add auto-ping functionality.
* If a message hasn't been sent or received within `intervalMs` a JSON-RPC call for the `'ping'` method will be issued.
This is to keep connections open when there is no activity, particularly to preserve subscription state for subscriptions that haven't seen a notification in X milliseconds.
```
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1598).
* #1604
* #1603
* __->__ #1598
* #1586

refactor(experimental): An autopinging transport

---

packages/library/src/__tests__/rpc-websocket-autopinger-test.ts
packages/library/src/rpc-websocket-autopinger.ts
packages/library/src/rpc-websocket-transport.ts
packages/library/src/rpc.ts
packages/rpc-core/src/response-patcher.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__typetests__/slot-notifications-type-test.ts
packages/rpc-core/src/rpc-subscriptions/index.ts
packages/rpc-core/src/rpc-subscriptions/slot-notifications.ts

refactor(experimental): install the autopinger by default
Creating a default subscriptions transport now comes with the auto-pinger by default.
Load up the browser bundle and run this test case.
```ts
const rpc = solanaWeb3.createSolanaRpcSubscriptions({transport: solanaWeb3.createDefaultRpcSubscriptionsTransport({url :'wss://api.devnet.solana.com'})});
const notifications = await rpc.accountNotifications('CXPeim1wQMkcTvEHx9QdhgKREYYJD8bnaCCqPRwJ1to1').subscribe();
for await (const notif of notifications) {
console.log(notif);
}
```
Observe pings every 5 seconds.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1603).
* #1604
* __->__ #1603
* #1598
* #1586

refactor(experimental): install the autopinger by default

---

packages/library/src/__tests__/rpc-websocket-connection-sharding-test.ts
packages/library/src/rpc-websocket-connection-sharding.ts
packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
packages/rpc-transport/src/json-rpc-subscription.ts

refactor(experimental): a WebSocket transport that shards payloads amongst a pool of shared socket connections
Prior to this, the base WebSocket transport would open a separate connection for each and every subscription you would make. While this makes the API very easy to reason about, it's obviously inefficient.
In this PR we introduce a meta-transport that you can wrap around a base transport to add the following behaviours:
1. You can specify an optional `getShard` method to produce a shard key from a payload. You could use this to, for instance, shard subscriptions evenly across 20 socket connections, by hashing each payload to a number between 0-19.
2. The first request for a shard will open a connection
3. Subsequent requests for a shard will reuse the open connection
```
cd …
```

refactor(experimental): a WebSocket transport that shards payloads amongst a pool of shared socket connections

---

packages/library/src/__tests__/rpc-websocket-connection-sharding-test.ts
packages/library/src/rpc-websocket-connection-sharding.ts
packages/library/src/rpc-websocket-transport.ts
packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
packages/rpc-transport/src/json-rpc-subscription.ts

refactor(experimental): install the sharding transport by default in web3.js
This meta-transport makes all subscriptions share a single socket connection, unless the user supplies a `getShard` method to produce unique shard keys from payloads.
This in `about:blank`: https://gist.github.com/steveluscher/ea01a212d50c88ee53a712c0cc2c976a
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1613).
* __->__ #1613
* #1612
* #1611

refactor(experimental): install the sharding transport by default in web3.js

---

packages/library/package.json
packages/library/src/rpc-transport.ts
packages/library/src/rpc-websocket-transport.ts
pnpm-lock.yaml

Much nicer to read these linearly rather than inside-out.
CI run

refactor(experimental): refactor the default subscriptions transport with `pipe` to make it more readable

---

packages/library/src/__tests__/rpc-request-deduplication-test.ts
packages/library/src/rpc-request-deduplication.ts

We want to produce subscription dedupe keys, but only for subscription requests. If we get `"method": "ping"` or any other such thing, return an undefined key.

refactor(experimental): create a deduplication key getter specifically for subscriptions

---

packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__typetests__/slot-notifications-type-test.ts
packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
packages/rpc-transport/src/json-rpc-subscription.ts
packages/rpc-transport/src/json-rpc-types.ts

OK listen. We're all adults here. That being said, not having a strategy for cancelling your RPC subscriptions makes everything really complicated and leaves your code prone to leaks.
`AbortSignal` is now a mandatory argument to `subscribe()`.
If you _really_ want to launch your subscriptions without any cancellation strategy you can still do this:
```ts
rpc
.slotNotifications()
.subscribe({ abortSignal: new AbortController().signal });
```
We won't judge you.
```
pnpm turbo test:typecheck
```

refactor(experimental): make abort signals mandatory in subscriptions

---

packages/library/src/__tests__/cached-abortable-iterable-test.ts
packages/library/src/__tests__/rpc-websocket-connection-sharding-test.ts
packages/library/src/cached-abortable-iterable.ts
packages/library/src/rpc-websocket-connection-sharding.ts

It turns out that this logic is _really_ similar to the logic that we're going to need for the subscription coalescing transport, so lets extract it into a base implementation now, and give it all the bells and whistles that it needs to support both use cases.
```
```

refactor(experimental): extract the request cache logic into a base implementation

---

packages/addresses/src/__tests__/coercions-test.ts
packages/addresses/src/__typetests__/coercions-typetests.ts
packages/addresses/src/base58.ts
packages/rpc-core/src/__tests__/coercions-test.ts
packages/rpc-core/src/__typetests__/coercions-typetests.ts
packages/rpc-core/src/lamports.ts
packages/rpc-core/src/stringified-bigint.ts
packages/rpc-core/src/stringified-number.ts
packages/rpc-core/src/transaction-signature.ts
packages/rpc-core/src/unix-timestamp.ts

This PR adds type cercion utility functions such as `lamports()` and `address()` to our API.
Note: I originally felt like these didn't belong in `@solana/rpc-core`, but I followed the pattern of placing these coercion functions in the same file as their assertions. It seems to make sense. Lmk any thoughts on where to place these.
Closes #1600

refactor(experimental): add coercion utility functions

---

packages/codecs-data-structures/src/scalar-enum.ts

Currently, running `pnpm test:typecheck` on the `codecs-data-structures` package fails, this PR fixes this by transforming `& object` to `& NonNullable<unknown>` (more famously known as `& {}`) to the `ScalarEnum` type. Umi previously used `& {}` and, when migrating the library to web3.js, I tried to make that type stronger but it seems only `& {}` can make this work.

refactor(experimental): fix codecs-data-structures typecheck

---

packages/rpc-core/src/rpc-methods/getTransaction.ts

The method for `getTransaction` should take a base58-encoded transaction signature string as a parameter, not a base58-encoded address, for explicit clarity.
See: https://docs.solana.com/api/http#gettransaction

refactor(experimental): change `getTransaction` parameter to `TransactionSignature`

---

packages/rpc-transport/src/transports/websocket/__tests__/websocket-connection-test.ts
packages/rpc-transport/src/transports/websocket/websocket-connection.ts

Previous to this PR, if you aborted a socket connection, it would keep publishing messages into its iterator until the socket disconnected.
Now it will tear down the iterators and return from them immediately upon you calling `abort()`
```
cd packages/rpc-transport
pnpm turbo test:unit:browser
pnpm turbo test:unit:node
```

refactor(experimental): drop messages the moment a socket connection is aborted

---

packages/library/src/__tests__/rpc-request-deduplication-test.ts
packages/library/src/__tests__/rpc-subscription-coalescer-test.ts
packages/library/src/rpc-request-deduplication.ts
packages/library/src/rpc-subscription-coalescer.ts
packages/rpc-transport/src/transports/websocket/__tests__/websocket-connection-test.ts
packages/rpc-transport/src/transports/websocket/websocket-connection.ts

This is a transport that, given two identical subscription requests, will issue the subscription request the first time only, and return a the cached iterator for that request each subsequent time, finally tearing the subscription down when the last consumer aborts.
This means that if you `slotSubscribe` from 10 places in your app, those will only ever produce one subscription over the RPC and will fan the notifications out to the callers.
```
```

refactor(experimental): a transport that coalesces multiple subscriptions behind a single subscription

---

packages/library/src/__tests__/rpc-request-deduplication-test.ts
packages/library/src/__tests__/rpc-subscription-coalescer-test.ts
packages/library/src/rpc-request-deduplication.ts
packages/library/src/rpc-subscription-coalescer.ts
packages/library/src/rpc.ts
packages/rpc-transport/src/transports/websocket/__tests__/websocket-connection-test.ts
packages/rpc-transport/src/transports/websocket/websocket-connection.ts

Let's make the library coalesce identical subscriptions by default, just like the legacy one.
This test case: https://gist.github.com/steveluscher/ff83dd03c26f98c2359718054e2e58e3

refactor(experimental): install the subscription coalescing transport by default

---

packages/transactions/src/__typetests__/transactions-typetests.ts
packages/transactions/src/durable-nonce.ts
packages/transactions/src/fee-payer.ts

Adds typetests for the `@solana/transactions` library.
Closes #1597

refactor(experimental): transaction type tests

---

.github/workflows/cicd.yml
.github/workflows/pull-requests.yml

This PR fixes CI caching, as detailed in [this comment](https://github.com/solana-labs/solana-web3.js/pull/1551#issuecomment-1745768306)

fix: ci caching

---

packages/transactions/src/__typetests__/transaction-typetests.ts
packages/transactions/src/durable-nonce.ts
packages/transactions/src/fee-payer.ts

This PR is a duplicate of the reverted #1618 
Needed to revert and check things out again.
---
This PR adds type tests to `@solana/transactions`. I also made two changes to type signatures within our methods, as documented in the linked PR at [this comment](https://github.com/solana-labs/solana-web3.js/pull/1618#pullrequestreview-1652851951).
---
Update: WOW this was stupid. I guess I didn't have the "multiple signers" change in my branch, so it was barfing on them not being in a list 😅.
Good to go

refactor(experimental): add transaction type tests

---

packages/library/src/__tests__/transaction-confirmation-strategy-blockheight-test.ts
packages/library/src/index.ts
packages/library/src/transaction-confirmation-strategy-blockheight.ts

Transactions with a lifetime as long as their blockhash is valid can be thought to expire after that blockhash becomes invalid. This strategy watches the progression of slots and throws an error after exceeding the height for which the blockhash is valid.
```
```

refactor(experimental): a strategy for expiring a transaction confirmation when the block height is exceeded

---

packages/library/src/__tests__/transaction-confirmation-strategy-nonce-test.ts
packages/library/src/index.ts
packages/library/src/transaction-confirmation-strategy-nonce.ts

Transactions with a lifetime tied to a nonce can be thought to expire after that nonce is ‘advanced’. This strategy watches a nonce's account and throws an error if the nonce changes from the expected value (ie. it was advanced in a different transaction).
```
```

refactor(experimental): a strategy for expiring a transaction confirmation when a nonce advances

---

packages/library/src/__tests__/transaction-confirmation-strategy-signature-test.ts
packages/library/src/index.ts
packages/library/src/transaction-confirmation-strategy-signature.ts

A transaction can be thought of as ‘confirmed’ when its signature achieves the level of commitment desired. This strategy watches the status of a given signature and returns when the signature's commitment achieves at least the level configured by the confirmer.
```
```

refactor(experimental): a strategy for confirming a transaction when the signature commits

---

packages/library/package.json
packages/library/src/__tests__/transaction-confirmation-test.ts
packages/library/src/index.ts
packages/library/src/transaction-confirmation.ts
packages/library/tsconfig.json
pnpm-lock.yaml

There are some transaction confirmation strategies on which there is some disagreement, like whether to poll the server for a signature's status or to subscribe for changes to it.
In this PR we commit the _uncontroversial_ parts of the strategy; that you will have to wait for the signature to be confirmed (somehow) and fail if the block height exceeds the `lastValidBlockHeight`.
These functions leave the implementation of _how_ to do that up to the caller. This will enable us to rebuild the default strategy on top of this, but will also allow people to supply their _own_ strategies, as appropriate for their use case.
```
```

refactor(experimental): a low-level series of helpers to confirm transactions

---

packages/library/README.md

In the code example within `packages/library/README.md`:
1. Corrected an unclosed string literal that could cause confusion for readers or implementation issues.
2. Added the `async` keyword to the function to align with asynchronous operations.

fix: unclosed string literal in code example, async keyword for the function

---

packages/rpc-graphql/package.json
pnpm-lock.yaml

This PR should solve the tree-shakability problem. I've made `graphql` a direct dependency for `@solana/rpc-graphql`, as we've done with other external libraries required by a package - like the usage of `@metaplex-foundation/umi-serializers` in `@solana/addresses`.

refactor(experimental): make graphql a dependency

---

packages/rpc-core/src/rpc-methods/__tests__/get-blocks-with-limit-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-slot-leader-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-vote-accounts.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/account-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/program-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/signature-notifications-test.ts

This PR fixes a few missed path updates in the `@solana/rpc-core` tests where the tests are trying to import the `Commitment` type, which has been moved to its own file `commitment.ts`.
Might have been missed in #1698.

refactor(experimental): update paths to commitment type

---

packages/rpc-core/src/rpc-methods/getBlockProduction.ts
packages/rpc-core/src/rpc-methods/getVoteAccounts.ts

This PR replaces any `u64` types with `Slot` for fields that represent a slot.
Closes #1629

refactor(experimental): use slot type for all slots

---

packages/addresses/README.md
packages/addresses/src/__tests__/address-test.ts
packages/addresses/src/__tests__/coercions-test.ts
packages/addresses/src/__tests__/computed-address-test.ts
packages/addresses/src/__typetests__/coercions-typetests.ts
packages/addresses/src/address.ts
packages/addresses/src/computed-address.ts
packages/addresses/src/index.ts
packages/addresses/src/public-key.ts
packages/library/README.md
packages/transactions/src/__tests__/accounts-test.ts
packages/transactions/src/__tests__/compile-address-table-lookups-test.ts
packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/accounts.ts
packages/transactions/src/compile-address-table-lookups.ts
packages/transactions/src/serializers/address-table-lookup.ts
packages/transactions/src/serializers/message.ts

- Rename `isBase58EncodedAddress()` to `isAddress()`
- Rename `assertIsBase58EncodedAddress()` to `assertIsAddress()`
- Rename `getBase58EncodedAddressCodec()` to `getAddressCodec()`
- Rename `getBase58EncodedAddressComparator()` to `getAddressComparator()`
- Rename `base58.ts` and `base58-test.ts` files to `address.ts` and `address-test.ts`

refactor(experimental): rename Base58EncodedAddress helpers

---

packages/transactions/src/index.ts
packages/transactions/src/serializers/index.ts

This PR exports the `getTransactionEncoder` function from `@solana/transactions`
Currently only this encoder is exported, others can be added if required

refactor(experimental): export the transaction encoder

---

packages/rpc-core/src/rpc-methods/__tests__/get-cluster-nodes-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-program-accounts-test.ts
scripts/get-latest-validator-release-version.sh
scripts/setup-test-validator.sh

This PR makes a temporary fix for CI to enable using the `1.17.x` test validator, where the following change has been implemented: https://github.com/solana-labs/solana/pull/33531.
When `1.17` goes live on mainnet-beta, we can revert the changes to the test scripts, such as `scripts/setup-test-validator.sh`.
An issue has been created to remind us of this revert.

refactor(experimental): update test validator with new vote account state

---

packages/options/src/index.ts

My bad, I forgot to export the option codecs when writing the `options` package. This is needed for client generation.

refactor(experimental): export option codecs

---

packages/library-legacy/test/connection.test.ts

This was broken by the change to a 1.17 validator, which changes this error message

refactor: fix throw message in stake activation test

---

packages/rpc-graphql/src/schema/scalars.ts

This PR introduces a `bigint` GraphQL scalar, which allows for parsing and interpreting `bigint` values from the RPC. 
Note: I have decided to handle these values as strings on the client API, with a suffix `n` character.

refactor(experimental): a bigint scalar for RPC GraphQL

---

packages/rpc-graphql/src/schema/picks.ts

These picks are designed to reduce some of the verbosity involved with initializing GraphQL JS objects and defining their fields and types. The result is GraphQL JS object definitions that look more like TypeScript type definitions.

refactor(experimental): picks for creating GraphQL JS types

---

packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/schema/account/index.ts
packages/rpc-graphql/src/schema/account/query.ts

A resolver to hit the Solana RPC for an `AccountInfo` from a GraphQL query.

refactor(experimental): an account resolver

---

packages/rpc-graphql/package.json
packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/rpc.ts
packages/rpc-graphql/src/schema/account/index.ts
packages/rpc-graphql/src/schema/account/query.ts
packages/rpc-graphql/src/schema/account/types.ts
packages/rpc-graphql/src/schema/inputs.ts

The `Account` query and schema for querying on-chain Solana accounts and their potentially parsed data.

refactor(experimental): an account GraphQL query

---

packages/addresses/package.json
packages/assertions/package.json
packages/codecs-core/package.json
packages/codecs-data-structures/package.json
packages/codecs-numbers/package.json
packages/codecs-strings/package.json
packages/compat/package.json
packages/fetch-impl/package.json
packages/functional/package.json
packages/instructions/package.json
packages/keys/package.json
packages/library/package.json
packages/options/package.json
packages/rpc-core/package.json
packages/rpc-graphql/package.json
packages/rpc-transport/package.json
packages/text-encoding-impl/package.json
packages/transactions/package.json
packages/webcrypto-ed25519-polyfill/package.json
packages/ws-impl/package.json

I keep getting a mismatch between an editor setting and prettier styling for package.json
We run prettier on package.json so our `style:fix` should also fix it
Note that we don't run eslint on package.json and it makes a huge mess of it and complains about ordering of objects, so I've deliberately only added it to the prettier calls

chore: make style:fix also fix package.json

---

packages/rpc-graphql/src/rpc.ts
packages/rpc-graphql/src/schema/account/query.ts
packages/rpc-graphql/src/schema/account/types.ts
packages/rpc-graphql/src/schema/block/query.ts
packages/rpc-graphql/src/schema/block/types.ts
packages/rpc-graphql/src/schema/inputs.ts
packages/rpc-graphql/src/schema/picks.ts
packages/rpc-graphql/src/schema/program-accounts/query.ts
packages/rpc-graphql/src/schema/program-accounts/types.ts
packages/rpc-graphql/src/schema/scalars.ts
packages/rpc-graphql/src/schema/transaction/query.ts
packages/rpc-graphql/src/schema/transaction/types.ts

This PR makes `@solana/rpc-graphql` tree-shakable, which is previously was not.
Basically, there appears to be _a lot_ of changes, but I've just converted static constants to arrow functions. Nothing else has been changed.

refactor(experimental): make rpc-graphql tree-shakable

---

packages/compat/src/__tests__/address.ts
packages/compat/src/__tests__/keypair.ts
packages/compat/src/__typetests__/address.ts
packages/compat/src/__typetests__/keypair.ts
packages/compat/src/address.ts
packages/compat/src/keypair.ts

This PR adds `PublicKey` and `Keypair` compatibility helpers for the new API.

refactor(experimental): add keys to compat

---

packages/rpc-core/src/rpc-subscriptions/slots-updates-notifications.ts

This PR updates the `slotsUpdatesNotifications` subscription method with a few optional fields that weren't present in the docs. See https://github.com/solana-labs/solana/pull/33460

refactor(experimental): update slotsUpdates subscription optional fields

---

packages/addresses/package.json
packages/addresses/src/__tests__/address-test.ts
packages/addresses/src/address.ts
packages/addresses/src/program-derived-address.ts
packages/addresses/src/public-key.ts
packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/serializers/address-table-lookup.ts
packages/transactions/src/serializers/message.ts
pnpm-lock.yaml

- Use strings-codecs package
- Memoise created encoder/decoder
This should serve as a pattern for refactoring the other serializers related to transactions

refactor(experimental): refactor Address codec

---

packages/transactions/package.json
packages/transactions/src/serializers/__tests__/transaction-version-test.ts
packages/transactions/src/serializers/message.ts
packages/transactions/src/serializers/transaction-version.ts
pnpm-lock.yaml

This PR refactors the `TransactionVersion` serializer to use the codecs-core Encoder/Decoder/Codec data structures
The only behaviour change is that we no longer have the unimplemented runtime errors. Calling `encode` on the `Decoder`, or vice versa, is now a type error

refactor(experimental): use codecs-core for transaction version codec

---

packages/compat/src/__tests__/address-test.ts
packages/compat/src/__tests__/keypair-test.ts

- Added `-test` suffix to files
- Renamed describe block to the functions under test

refactor(experimental): massage test names in `@solana/compat`

---

packages/library/src/__tests__/transaction-confirmation-strategy-signature-test.ts
packages/library/src/__tests__/transaction-confirmation-test.ts
packages/library/src/index.ts
packages/library/src/transaction-confirmation-strategy-recent-signature.ts
packages/library/src/transaction-confirmation.ts

A common pitfall for folks is trying to use `confirmTransaction()` to ‘confirm’ really old transactions that have fallen out of the status cache. You should not do this; you should use `getSignatureStatuses([...], {searchTransactionHistory: true})` for that.
In this PR, we rename _all_ of this stuff using the word ‘recent’ to drive that home.

refactor(experimental): rename signature confirmation strategy using the word ‘recent’

---

packages/codecs-data-structures/src/scalar-enum.ts

This was an error on my side. The encoder function should ask for a `NumberEncoder` and the decoder function for a `NumberDecoder`. They currently both ask for a `NumberCodec` which is too much.

fix(experimental): fix scalar enum codec options

---

packages/library/src/__tests__/transaction-confirmation-strategy-timeout-test.ts
packages/library/src/transaction-confirmation-strategy-timeout.ts

This won't be encouraged or exported, but here's a timeout-based confirmation strategy for transactions come with signatures but not last-valid-block-heights (ahem… `requestAirdrop`)

refactor(experimental): a timeout-based transaction confirmation strategy

---

packages/library/src/__tests__/airdrop-confirmer-test.ts
packages/library/src/__tests__/airdrop-test.ts
packages/library/src/airdrop-confirmer.ts
packages/library/src/airdrop.ts
packages/library/src/index.ts

Folks often find themselves requesting an airdrop but continuing with the rest of their program before confirming that the drop landed. This leads to a lot of confusing ‘insufficient funds’ type errors.
In this PR we introduce a higher-level helper that does airdropping and confirmation in one.
```ts
const {
createDefaultRpcSubscriptionsTransport,
createDefaultRpcTransport,
createSolanaRpc,
createSolanaRpcSubscriptions,
generateKeyPair,
getAddressFromPublicKey,
requestAndConfirmAirdrop,
} = require("./dist/index.node.cjs");
const { lamports } = require("@solana/rpc-core");
const rpc = createSolanaRpc({
transport: createDefaultRpcTransport({
url: "https://api.devnet.solana.com",
}),
});
const rpcSubscriptions = createSolanaRpcSubscriptions({
transport: …
```

refactor(experimental): an airdrop request helper

---

packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/signatures.ts

This is what happens when you suppress TypeScript, kids.

refactor(experimental): fix `getSignatureFromTransaction`

---

packages/compat/src/__tests__/transaction-test.ts
packages/compat/src/__typetests__/transaction-typetests.ts
packages/compat/src/transaction.ts
packages/transactions/src/durable-nonce.ts

This PR adds a new `@solana/compat` function to convert a versioned transaction that uses a durable nonce lifetime
This is similar to the blockhash version, with a few differences:
- It does not take `lastValidBlockHeight` since that is only used for blockhash lifetimes
- It errors if the input transaction does not have an advance durable nonce instruction as its first instruction
- It returns an `IDurableNonceTransaction`
Note that the instruction check is done on the modern instruction. I've just used the `isAdvanceNonceAccountInstruction` function that we already have
I opted for a separate function because I don't think there's an easy way to differentiate these types in the legacy library, since it puts the `nonce` value in the `blockhash` field
Callers will likely often already know …

refactor(experimental): add fromVersionedTransactionWithDurableNonce

---

packages/transactions/src/serializers/__tests__/instruction-test.ts
packages/transactions/src/serializers/instruction.ts
packages/transactions/src/serializers/message.ts

Note that the implementation here is slightly different to what I've done before, but I think better:
- The Encoder/Decoder are memoized at the top level, instead of memoizing constituent parts (this was dumb)
- I used `combineCodec` instead of manually writing the codec (this was also dumb)

refactor(experimental): use new codecs to de/serialize Instructions

---

packages/library/src/__tests__/send-transaction-test.ts
packages/library/src/index.ts
packages/library/src/send-transaction.ts

This is a high level helper for sending and confirming transactions so that you don't have to think about:
- serializing the transaction to wire format
- confirming it
- how to set the simulation commitment so that you don't immediately faceplant
Start a local validator (eg. I used `./scripts/start-shared-test-validator.sh`), and then make a memo program transaction.
```ts
const {
appendTransactionInstruction,
createDefaultRpcSubscriptionsTransport,
createDefaultRpcTransport,
createDefaultTransactionSender,
createSolanaRpc,
createSolanaRpcSubscriptions,
createTransaction,
generateKeyPair,
getAddressFromPublicKey,
getSignatureFromTransaction,
requestAndConfirmAirdrop,
setTransactionFeePayer,
setTransactionLifetimeUsingBlockhash,
signTransaction,
} = require("./dist/index.node.cjs");
const …
```

refactor(experimental): a send-and-confirm transaction helper

---

packages/rpc-transport/src/json-rpc-types.ts

_tl;dr, @Dimava is a saint ([link](https://github.com/sindresorhus/type-fest/issues/585#issuecomment-1528768370))_.
Breaking up the mega-overload helper into separate helpers for each level of overload fixed #1682.
```
~/src/solana-web3.js-git$ cd pacakges/library/
~/src/solana-web3.js-git/packages/library$ pnpm tsc -p ./tsconfig.json --noEmit --generateTrace tracing_output_folder
```
Holy shit.
https://github.com/solana-labs/solana-web3.js/assets/13243/022b05b4-341e-4c35-960d-069d7084f0e5

refactor(experimental): alias JSON-RPC types for performance

---

packages/library/src/__tests__/transaction-confirmation-strategy-racer-test.ts
packages/library/src/transaction-confirmation-strategy-racer.ts

It's conceivable that, despite the fact that the confirmation helpers use subscriptions internally, you might want to be lazy and not manage cancellation. This is so because transaction confirmation is short-lived-ish.
To save you a few keystrokes, and at your own peril, we make `abortSignal` optional in the method signature of `confirmRecentTransaction` and `confirmDurableNonceTransaction`.
```
cd packages/library/
```

refactor(experimental): make `abortSignal` optional in the confirmation helpers

---

packages/library/src/__tests__/transaction-confirmation-strategy-racer-test.ts
packages/library/src/airdrop.ts
packages/library/src/transaction-confirmation-strategy-racer.ts

It's probably fadingly unlikely that the kind of person who requests an airdrop is interested in cancelling it mid-flight.
To save you a few keystrokes, and at your own peril, we make `abortSignal` optional in the method signature of `requestAndConfirmAirdrop`.
```
cd packages/library/
```

refactor(experimental): make `abortSignal` optional in the airdrop helper

---

packages/webcrypto-ed25519-polyfill/src/__tests__/index-test.ts
packages/webcrypto-ed25519-polyfill/src/__tests__/secrets-test.ts
packages/webcrypto-ed25519-polyfill/src/index.ts
packages/webcrypto-ed25519-polyfill/src/secrets.ts

This PR adds the `importKey` function to the webcrypto polyfill
It supersedes #1681, thanks to @ronanyeah for the contribution!
- when we import public key bytes we store them as-is. Since our existing secrets store stores secrets (from which we can derive a public key), we use a new store for these public key bytes which don't need to be converted to be used as a public key
- when we import private key bytes, we validate the PKCS8 header (we just compare to the known precise expected header), and strip it. The remaining private key bytes are stored in the secrets store

refactor(experimental): add Ed25519 importKey polyfill

---

packages/compat/src/index.ts

This PR adds proper exports to `@solana/compat` to expose the address and keypair compatibility functions (whoopsie!).

refactor(experimental): export address and keypair compats

---

packages/compat/src/transaction.ts
packages/transactions/package.json
packages/transactions/src/__tests__/decompile-transaction-test.ts
packages/transactions/src/decompile-transaction.ts
pnpm-lock.yaml

This PR adds a first version of the `decompileTransaction` function.
This takes as input a `CompiledTransaction`, ie the result of calling `getCompiledTransaction`. It returns a `CompilableTransaction` which may have signatures, ie the input to `getCompiledTransaction`.
This is quite similar to the compat function that converts old web3js to new. Note though that I've implemented this as a single function which itself determines whether we're using a blockhash or durable lifetime constraint. This means that we always take an optional `lastValidBlockHeight` parameter, which is ignored if using a durable nonce, and defaulted to U64 max if using a blockhash.
The reason for this difference is that given a compiled instruction you can't know which lifetime constraint is used without inspecting …

refactor(experimental): add support for decompiling a compiled transaction

---

packages/transactions/src/__tests__/durable-nonce-test.ts
packages/transactions/src/durable-nonce.ts

This PR updates the logic to determine whether a given instruction is a durable nonce transaction. Specifically, the nonce authority address can now be writeable. This is the case if the nonce authority is also the fee payer, for example in a transaction created with the CLI: https://explorer.solana.com/tx/2FZPN5ZJqi5LSMe18auxx59G1VZAP71p8KLCDvyH1WAFgqEXfag6xmC8KnzXQW3KSdbmEyWp8rdd1VnmxMsTrUdG?cluster=devnet 
I don't think any change is required for other accounts
- The nonce address is unlikely to need to be a signer, since it is already initialized 
- I think sysvar addresses are always readonly

refactor(experimental): allow the nonce authority account to be writable

---

packages/transactions/src/__tests__/decompile-transaction-test.ts

This PR adds unit tests for decompiling a durable nonce transaction

refactor(experimental): add tests for decompiling durable nonce transaction

---

packages/transactions/src/serializers/__tests__/transaction-test.ts
packages/transactions/src/serializers/transaction.ts

This PR adds `getTransactionDecoder`, which deserializes a compiled transaction and then decompiles it
It also adds `getTransactionCodec`, combining the existing encoder and this new decoder
This gives us the ability to deserialize from transaction bytes to a new transaction

refactor(experimental): add transaction decoder + codec

---

packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/__typetests__/transaction-typetests.ts
packages/transactions/src/signatures.ts

- asserts that there is a signature for each expected signer
- only verifies the presence of signatures, does not verify the signatures are valid
Part of #1773, but won't close yet in case we want to add a separate function to validate signatures too

refactor(experimental): add function to check if a transaction is fully signed

---

.github/workflows/cicd.yml

This should fix the CI/CD workflow
version-from-git is broken on Node20
fix we're waiting on: https://github.com/compulim/version-from-git/pull/17
Issue to get this moved back to Node 20: #1786

fix: temporarily lock to Node 18.x for CI/CD workflow

---

packages/transactions/src/signatures.ts

This greatly improves performance when signing a transaction with multiple keypairs
Fixes #1788

refactor(experimental): optimise signTransaction to only encode the message once

---

packages/library/package.json
packages/library/src/__tests__/transaction-confirmation-strategy-nonce-test.ts
packages/library/src/transaction-confirmation-strategy-nonce.ts
pnpm-lock.yaml

- straightforward replacement with base58/base64 from codecs-strings

refactor(experimental): replace umi-serializers with codecs in library package

---

packages/rpc-core/package.json
packages/rpc-core/src/rpc-methods/__tests__/get-fee-for-message-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-identity-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-largest-accounts-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-leader-schedule-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-program-accounts-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-slot-leader-test.ts
packages/rpc-core/src/rpc-methods/__tests__/get-slot-leaders-test.ts
packages/rpc-core/src/rpc-methods/__tests__/request-airdrop-test.ts
packages/rpc-core/src/rpc-methods/__tests__/send-transaction-test.ts
packages/rpc-core/src/rpc-methods/__tests__/simulate-transaction-test.ts
pnpm-lock.yaml

- These were only used in tests, but umi-serializers was a dependency
- I've also loosened some test values that seem to vary by validator
version. This may be the cause of the flaky rpc-core tests in CI

refactor(experimental): use codecs for rpc-core package

---

packages/transactions/package.json
packages/transactions/src/__tests__/blockhash-test.ts
packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/blockhash.ts
packages/transactions/src/signatures.ts
pnpm-lock.yaml

- use memoised base58 encoder for blockhash/signatures assertions
After this, no more Umi dependencies! 🎉

refactor(experimental): use codecs for transactions package

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/schema/account/types.ts

This PR enables returning default data - including the account's address - when it's not found by the RPC call `getAccountInfo`. This allows chained/nested queries to be more reliable if the RPC encounters an account that does not exist.

refactor(experimental): enhance null account info handling for GraphQL

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/schema/account/query.ts
packages/rpc-graphql/src/schema/account/types.ts

This PR adds an interceptor on the actual query passed into the resolver. The interceptor is designed to read which fields have been requested for an account, and determine the necessary action.
If _only_ the address has been requested, it's already in the query - either inside a provided query variable or in a previously obtained return payload. So, there's no need to make an RPC call to `getAccountInfo` if the user only needs the address.
If any other fields are requested, with or without `address`, the resolver will go to the RPC.

refactor(experimental): modify account resolver to not send a request for only an address

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/schema/account/types.ts

This PR switches the simple string base58-encoded addresses that are part of the default `jsonParsed` response for account types to the GraphQL `Account` interface type, allowing these fields to be fully queryable with nested queries.
Here's an example:
```typescript
const source = `
query myQuery($address: String!) {
account(address: $address) {
... on MintAccount {
address
data {
parsed {
info {
mintAuthority {
address
lamports
}
}
}
}
}
}
}
`;
const variableValues = {
address: 'AyGCwnwxQMCqaU4ixReHt8h5W4dwmxU7eM3BEQBdWVca',
};
const result = await rpcGraphQL.query(source, variableValues);
expect(result).toMatchObject({
data: {
account: {
address: 'AyGCwnwxQMCqaU4ixReHt8h5W4dwmxU7eM3BEQBdWVca',
data: {
parsed: {
info: {
mintAuthority: {
address: expect.any(String),
lamports: …
```

refactor(experimental): add support for nested accounts in all account types

---

packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/schema/inputs.ts

This PR adds a test and updates an input type's name to ensure filters for `getProgramAccounts` are supported by RPC-GraphQL.

refactor(experimental): reinforce filters for program accounts queries

---

packages/rpc-graphql/src/schema/transaction/types.ts

This PR switches the simple string base58-encoded addresses that are part of the default `jsonParsed` response for account types to the GraphQL Account interface type, allowing these fields to be fully queryable with nested queries.
Here's an example:
```typescript
const source = `
query myQuery($signature: String!, $commitment: Commitment) {
transaction(signature: $signature, commitment: $commitment) {
... on TransactionJsonParsed {
transaction {
message {
... on TransactionMessageParsed {
instructions {
... on SplTokenTransferInstruction {
parsed {
info {
amount
authority {
address
lamports
}
destination {
... on TokenAccount {
data {
parsed {
info {
address
mint {
... on MintAccount {
data {
parsed {
info {
address
decimals
}
}
}
}
}
owner {
address
lamports
}
}
}
}
}
}
source {
... on …
```

refactor(experimental): add support for nested accounts in all transaction types

---

packages/rpc-graphql/README.md

This PR delivers the official documentation for `@solana/rpc-graphql`!
With this documentation, developers are free to mess around with the experimental library and sniff out bugs. This should give them adequate information to really stress-test this library and try to perform complex queries on Solana.

refactor(experimental): add official RPC-GraphQL documentation

---

packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/compilable-transaction.ts
packages/transactions/src/compile-transaction.ts
packages/transactions/src/decompile-transaction.ts
packages/transactions/src/index.ts
packages/transactions/src/message.ts
packages/transactions/src/serializers/transaction.ts
packages/transactions/src/signatures.ts

This PR exports the `CompilableTransaction` and `CompiledTransaction` types as they define important Transaction states and will be required by the `signers` package.

refactor(experimental): export CompilableTransaction and CompiledTransaction types

---

packages/rpc-core/src/rpc-methods/getTokenAccountsByOwner.ts

This commit renames the parameter 'program' to 'owner' across all instances within the GetTokenAccountsByOwnerApi interface. This modification corrects the name, making the API more intuitive and consistent with the expectations of the method.
Fixes #1808. 
IMO, since every token account is > 128 bytes, I'd suggest removing the final overload of `GetTokenAccountsByOwnerApi` the one with no encoding. If the user does not pass an encoding value, the method returns an error. Happy to make that tweak, but I wanted to confirm it here first.

fix(experimental): parameter names in GetTokenAccountsByOwnerApi

---

packages/library-legacy/src/connection.ts

As reported in https://solana.stackexchange.com/questions/7981/structerror-at-path-meta-expected-an-object-but-received-null-gettransac, when calling `getTransaction` directly, the deserialization of the response fails because there's no `meta` field, and `GetTransactionRpcResult` requires it.
Note that `GetParsedTransactionRpcResult` correctly declares the `meta` field as `nullable`, and the docs say that meta may be null https://docs.solana.com/api/http#gettransaction
Make `GetTransactionRpcResult` consistent with its parsed cousin, and declare the meta as `nullable`

fix(legacy): declare GetTransactionRpcResult's `meta` as nullable

---

packages/instructions/src/instruction.ts
packages/transactions/src/compilable-transaction.ts
packages/transactions/src/types.ts

This PR makes add the following type parameters:
- `TAccounts` on `IInstruction` so we can refine the account metas type without asserting that the accounts are provided (via the existing `IInstructionWithAccounts`). This is then being used to re-define the `LegacyTransaction` such that it excludes `IAccountLookupMeta` types.
- `TInstruction` on transaction types (i.e. `BaseTransaction`, `LegacyTransaction`, `V0Transaction` and `CompilableTransaction`). This enables functions to refine the instruction type that they support within a transaction. That way, we can create a `ILegacyInstruction` type for the `LegacyTransaction`.
- `TVersion` on transaction types to make it easier to define the `LegacyTransaction` and `V0Transaction` types.
On top of the nice refactoring we get, this PR allows …

refactor(experimental): parameterize account metas for instructions and instructions for transactions

---

packages/rpc-core/src/rpc-methods/getSignaturesForAddress.ts

`getSignaturesForAddress` does not return objects wrapped in RPC Response contexts.
https://docs.solana.com/api/http#getsignaturesforaddress
Remove the wrapper!

refactor(experimental): remove rpc response from `getSignaturesForAddress`

---

packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/__typetests__/transaction-typetests.ts
packages/transactions/src/signatures.ts

I feel like in the common case of calling `signTransaction` you will want to end up with a fully signed (ie. landable) transaction, and that partially signing a transaction is more of the edge case.
```ts
// Instead of this:
const signedTx: ITransactionWithSignatures = await signTransaction(...);
assertIsFullySignedTransaction(signedTx);
// Just do this:
const signedTx: IFullySignedTransaction = await signTransaction(...); // Throws if it doesn't end up fully signed.
```
```
```

refactor(experimental): make `signTransaction` assert the transaction is fully signed; add `partiallySignTransaction`

---

packages/rpc-graphql/README.md
packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/resolvers/program-accounts.ts
packages/rpc-graphql/src/schema/account/types.ts

This PR introduces a revised version of the account schema for `jsonParsed`
account data.
Typically we see JSON-parsed account data like this:
```javascript
{
data: {
parsed: {
info: {
/* data */
},
type: 'mint',
},
program: 'Tokenkegxxxxxxxx',
space: 82n,
},
}
```
However, when it comes to GraphQL, I've made an opinionated decision to move
away from the JSON-parsed format returned by the RPC, and instead opt for this
"optimized" format:
```javascript
{
data: {
/* data */
},
meta: {
program: 'Tokenkegxxxxxxxx',
space: 82n,
type: 'mint',
},
}
```
Since we know we'll always get `program`, `space`, and `type`, we can extract
those to be "parsed metadata" about an account and introduce the `meta` field.

refactor(experimental): revise accounts schema

---

packages/rpc-graphql/README.md
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/resolvers/block.ts
packages/rpc-graphql/src/resolvers/transaction.ts
packages/rpc-graphql/src/schema/block/query.ts
packages/rpc-graphql/src/schema/inputs.ts
packages/rpc-graphql/src/schema/transaction/query.ts
packages/rpc-graphql/src/schema/transaction/types.ts

This PR introduces a revised transaction schema for GraphQL.
⚠️ ‼️ Note: This is only a _light_ revision to the transaction schema. It will be _massively_ easier to review schema changes once the next PR in this stack is merged, and the types are written in pure GraphQL lang.

refactor(experimental): revise transactions schema (Part 1)

---

packages/rpc-graphql/package.json
packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/loaders/account.ts
packages/rpc-graphql/src/loaders/common/resolve-info.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/index.ts
pnpm-lock.yaml

This PR takes @steveluscher's lay-up from #1827 and kicks off a stack for
replacing the entire custom GraphQL cache with `DataLoader`.
This particular PR migrates the account loader.

refactor(experimental-graphql): replace accounts cache with `DataLoader`

---

packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/loaders/block.ts
packages/rpc-graphql/src/resolvers/block.ts
packages/rpc-graphql/src/schema/index.ts

This PR replaces the block loader's use of the custom cache with a `DataLoader`
setup.

refactor(experimental-graphql): replace block cache with `DataLoader`

---

packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/loaders/transaction.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/resolvers/block.ts
packages/rpc-graphql/src/schema/index.ts

This PR replaces the transaction loader's use of the custom cache in favor of a
`DataLoader` setup.

refactor(experimental-graphql): replace transaction cache with `DataLoader`

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts

This PR enables VS Code's GraphQL syntax highlighting in all of the tests!
Pretty!

refactor(experimental-graphql): enable GraphQL syntax highlighting

---

packages/transactions/src/wire-transaction.ts

Refactor the implementation of `getBase64EncodedWireTransaction` such that it uses the `getBase64Decoder` instead of re-implementing its logic.

refactor(experimental): use getBase64Decoder in getBase64EncodedWireTransaction

---

packages/library-legacy-sham/src/index.ts

refactor(experimental): add constants to web3.js sham

---

packages/library-legacy-sham/package.json
packages/library-legacy-sham/src/__tests__/key-pair-test.ts
packages/library-legacy-sham/src/__typetests__/key-pair-typetest.ts
packages/library-legacy-sham/src/index.ts
packages/library-legacy-sham/src/key-pair.ts
packages/test-config/jest-unit.config.common.ts
pnpm-lock.yaml

Imagine that you depend on a module that itself depends on the legacy `@solana/web3.js`. This makes it difficult for you to remove the legacy library from your project.
The chances are, though, that module only needs a _fraction_ of what web3.js provides.
The goal of the sham – of which this PR is the first – is to provide drop-in replacements for just the things that a set list of known dependencies require. You should be able to hot-swap the sham in via npm `overrides` or yarn `resolutions` and thereby drop the legacy web3.js from your bundle.
This PR introduces an interface compatible(-ish) `Keypair` that you can use as a drop-in replacement for the one in `@solana/web3.js@1`
```
cd packages/library-legacy-sham/
```
See later diffs for a …

refactor(experimental): create a sham for `Keypair`

---

packages/test-config/browser-environment.ts
packages/test-config/jest-unit.config.browser.ts

1. When you're running browser tests, we use the JSDOM environment
2. JSDOM doesn't support `SubtleCrypto` yet, so we inject `node:crypto`
3. Now we're in a situation where `Uint8Array` comes from JSDOM but the `instanceof` checks inside `SubtleCrypto#digest` are made against the Node instance of `Uint8Array`. These checks never pass.
To solve this, we override the `Uint8Array` global in JSDOM with the one from Node. Oh well.

refactor(experimental): use Node's instance of `Uint8Array` in browser tests

---

packages/assertions/.vscode/settings.json
packages/build-scripts/getBaseConfig.ts
packages/build-scripts/package.json
packages/library-legacy/tsconfig.json
packages/test-matchers/tsconfig.json
packages/tsconfig/base.json
pnpm-lock.yaml

We're building a library. We don't deploy directly on the target – our customers do. They should have the final say what ECMA target they want to run against (eg. ES2020, ES2015, et cetera).
It's wise, therefore, to compile our _library_ at the highest possible target (ie. ESNext) so as not to lose any features/information on the way into our customers' build systems.
The only exception is the IIFE bundle that we ship, which we compile to the `browserslist` target "`supports bigint and not dead`".
Thanks to @hyrious for [the suggestion](https://github.com/evanw/esbuild/issues/3500#issuecomment-1820046687).
Spot check the compiled source in `packages/library-legacy-sham`
1. The browser/node/native bundles still have all of the private property syntax intact
2. The developement/production …

refactor(experimental): build libraries at the highest ECMAScript target possible

---

packages/transactions/src/index.ts
packages/transactions/src/serializers/index.ts

This allows consumers to perform signing logic manually:
```ts
const compiledMessage = compileMessage(transaction);
const bytes = getCompiledMessageEncoder().encode(compiledMessage);
// app logic
const signature = signTransaction(bytes);
```
This is probably not a super common use case, but it's necessary for eg a wallet that doesn't necessarily have `CryptoKeyPair` objects available for accounts it is signing for, and therefore can't use our `signTransaction` helper function.

refactor(experimental): export from messages in @solana/transactions

---

packages/library-legacy-sham/src/__tests__/connection-test.ts
packages/library-legacy-sham/src/__typetests__/connection-typetests.ts
packages/library-legacy-sham/src/connection.ts

The target of this sham is to be a drop-in replacement for `@solana/wallet-adapter` and nothing else. That library (unfortunately) uses `useConnection` solely to obtain the `rpcEndpoint`.
TBD

refactor(experimental): create a `Connection` sham that only exposes `rpcEndpoint`

---

packages/signers/README.md
packages/signers/src/__tests__/sign-transaction-test.ts
packages/signers/src/message-modifying-signer.ts
packages/signers/src/message-partial-signer.ts
packages/signers/src/sign-transaction.ts
packages/signers/src/transaction-modifying-signer.ts
packages/signers/src/transaction-partial-signer.ts
packages/signers/src/transaction-sending-signer.ts
packages/signers/src/types.ts

- Adds the optional config object `{ abortSignal?: AbortSignal }` to all five signer interfaces.
```ts
mySigner.signTransactions([tx], { abortSignal });
mySigner.signTransactions([tx]); // <- Still works.
```
- Refactor the `partiallySignTransactionWithSigners`, `signTransactionWithSigners` and  `signAndSendTransactionWithSigners` functions so everything after the first argument is bundled in an optional config object.
```ts
// Before
partiallySignTransactionWithSigners(tx, [otherSigner]);
signTransactionWithSigners(tx, [otherSigner]);
signAndSendTransactionWithSigners(tx, [otherSigner]);
signAndSendTransactionWithSigners(tx, [], fallbackSender);
// After
partiallySignTransactionWithSigners(tx, { signers: [otherSigner] });
signTransactionWithSigners(tx, { signers: [otherSigner] }); …
```

refactor(experimental): add AbortSignal support to the Signer API

---

packages/signers/README.md
packages/signers/src/__tests__/noop-signer-test.ts
packages/signers/src/index.ts
packages/signers/src/noop-signer.ts

This PR provides a `NoopSigner` implementation of the `TransactionPartialSigner` and `MessagePartialSigner` interfaces.
See the following section of the updated documentation for more details.
---
For a given address, a Noop (No-Operation) signer can be created to offer an implementation of both the `MessagePartialSigner` and `TransactionPartialSigner` interfaces such that they do not sign anything. Namely, signing a transaction or a message with a `NoopSigner` will return an empty `SignatureDictionary`.
This signer may be useful:
- For testing purposes.
- For indicating that a given account is a signer and taking the responsibility to provide the signature for that account ourselves. For instance, if we need to send the transaction to a server that will sign it and send it for us. …

refactor(experimental): add NoopSigners

---

packages/signers/src/__tests__/account-signer-meta-test.ts
packages/signers/src/__tests__/deduplicate-signers-test.ts
packages/signers/src/deduplicate-signers.ts

Deduplicate signers by reference only. Meaning, when extracting all signers in a transaction, we will remove duplicated reference of the same signer object. However, if we identity two different signer objects for the same address, we will fail as it is impossible to come up with a heuristic that works with every use-cases.
```ts
const signerA = await generateKeyPairSigner();
const signerB = await generateKeyPairSigner();
deduplicateSigners([signerA, signerB, signerA, signerB]);
// ^ [signerA, signerB]
deduplicateSigners([signerA, signerB, { ...signerA }]);
// ^ Error: Multiple distinct signers were identified for address A.
```
This improvement was suggested by the reviews of #1792.

refactor(experimental): deduplicate signers by reference

---

packages/signers/README.md
packages/signers/src/__tests__/sign-transaction-test.ts
packages/signers/src/sign-transaction.ts

This PR removes the optional `signers` array that allowed users to manually inject additional signers to the signing flow.
It removes it in favour of new helpers methods `addSignersToInstruction` and `addSignersToTransaction` introduces in the following PR (#1873).
This improvement was suggested by the reviews of #1792.

refactor(experimental): remove extra signers option

---

packages/signers/README.md
packages/signers/src/__tests__/__setup__.ts
packages/signers/src/__tests__/add-signers-test.ts
packages/signers/src/account-signer-meta.ts
packages/signers/src/add-signers.ts
packages/signers/src/index.ts
packages/signers/src/sign-transaction.ts

This PR provides two helper methods `addSignersToInstruction` and `addSignersToTransaction` which, given an array of signers, go through the account metas of the provided object and attach signers to them when applicable.
For an account meta to match a provided signer it:
-   Must have a signer role (`AccountRole.READONLY_SIGNER` or `AccountRole.WRITABLE_SIGNER`).
-   Must have the same address as the provided signer.
-   Must not have an attached signer already.
```ts
const myInstruction: IInstruction = {
accounts: [
{ address: '1111' as Address, role: AccountRole.READONLY_SIGNER },
{ address: '2222' as Address, role: AccountRole.WRITABLE_SIGNER },
],
// ...
};
const signerA: TransactionSigner<'1111'>;
const signerB: TransactionSigner<'2222'>;
const myInstructionWithSigners = …
```

refactor(experimental): helper functions that add signers to instructions and transactions

---

package.json
turbo.json

This PR reworks our `publish-packages` flow to hopefully be more robust and less annoying
Previously, we ran all the `build` and `publish-packages` jobs in parallel, which meant that you could have a build job fail (eg we have some flaky tests sometimes) after some packages had published. This doesn't sound like a problem, but if you re-ran the job then it would attempt to re-publish those packages and that would fail. This ultimately meant that if a `build` job failed you could probably never get to a point where all packages were published by re-running the CI.
This PR adds the `--continue` flag to the `turbo run publish-packages` line. This means that if a job fails then it is ignored and other independent jobs can continue. This means that if you need to publish 20 packages and 10 are …

refactor(experimental): improve robustness of publish-packages

---

turbo.json

There's an issue with my change in #1879 but I'm not too sure what it is
```bash
$ npm install @solana/web3.js@experimental
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @solana/codecs-core@2.0.0-development.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist
```
The latest experimental tagged version of [@solana/web3.js is 2.0.0-experimental.d93c93b](https://www.npmjs.com/package/@solana/web3.js?activeTab=versions)
And for the child packages eg [@solana/codecs-core  mentioned in that error, it's also 2.0.0-experimental.d93c93b](https://www.npmjs.com/package/@solana/codecs-core?activeTab=versions)
So it is correctly publishing the packages with the right versions, but seems to have …

Add a dependsOn line for publish-packages in turbo

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/loaders/account.ts
packages/rpc-graphql/src/loaders/program-accounts.ts
packages/rpc-graphql/src/loaders/transformers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR attempts to revise the accounts schema, as per #1831.

refactor(experimental-graphql): revise accounts schema (again)

---

packages/library-legacy-sham/package.json
packages/library-legacy-sham/src/__tests__/transaction-test.ts
packages/library-legacy-sham/src/__typetests__/transaction-typetests.ts
packages/library-legacy-sham/src/index.ts
packages/library-legacy-sham/src/transaction.ts
packages/library-legacy-sham/src/unimplemented.ts
pnpm-lock.yaml

This is a sham that lets you wrap some transaction bytes (in wire format) in a `Transaction`-like class that will vend you the signature. This is the minimum one might like to do given a sent transaction that they just want the signature of (eg. for lookup on a block explorer)
```
cd packages/library-legacy-sham
```

refactor(experimental): a sham for `Transaction`

---

packages/library-legacy-sham/src/__tests__/versioned-transaction-test.ts
packages/library-legacy-sham/src/__typetests__/versioned-transaction-typetest.ts
packages/library-legacy-sham/src/index.ts
packages/library-legacy-sham/src/versioned-transaction.ts

This is a sham that lets you wrap some transaction bytes (in wire format) in a `VersionedTransaction`-like class that will vend you the signatures. This is the minimum one might like to do given a sent transaction that they just want the signatures of (eg. for lookup on a block explorer)
```
cd packages/library-legacy-sham
```

refactor(experimental): a sham for `VersionedTransaction`

---

packages/compat/package.json
packages/compat/src/keypair.ts
packages/keys/src/__tests__/private-key-test.ts
packages/keys/src/__tests__/signatures-test.ts
packages/keys/src/index.ts
packages/keys/src/private-key.ts
packages/rpc-core/src/rpc-methods/__tests__/send-transaction-test.ts
packages/rpc-core/src/rpc-methods/__tests__/simulate-transaction-test.ts
pnpm-lock.yaml

Sometimes you just have the bytes already, but you don't want to have to futz with crafting your own PKCS#8 payload. This helper will do it for you.
Note: I left the PKCS#8 header alone in the polyfill, because it's designed to eventually go away.
```
cd packages/keys/
```
Closes #1813.

refactor(experimental): a `createPrivateKeyFromBytes` helper

---

packages/codecs-core/src/__tests__/__setup__.ts
packages/codecs-core/src/__tests__/codec-test.ts
packages/codecs-core/src/__tests__/combine-codec.ts
packages/codecs-core/src/__tests__/fix-codec-test.ts
packages/codecs-core/src/__tests__/map-codec-test.ts
packages/codecs-core/src/__tests__/reverse-codec-test.ts
packages/codecs-core/src/assertions.ts
packages/codecs-core/src/codec.ts
packages/codecs-core/src/combine-codec.ts
packages/codecs-core/src/fix-codec.ts
packages/codecs-core/src/map-codec.ts
packages/codecs-core/src/reverse-codec.ts

_Note this is a draft PR focusing on `codecs-core` to gather feedback, I will continue to update the other libraries afterwards._
This PR updates the codecs API such that both encoding and decoding function **have access to the entire byte array**. Let’s first see the change this PR introduce and then see why this is a valuable change.
- **Encode**: The `Encoder` type contains a new function `write`. Contrary to the `encode` function which creates a new `Uint8Array` and returns it directly, the `write function` updates the provided `bytes` argument at the provided `offset`. It then returns the next offset that should be written to.
```ts
// Before
type Encoder<T> = {
encode: (value: T) => Uint8Array;
// ...
};
// After
type Encoder<T> = {
encode: (value: T) => Uint8Array;
write: (value: …
```

refactor(experimental): pre-build the byte array before encoding with codecs

---

packages/codecs-core/src/__tests__/__setup__.ts
packages/codecs-core/src/__tests__/codec-test.ts
packages/codecs-core/src/__tests__/combine-codec.ts
packages/codecs-core/src/__tests__/map-codec-test.ts
packages/codecs-core/src/__typetests__/codec-typetest.ts
packages/codecs-core/src/assertions.ts
packages/codecs-core/src/codec.ts
packages/codecs-core/src/combine-codec.ts
packages/codecs-core/src/fix-codec.ts
packages/codecs-core/src/map-codec.ts
packages/codecs-core/src/reverse-codec.ts
packages/codecs-numbers/src/__tests__/__setup__.ts
packages/codecs-numbers/src/__tests__/short-u16-test.ts
packages/codecs-numbers/src/short-u16.ts
packages/codecs-strings/src/__tests__/string-test.ts
packages/codecs-strings/src/base16.ts
packages/codecs-strings/src/base64.ts
packages/codecs-strings/src/baseX-reslice.ts
packages/codecs-strings/src/baseX.ts
packages/codecs-strings/src/string.ts
packages/codecs-strings/src/utf8.ts

As suggested [here](https://github.com/solana-labs/solana-web3.js/pull/1865#discussion_r1407939794), this PR removes the `{ fixedSize: null }` attribute from `VariableSize*` types. This makes it easier and less confusing the create and use variable-size codecs.
Since it's now slightly less convinient to find out if a codec if fixed-size or not, this PR also offers type guards to make this easier.

refactor(experimental): remove `{ fixedSize: null }` from variable size codecs

---

packages/codecs-core/src/__typetests__/codec-typetest.ts
packages/codecs-core/src/__typetests__/combine-codec-typetest.ts
packages/codecs-core/src/__typetests__/fix-codec-typetest.ts
packages/codecs-core/src/__typetests__/map-codec-typetest.ts
packages/codecs-core/src/__typetests__/reverse-codec-typetest.ts
packages/codecs-core/src/codec.ts
packages/codecs-core/src/combine-codec.ts
packages/codecs-core/src/fix-codec.ts
packages/codecs-core/src/map-codec.ts
packages/codecs-core/src/reverse-codec.ts
packages/codecs-numbers/src/common.ts
packages/codecs-numbers/src/f32.ts
packages/codecs-numbers/src/f64.ts
packages/codecs-numbers/src/i128.ts
packages/codecs-numbers/src/i16.ts
packages/codecs-numbers/src/i32.ts
packages/codecs-numbers/src/i64.ts
packages/codecs-numbers/src/i8.ts
packages/codecs-numbers/src/u128.ts
packages/codecs-numbers/src/u16.ts
packages/codecs-numbers/src/u32.ts
packages/codecs-numbers/src/u64.ts
packages/codecs-numbers/src/u8.ts
packages/codecs-numbers/src/utils.ts
packages/codecs-strings/src/__typetests__/string-typetest.ts
packages/codecs-strings/src/string.ts

This PR adds the `TSize extends number` type parameter to fixed-size encoder, decoder and codecs. This makes it possible to make TypeScript assertions based on the codec's size.
It also renames all existing type parameters to make them consistent with the rest of the library.

refactor(experimental): add size type param to fixed-size codecs

---

packages/rpc-core/src/rpc-methods/common-transactions.ts
packages/rpc-core/src/rpc-methods/common.ts

The types for `jsonParsed` encoding on `AccountInfo` and
`ParsedTransactionInstruction` are not matching, even though both response types
implement the same `jsonParsed` interface.
Bring these types to parity.

refactor(experimental): bring `jsonParsed` types to parity

---

.github/workflows/pull-requests.yml

Our new Graphite workflow means that the mergebase of stacked PRs is the PR before it. Since that is by definition not `master` this pull request workflow wasn't running.

chore: run CI on pull requests to all branches

---

packages/accounts/package.json
packages/addresses/package.json
packages/assertions/package.json
packages/build-scripts/add-js-extension-to-types.mjs
packages/build-scripts/package.json
packages/codecs-core/package.json
packages/codecs-data-structures/package.json
packages/codecs-numbers/package.json
packages/codecs-strings/package.json
packages/compat/package.json
packages/functional/package.json
packages/instructions/package.json
packages/keys/package.json
packages/library-legacy-sham/package.json
packages/library/package.json
packages/options/package.json
packages/rpc-core/package.json
packages/rpc-graphql/package.json
packages/rpc-transport/package.json
packages/rpc-types/package.json
packages/signers/package.json
packages/transactions/package.json
packages/webcrypto-ed25519-polyfill/package.json

This is an alternative solution to #1902 and #1904.
It essentially goes through all the compiled `dist/**/**.d.ts` files and add the `.js` extension to relative import and exports.
For instance, it transforms `packages/addresses/dist/types/index.d.ts` from this:
```ts
export * from './address';
export * from './program-derived-address';
export * from './public-key';
//# sourceMappingURL=index.d.ts.map
```
To this:
```ts
export * from './address.js';
export * from './program-derived-address.js';
export * from './public-key.js';
//# sourceMappingURL=index.d.ts.map
```
It also checks whether the imported relative path is a folder and, when it is, adds `/index.js` instead of `.js`.
For instance, it transforms `packages/rpc-core/dist/types/index.d.ts` from this:
```ts
export * from …
```

refactor(experimental): add build script that adds .js to type imports

---

packages/build-scripts/getBaseConfig.ts

`__DEV__` is only supposed to be replaced for the IIFE library builds. We were building every package twice here for no reason.
In limited testing, seems to speed up total-repo `compile:js` by about 5%.

chore: stop building every package twice

---

packages/rpc-core/src/index.ts

This PR adds the `TransactionError` type to the exports of the `@solana/rpc-core` package. Note that this package is not currently re-exported by `@solana/web3.js`. 
This is useful for writing a wrapper function around `simulateTransaction` or `sendTransaction`, where you want to return a `TransactionError` if one is returned by the RPC calls.

refactor(experimental): export the TransactionError type to consumers of @solana/rpc-core

---

packages/rpc-core/src/rpc-methods/index.ts
packages/rpc-core/src/rpc-subscriptions/index.ts
packages/rpc-transport/README.md
packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
packages/rpc-transport/src/__tests__/json-rpc-test.ts
packages/rpc-transport/src/json-rpc-subscription.ts
packages/rpc-transport/src/json-rpc-types.ts
packages/rpc-transport/src/json-rpc.ts

This PR renames things like `responseProcessor`, which uses the term
`*Processor`, to instead use the term `*Transformer`.

refactor(experimental): rename `*Processor` to `*Transformer`

---

packages/rpc-core/src/rpc-methods/index.ts
packages/rpc-transport/src/__tests__/json-rpc-test.ts
packages/rpc-transport/src/apis/__typetests__/methods-api-typetest.ts
packages/rpc-transport/src/apis/methods/methods-api.ts
packages/rpc-transport/src/index.ts
packages/rpc-transport/src/json-rpc-types.ts
packages/rpc-transport/src/json-rpc.ts

This PR is a concept for now. It serves to potentially address the discussion raised in #1740.
The goal of the collective `@solana/rpc-*` packages has been to allow complete customization, as long as their API adheres to the [official JSON RPC spec](https://www.jsonrpc.org/specification).
However, I couldn't find the best way someone would _actually_ go about doing this with our current implementation. Maybe I'm missing something.
In the actual `library` package, we're providing what's been dubbed the "default" Solana API. The function `createSolanaRpc(..)` allows you to provide your own transport, but it automatically uses the Solana RPC API, defined by `@solana/rpc-core` for the client API.
https://github.com/solana-labs/solana-web3.js/blob/589c379aa0ab495f50dac873f06573f52cdc9f98/packag …

refactor(experimental): add generic `createJsonRpcApi` function for custom APIs

---

packages/rpc-core/src/rpc-subscriptions/account-notifications.ts
packages/rpc-core/src/rpc-subscriptions/block-notifications.ts
packages/rpc-core/src/rpc-subscriptions/index.ts
packages/rpc-core/src/rpc-subscriptions/logs-notifications.ts
packages/rpc-core/src/rpc-subscriptions/program-notifications.ts
packages/rpc-core/src/rpc-subscriptions/root-notifications.ts
packages/rpc-core/src/rpc-subscriptions/signature-notifications.ts
packages/rpc-core/src/rpc-subscriptions/slot-notifications.ts
packages/rpc-transport/src/apis/api-types.ts

This PR introduces a type for `IRpcSubscriptionsApi` and ensures all
subscriptions defined in `@solana/rpc-core` extend this type.
This will allow our subscription interfaces to be used in the generic
`createJsonRpcSubscriptionsApi(..)` (next commit).

refactor(experimental): make RPC subscription methods extend `IRpcSubscriptionsApiMethods`

---

packages/rpc-core/src/rpc-subscriptions/index.ts
packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
packages/rpc-transport/src/apis/__typetests__/subscriptions-api-typetest.ts
packages/rpc-transport/src/apis/api-types.ts
packages/rpc-transport/src/apis/subscriptions/subscriptions-api.ts
packages/rpc-transport/src/index.ts
packages/rpc-transport/src/json-rpc-subscription.ts
packages/rpc-transport/src/json-rpc-types.ts

Continuing the work from #1781, this PR adds a generic function for creating an
RPC Subscriptions API, and drives this function from the main `@solana/web3.js`.

refactor(experimental): add generic `createJsonRpcSubscriptionsApi` for custom APIs

---

packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/slots-updates-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/vote-notifications-test.ts

Some of our Jest tests have leaky open handles, many of which are tied to
subscriptions tests that leave the subscription open.
This PR adds abort signals for closing subscriptions after each test.
Part of #1948

refactor(experimental): close leaky open handles in subscriptions tests

---

packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/slots-updates-notifications-test.ts
packages/rpc-core/src/rpc-subscriptions/__tests__/vote-notifications-test.ts

This PR adds `try...finally` wrappers around the subscriptions tests to make
sure the subscription is closed even if the test fails.

refactor(experimental): wrap subscription tests in `try...finally`

---

packages/accounts/README.md
packages/accounts/src/__tests__/maybe-account-test.ts
packages/accounts/src/__typetests__/maybe-account-typetest.ts
packages/accounts/src/maybe-account.ts

This PR adds a new `assertAccountsExist` function to assert that all MaybeAccounts in an array exist. If any accounts do not exist then a single error is thrown including the address of all missing accounts.
This can be used to narrow the result of `fetchEncodedAccounts` or `fetchJsonParsedAccounts`:
```ts
const accounts = fetchEncodedAccounts(rpc, ['1111', '2222', '3333'])
assertAccountsExist(accounts);
accounts.map(a => a.data); // OK
```

Add assertAccountsExist function to @solana/accounts

---

packages/rpc-graphql/src/loaders/transaction.ts

**Issue:**
The intention here seems to be to fetch the transaction again with jsonParsed encoding if the requested encoding is not jsonParsed.  but the config object passed to rpc.getTransaction in this block is the same as the original call and will still contain the original encoding. It does not change to jsonParsed as intended.
**Fix:**
Created a new jsonParsedConfig object with encoding explicitly set to jsonParsed. This ensures the second call to rpc.getTransaction fetches the transaction with the jsonParsed encoding.

Update encoding in the transaction config

---

packages/accounts/README.md
packages/accounts/src/__tests__/decode-account-test.ts
packages/accounts/src/__tests__/maybe-account-test.ts
packages/accounts/src/__typetests__/decode-account-typetest.ts
packages/accounts/src/__typetests__/maybe-account-typetest.ts
packages/accounts/src/decode-account.ts
packages/accounts/src/maybe-account.ts

This PR adds two new functions to the `accounts` package, `assertAccountDecoded` and `assertAccountsDecoded`.
These narrow `Account<TData | Uint8Array>` to `Account<TData>`
This is particularly useful for handling the result of `fetchJsonParsedAccount<TData>`. This returns a `MaybeAccount<TData | Uint8Array>`, ie the account might or might not exist, and if it does exist then the account might or might not have actually returned JSON parsed data.
Note that as with the rest of the `accounts` package, we're not asserting that the data matches the declared shape. The only check done here is whether it's a `Uint8Array`, if it's not then we narrow it to `TData`. 
We already had `assertAccountExists` to narrow to `Account<TData | Uint8Array>`, so this function adds the final step to narrow it …

Add function to assert account(s) are decoded

---

packages/library-legacy/src/transaction/legacy.ts
packages/library-legacy/src/utils/Pair.ts
packages/library-legacy/test/transaction.test.ts

In my experience, an annoying error to get because it doesn't give you the information you really want (which account has the problem) even though it clearly can. This PR fixes this.
Also seems I'm not the only that finds this annoying: https://twitter.com/redacted_noah/status/1742943786299191741

feat: specify which account is missing/has an invalid signature on signature verification failure

---

packages/library/src/__tests__/transaction-confirmation-strategy-blockheight-test.ts
packages/library/src/__tests__/transaction-confirmation-test.ts
packages/library/src/transaction-confirmation-strategy-blockheight.ts
packages/library/src/transaction-confirmation.ts

This PR repairs the block height exceedence detection in the transaction confirmer. Previously, we mistakenly compared slot height to the last valid block height. Those are not equivalent values.
Since there is no subscription API for block height, this implementation determines the difference between the slot height and the block height, then subscribes to the slot height. It waits until the slot when the block height is expected to be exceeded to be reached.
Finally, in consideration that one or more blocks might have been skipped since having started to wait, it rechecks the slot height / block height difference before failing.
```
cd packages/library/
pnpm turbo test:unit:browser
pnpm turbo test:unit:node
```
Fixes #1985.

Detect block height exceedences using a combination of slot notifications and `getEpochInfo`

---

packages/library/src/index.ts

It's wierd for `@solana/functional` to be the only thing that you have to add as a dependency separate from `@solana/web3.js`, if that's the way you're going.

Export `@solana/functional` from the main library

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts

This PR enforces scoped RPC APIs in tests for `@solana/rpc-graphql`.

refactor(experimental): use scoped APIs in rpc-graphql tests

---

packages/rpc-graphql/src/loaders/account.ts
packages/rpc-graphql/src/loaders/block.ts
packages/rpc-graphql/src/loaders/program-accounts.ts
packages/rpc-graphql/src/loaders/transaction.ts

This PR enforces use of scoped RPC APIs in the loaders of `@solana/rpc-graphql`.

refactor(experimental): use scoped APIs in rpc-graphql

---

packages/rpc-transport/src/__typetests__/methods-api-typetest.ts
packages/rpc-transport/src/__typetests__/subscriptions-api-typetest.ts

This PR moves the type tests for `@solana/rpc-transport` into the main `src`
directory.

refactor(experimental): move rpc-transport type tests into `src`

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/loaders/transformers/transaction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR fixes the `transformParsedInstruction(..)` function to support proper
parsing of `spl-memo` instructions.

refactor(experimental): fix memo instructions in GraphQL

---

packages/codecs-data-structures/src/__tests__/array-test.ts
packages/codecs-data-structures/src/__tests__/map-test.ts
packages/codecs-data-structures/src/__tests__/set-test.ts
packages/codecs-data-structures/src/__typetests__/array-typetest.ts
packages/codecs-data-structures/src/__typetests__/map-typetest.ts
packages/codecs-data-structures/src/__typetests__/set-typetest.ts
packages/codecs-data-structures/src/array.ts
packages/codecs-data-structures/src/map.ts
packages/codecs-data-structures/src/set.ts

This PR allows `Array`, `Map` and `Set` codecs of `"remainder"` size to have variable-size items (as [recently updated on Umi's serializers](https://github.com/metaplex-foundation/umi/pull/107)).
These array-like codecs support the following three configurable size strategies:
- `{ size: 42 }` means a fixed-size array of 42 items.
- `{ size: getU32Codec() }` means the array is prefixed by a `u32` number storing its number of items.
- `{ size: "remainder" }` means the remainder of the bytes should be used to encode and/or decode the items inside the array.
Prior to this PR, we were enforcing arrays of `"remainder"` size to have fixed-size items. This allowed us to pre-compute the size of the array by dividing the size of what's left in the bytes by the fixed size of its item codec. If the …

refactor(experimental): add support for variable-sized items in remainder-sized codecs

---

packages/library/package.json
packages/library/src/index.ts
pnpm-lock.yaml

Same logic as https://github.com/solana-labs/solana-web3.js/pull/2007
`accounts` is a relatively high level package and you shouldn't need to install it separately from `@solana/web3.js` if you're using the main package.

Re-export @solana/accounts from @solana/web3.js

---

packages/rpc-core/src/rpc-methods/__typetests__/rpc-methods-test.ts
packages/rpc-core/src/rpc-methods/getTokenAccountsByDelegate.ts
packages/rpc-core/src/rpc-methods/getTokenAccountsByOwner.ts

These data stuctures were messed up, with the `TokenAccount` nested under the `program` instead of `data`
I've added typetests to verify the fix. I don't think we had these when we first wrote most of these methods, but they're better than the unit tests we have for rpc-methods TBH. Probably worth adding them at least where we find bugs!

Fix return type of getTokenAccountsByDelegate/Owner

---

packages/transactions/src/__tests__/decompile-transaction-test.ts
packages/transactions/src/decompile-transaction.ts
packages/transactions/src/serializers/__tests__/transaction-test.ts
packages/transactions/src/serializers/transaction.ts

This PR updates `decompileTransaction` to support transactions that include address lookup tables. It is passed a dictionary of `Address -> Address[]` mapping each lookup table address to its addresses. These are used to generate `IAccountLookupMeta` objects for the instructions that use addresses from the lookup tables. An error is thrown for any lookup table required by the transaction that is missing from the mapping passed in.
The `getTransactionDecoder` and `getTransactionCodec` functions are both modified to receive this mapping of address lookups and pass it to `decompileTransaction`. It is the responsibility of the caller to fetch the required lookups and pass them in.
A follow up PR will add an async `decodeTransaction` helper function to the `library` package that uses an …

Update transaction decoder to use lookup tables

---

packages/transactions/src/__tests__/decompile-transaction-test.ts
packages/transactions/src/decompile-transaction.ts

This PR fixes a bug where decompiling a transaction that had no real signatures would result in returning `signatures: {}` instead of excluding that field. This meant that compiling and then decompiling such a transaction would not give an identical result when it should.
When we compile a transaction, we insert an all-zero 64-byte Uint8Array in place of all missing signatures.
We already had logic to exclude these signatures when we decompile a transaction, since we don't store them on our `Transaction` model. They're simply an artifact of compiling a transaction.
But the logic that determined whether to include the `signatures` field used the input `compiledTransaction.signatures` instead of our filtered and reshaped signatures to determine whether there were any signatures. This meant …

Fix bug where decompileTransaction would return empty signatures instead of excluding the field

---

packages/library/src/__tests__/decode-transaction-test.ts
packages/library/src/decode-transaction.ts
packages/transactions/src/index.ts
packages/transactions/src/serializers/transaction.ts

This PR adds a new helper function `decodeTransaction`. It takes as input encoded transaction bytes and a function to get multiple accounts. It:
- Decodes the transaction to an intermediate `CompiledTransaction`
- Inspects that transaction, and if it contains any address lookup tables it fetches them using `fetchJsonParsedAccounts`
- Decompiles the `CompiledTransaction` using the fetched lookup tables
This gives us the ability to decode an arbitrary transaction, whether or not it has address lookup tables

Add async function to decode a transaction using an RPC to fetch lookup tables

---

packages/library-legacy/src/connection.ts

Caused some initial confusion for me when using this type, as it wasn't directly obvious to me that the returned data is encoded in base64, not that the addresses themselves are meant to be in base64 (they're meant to be in base58 as usual).  Not sure if this is just me being a doofus, but either way specifying the encoding in a comment can't hurt.

nit: Add comment specifying encoding of addresses

---

packages/library-legacy/src/connection.ts

When rate limiting errors are hit in the legacy library, an error message is logged via `console.log` rather than `console.error`. This means that this error message gets logged to `stdout` for node apps.. which is very annoying when writing node scripts.

fix: change request retry output log to an error log

---

packages/library/package.json
packages/library/src/index.ts
pnpm-lock.yaml

Since these are intended to be used with `accounts` or `rpc-core` account fetching, I think it makes sense to export them from the main package too.

Export @solana/rpc-parsed-types from the main library

---

packages/rpc-parsed-types/src/index.ts

This PR exports the `RpcParsedType` that is used for the tagged union when there are multiple JSON parsed accounts for the same program
Exporting this makes it easy for a caller to create a conditional type to define each individual subtype that it needs, without us exporting them all

Export RpcParsedType from rpc-parsed-types package

---

packages/library/README.md
packages/library/package.json
packages/library/src/__tests__/transaction-confirmation-strategy-nonce-test.ts
packages/library/src/index.ts
packages/library/src/transaction-confirmation-strategy-nonce.ts
pnpm-lock.yaml

This PR adds the new `@solana/codecs` umbrella package to the main `@solana/web3.js` library.
Codecs are a core component of the new Web3.js and are already being fully imported by the current dependencies of the main library. For instance, `@solana/transactions` — which is re-exported by the main library — uses them all.
Therefore, it makes sense to also export them from the main library so end-users can easily leverage them in their own applications.

refactor(experimental): add codecs to main library

---

packages/rpc-types/package.json
pnpm-lock.yaml

Some idiot (me) added a `workspace:2.0.0-development` dependency and broke installing all the things
```
$ npm install @solana/web3.js@2.0.0-experimental.4c9a8b8
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @solana/codecs-strings@2.0.0-development.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
This PR fixes it!

remove broken 2.0.0-development dependency

---

packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/schema/block.ts
packages/rpc-graphql/src/schema/transaction.ts

In the Solana monorepo, a [`UnixTimestamp`](https://github.com/solana-labs/solana/blob/098076f5cab81a54335330993842fc0831e1ca65/sdk/program/src/clock.rs#L173) is of type `i64`. Therefore, timestamps should be `BigInt`.
Closes #2061

refactor(experimental): graphql: fix `blockTime` in transaction schema

---

packages/accounts/package.json
packages/accounts/src/__tests__/__setup__.ts
packages/accounts/src/__typetests__/fetch-account-typetest.ts
packages/accounts/src/fetch-account.ts
packages/accounts/src/parse-account.ts
packages/accounts/src/rpc-api/common.ts
packages/accounts/src/rpc-api/getAccountInfo.ts
packages/accounts/src/rpc-api/getMultipleAccounts.ts
packages/accounts/src/rpc-api/index.ts
pnpm-lock.yaml

This PR removes the `@solana/rpc-core` dependency from `@solana/accounts` which avoids ending up with unused nested dependencies such as `@solana/transactions` when we only need the `GetAccountInfoApi` and `GetMultipleAccountsApi` types.
It does this by simply duplicating the types locally in the `@solana/accounts` package.

refactor(experimental): decouple @solana/accounts from @solana/rpc-core

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/index.ts

This PR fixes the caching problem reported on the Playground's repository at
<https://github.com/solana-labs/solana-graphql-playground/issues/19>.
It refactors the entrypoint to create the instance of the loaders/resolvers at
the time of querying, meaning each query gets a fresh cache.

refactor(experimental): graphql: refactor entrypoint to fix caching

---

packages/rpc-parsed-types/src/__typetests__/address-lookup-table-accounts-test.ts
packages/rpc-parsed-types/src/__typetests__/nonce-accounts-test.ts
packages/rpc-parsed-types/src/__typetests__/vote-accounts-test.ts
packages/rpc-parsed-types/src/address-lookup-table-accounts.ts
packages/rpc-parsed-types/src/nonce-accounts.ts
packages/rpc-parsed-types/src/rpc-parsed-type.ts
packages/rpc-parsed-types/src/vote-accounts.ts

Some of the programs that own JSON parseable accounts, such as token, have accounts with multiple types. They have both `info` and `type` fields, and we have these typed so that you can discriminate using the `type` field.
But some other programs, such as vote and address lookup tables, have only one type of account. They don't have a `type` field but do have the `info` field, with the same shape for all their accounts.
Since I didn't need to discriminate them, I exported these types without the`info` field too. This PR changes this so that their type includes the `info` field, with all their properties nested inside it.
I found that it's annoying to use these as-is because you end up with some types having an `info` field containing their properties, and others not. But if the data comes …

refactor(experimental): add `info` field to JSON parsed types

---

packages/library/src/index.ts

It turns out this function is less helpful when it's not exported from the package!

Export the async decodeTransaction function from library

---

packages/errors/src/__tests__/error-test.ts
packages/errors/src/__tests__/message-formatter-test.ts
packages/errors/src/codes.ts
packages/errors/src/context.ts
packages/errors/src/error.ts
packages/errors/src/messages.ts
packages/library/package.json
packages/library/src/__tests__/transaction-confirmation-test.ts
packages/signers/package.json
packages/signers/src/__tests__/sign-transaction-test.ts
packages/transactions/package.json
packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/signatures.ts
pnpm-lock.yaml

In this PR we make first use of the new `SolanaError` class to convert two regular errors into coded errors.
```shell
pnpm turbo test:unit:browser
pnpm turbo test:unit:node
```

Convert two errors in `@solana/transactions` to the new coded error system

---

packages/errors/README.md
packages/errors/bin/cli.ts
packages/errors/package.json
packages/errors/src/__tests__/message-formatter-test.ts
packages/errors/src/message-formatter.ts
packages/errors/tsconfig.json
pnpm-lock.yaml

The goal here is to strip _all_ error messages from production builds of Solana apps, while still preserving the ability to recover the error text.
We do this as follows:
- Strip the errors out in production mode
- Replace them with the error code and the serialized context they were thrown with
- Provide an npm binary that you can call (just copy and paste the message into your terminal) to decode the error
```shell
npx . decode 69420 $"addresses=%5B%22J2obR2DK7gnd6H88HjKzEYuMyboDWRNpbzwmGSh31nnu%22,%22HpcB5Qg8Y9E73dUkot5e8HkgAJbExsYeUzniY4bCuKac%22%5D"
```

An error decoder for production Solana coded errors

---

packages/errors/package.json
packages/errors/src/__typetests__/error-typetest.ts
pnpm-lock.yaml

This typetest really drives home how to use `SolanaError` and `isSolanaError()` in practice. Watch how you can refine errors by code, and how the type of the context materiailzes with it.
```shell
cd packages/errors/
pnpm turbo test:typecheck
```

A typetest for coded errors

---

.github/workflows/cicd.yml
.github/workflows/pull-requests.yml

The newest version of Turborepo collects anonymous telemetry by default. This, at least, turns this off in CI.

Ask Turborepo and others not to collect telemetry in CI

---

packages/rpc-types/src/cluster-url.ts
packages/rpc-types/src/index.ts

As per @lorisleiva's suggestion, here's some types for cluster URLs!
Straight from [this comment](https://github.com/solana-labs/solana-web3.js/pull/2053#issuecomment-1916636042)

refactor(experimental): add `ClusterUrl` types

---

packages/rpc-transport/src/__typetests__/json-rpc-typetest.ts
packages/rpc-transport/src/apis/__typetests__/methods-api-typetest.ts
packages/rpc-transport/src/apis/__typetests__/subscriptions-api-typetest.ts
packages/rpc-transport/src/index.ts
packages/rpc-transport/src/json-rpc-config.ts
packages/rpc-transport/src/json-rpc-types.ts
packages/rpc-transport/src/json-rpc.ts
packages/rpc-transport/src/transports/http/__typetests__/http-transport-typetest.ts
packages/rpc-transport/src/transports/http/http-transport.ts
packages/rpc-transport/src/transports/transport-types.ts

This change introduces cluster-level transports as well as cluster-level JSON RPCs
that infer the cluster from the provided transport.

refactor(experimental): add cluster level API for transports

---

packages/rpc-transport/src/__typetests__/json-rpc-subscription-typetest.ts
packages/rpc-transport/src/json-rpc-config.ts
packages/rpc-transport/src/json-rpc-subscription.ts
packages/rpc-transport/src/json-rpc-types.ts
packages/rpc-transport/src/transports/transport-types.ts
packages/rpc-transport/src/transports/websocket/__typetests__/websocket-typetest.ts
packages/rpc-transport/src/transports/websocket/websocket-transport.ts

This change mirrors the first change in the stack, but for subscriptions.

refactor(experimental): add cluster level subscriptions API for transports

---

packages/library/src/__typetests__/create-rpc-subscriptions.ts
packages/library/src/rpc-websocket-autopinger.ts
packages/library/src/rpc-websocket-connection-sharding.ts
packages/library/src/rpc-websocket-transport.ts
packages/library/src/rpc.ts

This change adds the cluster-level APIs to the main library's subscriptions.

refactor(experimental): add cluster level subscriptions API for library

---

packages/codecs-data-structures/src/__tests__/scalar-enum-test.ts
packages/codecs-data-structures/src/__typetests__/scalar-enum-typetest.ts
packages/codecs-data-structures/src/scalar-enum.ts
packages/codecs-data-structures/tsconfig.json

This PR refactors the definition of a "Scalar Enum" in the context of codecs which unlocks stricter types and adds support for hybrid scalar enums (both numeric and lexical).
- The `ScalarEnum` type now simply defines the "lookup object" created by the `enum` constructor.
- The `ScalarEnumFrom<T>` and `ScalarEnumTo<T>` types describe the input/output to encode/decode respectively, given a `enum` constructor.
- The Scalar Enum `Encoder`, `Decoder` and `Codec` functions now use these types to create stronger type constraints. This means, TypeScript will now fail if we provide the wrong key or value for the enum.
- The `getScalarEnumStats` helper function was also updated to provide non-duplicated keys and values for the `enum` constructor. Whilst it was not an issue for full-numeric or …

refactor(experimental): refactor ScalarEnums in codecs

---

packages/signers/src/__tests__/account-signer-meta-test.ts
packages/signers/src/__tests__/fee-payer-signer-test.ts
packages/signers/src/account-signer-meta.ts
packages/signers/src/fee-payer-signer.ts
packages/signers/src/index.ts
packages/transactions/src/index.ts

The `@solana/signers` package allows us to store `TransactionSigners` inside instructions' account meta which can then be extracted in order to sign the transaction they belong to.
Signing transactions that way currently doesn't take the fee payer into account. It works most of the time as it is likely that the fee payer will end up being required as a signer inside one of the instructions. However, when that's not the case, the fee payer will have to manually sign the transaction on top of using the `signTransactionWithSigners` function.
This PR fixes that by storing the fee payer signer inside the transaction object, much like we do with the instruction account metas.
It offers a new `setTransactionFeePayerSigner` which, on top of adding the `feePayer` address, also add a …

refactor(experimental): store fee payer Signers in transactions

---

packages/transactions/README.md
packages/transactions/src/__tests__/instructions-test.ts
packages/transactions/src/instructions.ts

This PR adds the following two helper functions enabling users to add multiple instructions to their transaction within a single function call:
- `appendTransactionInstructions`
- `prependTransactionInstructions`
Additionally, it refactors the `appendTransactionInstruction` and `prependTransactionInstruction` functions such that they now delegate to their respective plural helper by passing an array with a single element.
Tests added.
README updated.
Fixes #2108.

refactor(experimental): add multiple instructions to transactions helpers

---

packages/compat/src/keypair.ts
packages/errors/src/__tests__/RPC_INTEGER_OVERFLOW-test.ts
packages/errors/src/codes.ts
packages/errors/src/context.ts
packages/errors/src/messages.ts
packages/keys/README.md
packages/keys/package.json
packages/keys/src/key-pair.ts
pnpm-lock.yaml

Adds a helper function that creates a crypto KeyPair from a 64-bytes secret key.

refactor(experimental): add createKeyPairFromBytes helper

---

packages/signers/src/keypair-signer.ts

Adds a helper method that create a `KeyPairSigner` from the 64-bytes of a secret key.

refactor(experimental): add createKeyPairSignerFromBytes helper

---

packages/rpc-core/src/rpc-methods/__tests__/get-leader-schedule-test.ts
packages/rpc-core/src/rpc-methods/__typetests__/get-leader-schedule-type-test.ts
packages/rpc-core/src/rpc-methods/__typetests__/get-supply-type-test.ts
packages/rpc-core/src/rpc-methods/getLeaderSchedule.ts
packages/rpc-core/src/rpc-methods/getSupply.ts

This change simply fixes a handful of incorrect RPC method signatures, as per
the RPC docs.
Stems from errors found in #2087.

refactor(experimental): fix a few RPC methods

---

packages/codecs-strings/package.json
packages/codecs-strings/src/__benchmarks__/run.ts
pnpm-lock.yaml

These should form a basis for refactoring work – to ensure that changes don't regress performance.
```shell
~/src/solana-web3.js-git/packages/codecs-strings$ pnpm benchmark
> @solana/codecs-strings@2.0.0-development benchmark /home/sol/src/solana-web3.js-git/packages/codecs-strings
> ./src/__benchmarks__/run.ts
Packages: +5
+++++
Progress: resolved 28, reused 5, downloaded 0, added 5, done
┌─────────┬─────────────────┬──────────┬────────────────────┬──────────┬─────────┐
│ (index) │    Task Name    │ ops/sec  │ Average Time (ns)  │  Margin  │ Samples │
├─────────┼─────────────────┼──────────┼────────────────────┼──────────┼─────────┤
│    0    │ 'Base58 decode' │ '61,775' │ 16187.51705202282  │ '±0.43%' │  30888  │
│    1    │ 'Base58 encode' │ '42,444' │ 23560.373047174093 │ '±0.38%' │ …
```

A benchmark suite for the base58 encoder

---

packages/codecs-strings/src/baseX.ts

No change in benchmarks.
```shell
cd packages/codecs-strings/
pnpm benchmark
```

Eliminate copy in baseX encoder

---

packages/codecs-strings/src/baseX.ts

No change in benchmarks.
```shell
cd packages/codecs-strings/
pnpm benchmark
```

Partition leading zeros in baseX in one step using regular expressions

---

packages/library/src/__tests__/airdrop-internal-test.ts
packages/library/src/__tests__/send-transaction-internal-test.ts
packages/library/src/airdrop-internal.ts
packages/library/src/airdrop.ts
packages/library/src/send-transaction-internal.ts
packages/library/src/send-transaction.ts

The goal of this PR is to make it abundantly clear what kind of transaction sender you're creating by renaming these to `{METHOD}Factory`. This will make them come up first in autocomplete when someone types, for instance, `sendAndConfirm`.
Closes #2120.

Rename all transaction/airdrop sender factories with the ‘Factory’ suffix

---

packages/library/src/send-transaction-internal.ts
packages/library/src/send-transaction.ts

Folks can use this to create a transaction sender that does not confirm the transaction.
Closes #2121

Export a non-confirming transaction sender factory

---

packages/rpc-subscriptions-api/src/index.ts

`BlockNotifications` is actually an unstable method. Move it to the unstable
API.

refactor(experimental): move block-notifications to unstable methods

---

packages/rpc-api/src/index.ts
packages/rpc/src/__typetests__/rpc-clusters-typetest.ts
packages/rpc/src/rpc.ts

Repair the type inference for `SolanaRpcMethodsMainnet` by eliminating the
`Omit<..>` from the type and relaxing some type conditionals in
`createSolanaRpc(..)`.
Closes #2164 
Note: This solves the type inference issue but not the speed of type resolution.
I'm noticing only about a 1 second hang when I type `.`.
What was the tool for testing this response time?

refactor(experimental): repair `SolanaRpcMethodsMainnet` type inference

---

packages/rpc-graphql/src/loaders/account.ts
packages/rpc-graphql/src/loaders/block.ts
packages/rpc-graphql/src/loaders/loader.ts
packages/rpc-graphql/src/loaders/program-accounts.ts
packages/rpc-graphql/src/loaders/transaction.ts

Add a `loadMany` function to the `Loader` interface, in order to set the stage
for future resolvers to be able to combine multiple fetches into one query
result.

refactor(experimental): graphql: add `loadMany` to loaders

---

packages/rpc-graphql/package.json
packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/index.ts
packages/rpc-graphql/src/loaders/__tests__/account-loader-test.ts
packages/rpc-graphql/src/loaders/account.ts
packages/rpc-graphql/src/loaders/loader.ts
packages/rpc-graphql/src/resolvers/__tests__/account-resolver-test.ts
pnpm-lock.yaml

So.... this batch loader works great!
However, my tests are super flaky with the timer manipulation.
Every 5-6 attempts, they all pass, but the other times I get a few failures.
It's always the same tests that fail, and they seem to be 1 less `fetchMock`
invocation than expected.
I think I'm missing something.

refactor(experimental): graphql: expand on batch loader for accounts

---

packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/context.ts
packages/rpc-graphql/src/loaders/__tests__/program-accounts-loader-test.ts
packages/rpc-graphql/src/loaders/account.ts
packages/rpc-graphql/src/loaders/coalescer.ts
packages/rpc-graphql/src/loaders/loader.ts
packages/rpc-graphql/src/loaders/program-accounts.ts
packages/rpc-graphql/src/resolvers/__tests__/program-accounts-resolver-test.ts
packages/rpc-graphql/src/resolvers/program-accounts.ts
packages/rpc-graphql/src/resolvers/resolve-info/account.ts
packages/rpc-graphql/src/resolvers/resolve-info/index.ts
packages/rpc-graphql/src/resolvers/resolve-info/program-accounts.ts
packages/rpc-graphql/src/schema/root.ts

Continue in the spirit of the previous commit, this time adding a request
coalescer to the `programAccounts` query, allowing for similar optimizations to
`account`, despite there being no batch RPC method for `getProgramAccounts`.

refactor(experimental): graphql: program accounts makeover

---

packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/loaders/__tests__/transaction-loader-test.ts
packages/rpc-graphql/src/loaders/coalescer.ts
packages/rpc-graphql/src/loaders/loader.ts
packages/rpc-graphql/src/loaders/transaction.ts
packages/rpc-graphql/src/resolvers/__tests__/transaction-resolver-test.ts
packages/rpc-graphql/src/resolvers/block.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/resolvers/resolve-info/index.ts
packages/rpc-graphql/src/resolvers/resolve-info/transaction.ts
packages/rpc-graphql/src/resolvers/transaction.ts
packages/rpc-graphql/src/resolvers/types.ts
packages/rpc-graphql/src/schema/instruction.ts
packages/rpc-graphql/src/schema/root.ts
packages/rpc-graphql/src/schema/transaction.ts
packages/rpc-graphql/src/schema/types.ts

Similar to the previous commit, adding a request coalescer for transactions.
However, here the schema is also modified to be much simpler, allowing for
`data` field queries directly - similar to accounts - and shedding any
unnecessary object structure from the RPC default.

refactor(experimental): graphql: transaction makeover

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/loaders/__tests__/block-loader-test.ts
packages/rpc-graphql/src/loaders/block.ts
packages/rpc-graphql/src/loaders/loader.ts
packages/rpc-graphql/src/resolvers/__tests__/block-resolver-test.ts
packages/rpc-graphql/src/resolvers/block.ts
packages/rpc-graphql/src/resolvers/resolve-info/block.ts
packages/rpc-graphql/src/resolvers/resolve-info/index.ts
packages/rpc-graphql/src/resolvers/resolve-info/transaction.ts
packages/rpc-graphql/src/resolvers/types.ts
packages/rpc-graphql/src/schema/block.ts
packages/rpc-graphql/src/schema/root.ts
packages/rpc-graphql/src/schema/types.ts

This commit updates the `block` schema to leverage the new transaction schema
laid out in the previous commit. It also adds the necessary request coalescer,
resolve info, and more to the block schema.

refactor(experimental): graphql: block makeover

---

packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/resolvers/__tests__/block-inputs-test.ts
packages/rpc-graphql/src/resolvers/types.ts

When working in the GraphQL playground, providing a raw integer will not parse
properly into the `Slot` type. This change fixes the `BigIntScalar` type to
accept raw integer and float inputs.

refactor(experimental): graphql: fix bigint inputs

---

packages/codecs-data-structures/src/__tests__/data-enum-test.ts
packages/codecs-data-structures/src/__tests__/struct-test.ts
packages/codecs-data-structures/src/__typetests__/data-enum-typetest.ts
packages/codecs-data-structures/src/__typetests__/struct-typetest.ts
packages/codecs-data-structures/src/data-enum.ts
packages/codecs-data-structures/src/struct.ts
packages/transactions/src/serializers/message.ts

This PR improves the type inferences of `getStructCodec` and `getDataEnumCodec` such that it becomes easier to create custom codecs using them.
Thank you @lithdew for raising this in #2159 and for providing a detailed explanation of the implementation.
Fixes #2159.

refactor(experimental): improve codec field and variant types

---

packages/errors/src/codes.ts
packages/errors/src/context.ts
packages/errors/src/messages.ts

Updates the links to the README in the `@solana/errors` package.

refactor(experimental): errors: fix `README` link

---

packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
packages/rpc/src/rpc-request-coalescer.ts

I learned today that it's wrong to synthesize an `AbortError` `DOMException` with an `AbortSignal's` `reason`. You should throw the `reason` directly.
See https://fetch.spec.whatwg.org/#deserialize-a-serialized-abort-reason

The request coalescer now throws the `AbortSignal's` `reason`

---

packages/rpc-transport-http/src/http-transport-headers.ts

```ts
createHttpTransport({
headers: {
'Proxy-Foo': 'Bar', // ERROR
'proxy-foo': 'Bar', // ERROR
'PROXY-FOO': 'Bar', // ERROR
'Sec-Foo': 'Bar', // ERROR
'sec-foo': 'Bar', // ERROR
'SEC-FOO': 'Bar', // ERROR
},
});
```

Forbid `Proxy-*` and `Sec-*` headers via TypeScript

---

packages/build-scripts/getBaseConfig.ts
packages/fetch-impl/package.json
packages/fetch-impl/src/__tests__/fetch-test.node.ts
packages/fetch-impl/src/index.node.ts
packages/rpc-transport-http/package.json
packages/rpc-transport-http/src/__tests__/http-transport-dispatcher-test.browser.ts
packages/rpc-transport-http/src/__tests__/http-transport-headers-test.ts
packages/rpc-transport-http/src/__tests__/http-transport-test.ts
packages/rpc-transport-http/src/http-transport.ts
packages/rpc/src/rpc-transport.ts
pnpm-lock.yaml

The current version of web3.js allows folks to supply what's called an ‘HTTP Agent.’ This is a class that mediates how network requests should be fetched. One example is to establish a connection pool for a given URL, and keep connections open for a time so that TLS/SSL negotiation doesn't have to be done on every request.
The new web3.js up until this point has punted on how to reintroduce this concept. In this PR we bring it back in the form of allowing callers to create transports with custom Undici `Dispatchers`.
It only works in Node. If you supply the `dispatcher_NODE_ONLY` property in non-Node environments you'll get a console warning that your config has been ignored.
I desperately wanted to avoid the situation in this PR, which was to create a config property on transports that's …

Allow devs to supply a dispatcher to the Node implementation of `fetch`

---

packages/fetch-impl/package.json
packages/fetch-impl/src/__benchmarks__/run.ts
pnpm-lock.yaml

The benchmark script just requests the `getLatestBlockhash` method 1024 times in parallel, and takes the average of 10 trials.
```shell
$ cd packages/fetch-impl/
$ pnpm benchmark https://api.devnet.solana.com/{API TOKEN FOR NO RATE LIMIT}
┌─────────┬───────────────────────────────────┬─────────┬────────────────────┬───────────┬─────────┐
│ (index) │ Task Name                         │ ops/sec │ Average Time (ns)  │ Margin    │ Samples │
├─────────┼───────────────────────────────────┼─────────┼────────────────────┼───────────┼─────────┤
│ 0       │ 'no dispatcher'                   │ '1'     │  548031484.6       │ '±49.40%' │ 10      │
│ 1       │ 'unlimited connections'           │ '0'     │ 4383004893.2       │ '±1.45%'  │ 10      │
│ 2       │ '16 connections'                  │ '0' …
```

Create benchmarks for tuning the Node transport

---

packages/webcrypto-ed25519-polyfill/src/secrets.ts

These errors are not so much Solana framework errors as they are designed to mimic the DOM API errors. Leave them as-is.

Remove coded error TODO from `@solana/webcrypto-ed25519-polyfill`

---

packages/errors/src/rpc-enum-errors.ts
packages/errors/src/transaction-error.ts

In a future PR when we add `InstructionError` the core mucking code is going to look exactly the same as this. Let's extract it to share with that function, down the line.
Addresses #2118.

Extract core RPC enum-error handling functionality

---

packages/errors/package.json
packages/errors/src/__typetests__/error-typetest.ts
pnpm-lock.yaml

In order to be able to add `SolanaError` to `@solana/addresses`, the
`devDependency` for `@solana/addresses` needs to be removed.

refactor(experimental): errors: remove cyclical dependency

---

packages/codecs-core/src/codec.ts
packages/codecs-core/src/reverse-codec.ts
packages/codecs-data-structures/src/boolean.ts
packages/codecs-data-structures/src/nullable.ts
packages/options/src/option-codec.ts

As mentioned in
[this PR comment](https://github.com/solana-labs/solana-web3.js/pull/2188#discussion_r1501789028),
if you need to provide some kind of "reason" or "message" to an error, it's
usually a smell.
Now that we have custom error codes and can perform proper error handling, we
can replace this mechanism for piping error messages (effectively "reasons") to
fixed codec assertions!
This change refactors out `message` from `assertIsFixed`. In a later commit,
I'll replace the thrown error with a coded `SolanaError` and add the necessary
`catch` statements downstream.

refactor(experimental): codecs: refactor `message` out of codec assertions

---

packages/codecs-numbers/src/u128.ts
packages/codecs-numbers/src/u64.ts

When working with `u64` and `u128` codecs, all range numerical values should be
`bigint`, since they are large, >8 byte numbers.
Simply flips the minimum range boundary to use `bigint`, for consistency.

refactor(experimental): codecs: use `bigint` for range values on `u64` and `u128`

---

packages/library-legacy/src/programs/stake.ts
packages/library-legacy/test/program-tests/stake.test.ts

When [this feature](https://github.com/solana-labs/solana/issues/33300) is activated, splitting a rent account will require that the split recipients' accounts are rent-exempt.
In this PR we give an opportunity, through the stake program client API, for callers to opt to fund the destination account.
```shell
cd packages/library-legacy/
TEST_LIVE=1 pnpm test:unit:node
```

fix: splitting a stake account now requires the splits to pay rent

---

package.json
packages/rpc-subscriptions-transport-websocket/src/__tests__/websocket-connection-test.ts
pnpm-lock.yaml

Otherwise blocked on https://github.com/romgain/jest-websocket-mock/issues/171.

Upgrade `mock-socket` to 9.3.1 and reenable test

---

packages/errors/src/__tests__/error-test.ts
packages/errors/src/__typetests__/error-typetest.ts
packages/errors/src/error.ts
packages/errors/tsconfig.json

The runtime has built-in support for ‘sub exceptions.’ You can read about it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause
> It is used when catching and re-throwing an error with a more-specific or useful error message in order to still have access to the original error.
This PR brings `cause` to `SolanaError` so that we can use it to rethrow errors under one umbrella error. Developers will have access to the inner error via `SolanaError#cause`.
The first error that will make use of this is the websocket close error, in the next PR.
```shell
```

`SolanaError` now supports the `cause` property

---

packages/rpc-subscriptions/src/cached-abortable-iterable.ts
packages/rpc-subscriptions/src/rpc-subscriptions-coalescer.ts
packages/rpc-subscriptions/src/rpc-subscriptions-connection-sharding.ts

This is the first step on the way to evicting invariant violation strings (error that should never happen, therefore would be nonsensical to build error catching around) from the production code.
Here we reorganize things so that in `__DEV__` mode the error has a message, but otherwise it gets stripped out.

Only get the cached abortable iterable factory cache error message in dev mode

---

packages/rpc/src/__tests__/rpc-integer-overflow-test.ts
packages/rpc/src/__typetests__/rpc-clusters-typetest.ts
packages/rpc/src/rpc-transport.ts
packages/rpc/src/rpc.ts

This PR changes the `createSolanaRpc` function so that it accepts a `ClusterUrl` as a first parameter and an optional config object as a second parameter.
This makes it much easier for 95% of RPC use-cases to get started with the library:
```ts
const rpc = createSolanaRpc("http://localhost:8899");
// Cluster-aware RPCs:
const rpc = createSolanaRpc(devnet("https://api.devnet.solana.com"));
const rpc = createSolanaRpc(testnet("https://api.testnet.solana.com"));
const rpc = createSolanaRpc(mainnet("https://api.mainnet-beta.solana.com"));
// With configs:
const rpc = createSolanaRpc("http://localhost:8899", {
headers: myHeaders,
dispatcher_NODE_ONLY: myDispatcher,
});
```
Additionally, this PR adds a `createSolanaRpcFromTransport` function that allows the remaining 5% of use-cases to …

refactor(experimental): add function to create a Solana RPC using only an URL

---

packages/rpc-subscriptions/src/__typetests__/rpc-subscriptions-clusters-typetest.ts
packages/rpc-subscriptions/src/rpc-subscriptions-transport.ts
packages/rpc-subscriptions/src/rpc-subscriptions.ts

This PR changes the `createSolanaRpcSubscriptions` and `createSolanaRpcSubscriptions_UNSTABLE` functions so that they accepts a `ClusterUrl` as a first parameter and an optional config object as a second parameter.
This makes it much easier for 95% of RPC Subscription use-cases to get started with the library:
```ts
const rpcSubscriptions = createSolanaRpcSubscriptions("ws://localhost:8899");
// Cluster-aware RPC Subscriptions:
const rpcSubscriptions = createSolanaRpcSubscriptions(devnet("ws://api.devnet.solana.com"));
const rpcSubscriptions = createSolanaRpcSubscriptions(testnet("ws://api.testnet.solana.com"));
const rpcSubscriptions = createSolanaRpcSubscriptions(mainnet("ws://api.mainnet-beta.solana.com"));
// With configs:
const rpcSubscriptions = …
```

refactor(experimental): add function to create Solana RPC Subscriptions using only an URL

---

.github/workflows/cicd.yml
.github/workflows/pull-requests.yml

I'm pretty sure that my validator start/stop script (for Jest) is racey, and that most of the CI flakiness is because of:
* one test releasing its lock on the test validator
* a second test ‘getting’ the lock on that same test validator
* the validator going down anyway
Let's just start the thing when the CI run starts, and stop it when it's done.

Start the test validator at the beginning of a CI run, and keep it up until the end

---

packages/errors/src/codes.ts

Now that all `SolanaErrors` have been converted, this stack massages the error names in order to use consistent naming conventions.
This first PR adds guidelines to the error codes docblocks and visually separates the groups a bit more.

refactor(experimental): add guidelines to error codes

---

packages/errors/src/codes.ts

Move the invariant error range to `99000000` so that they are listed after all other groups.

refactor(experimental): move Invariant errors range to the end

---

packages/errors/src/codes.ts

Creates an account error group with its own code range. They will be renamed properly in a subsequent PR of this stack.

refactor(experimental): group Account errors

---

.github/workflows/commit-lint.yml
.mergify.yml

Automerge was largely busted because it was doing a check for the CI step ‘Validate Commit Message.’ We don't do that step anymore, except on changes to `library-legacy/`

chore: get automerge working again

---

packages/library-legacy/src/programs/vote.ts

I would like to use the `UpdateValidatorIdentity` instruction of VoteProgram in TS code and it is not available in the current web3.js library.
https://github.com/solana-labs/solana/blob/v1.18.4/sdk/program/src/vote/instruction.rs#L381

[vote-program] adding instruction update validator identity

---

packages/codecs-data-structures/README.md

Couple of small fixes in the codecs documentation since the latest changes that were made with enums.
Namely, the type parameter `T` in `getDataEnum<T>` no longer refers to the data enum type but to the variants to be inferred.
Since this is just a small README change, I don't think it warrants a changeset.

refactor(experimental): Fix codecs-data-structure documentation

---

packages/rpc-api/src/__tests__/get-fee-for-message-test.ts
packages/rpc-api/src/__tests__/send-transaction-test.ts
packages/rpc-api/src/__tests__/simulate-transaction-test.ts

You can get into some pretty weird situations in tests if all of the following are true:
- The test validator just started up
- You fetch a blockhash using `finalized` commitment before the first root has been made
- You're testing something to do with fees
In cases like this, you'll get the first blockhash ever, which basically lets you land transactions without paying a fee. If your test exercises fee-related exceptions, it just might fail.
Fee-related tests in the next PR work.

Use matching commitment when fetching blockhashes in tests

---

packages/errors/src/index.ts
packages/errors/src/json-rpc-error.ts
packages/errors/src/rpc-enum-errors.ts
packages/errors/src/stack-trace.ts
packages/rpc-subscriptions/src/rpc-integer-overflow-error.ts
packages/rpc/src/rpc-integer-overflow-error.ts

This is used in enough places now that I feel it necessary to extract it into `@solana/errors`. This utility calls `Error.captureStackTrace()` for you, but only if it exists in the runtime.

Extract the stack trace capture code into `@solana/errors`

---

packages/library-legacy/src/message/legacy.ts
packages/library-legacy/src/transaction/legacy.ts
packages/library-legacy/src/validator-info.ts

I noticed many places where we:
1. Read a section of bytes from an array, from index A-B
2. Overwrite the entire byte array with the bytes from B onward
This is done in two steps using `Array#slice` twice. What we're looking for here is the mutative, one-step `Array#slice`.
CI run

fix: splice bytes in-place when reading buffers

---

packages/codecs-core/README.md
packages/codecs-core/src/__tests__/__setup__.ts
packages/codecs-core/src/__tests__/offset-codec-test.ts
packages/codecs-core/src/__tests__/pad-codec-test.ts
packages/codecs-core/src/__typetests__/pad-codec-typetest.ts
packages/codecs-core/src/pad-codec.ts
packages/codecs/README.md

This PR adds new `padLeftCodec` and `padRightCodec` helper functions. See copy/pasted documentation below:
---
The `padLeftCodec` and `padRightCodec` helpers can be used to add padding to the left or right of a given codec. They accept an `offset` number that tells us how big the padding should be.
```ts
const getLeftPaddedCodec = () => padLeftCodec(getU16Codec(), 4);
getLeftPaddedCodec().encode(0xffff);
// 0x00000000ffff
//   |       └-- Our encoded u16 number.
//   └-- Our 4-byte padding.
const getRightPaddedCodec = () => padRightCodec(getU16Codec(), 4);
getRightPaddedCodec().encode(0xffff);
// 0xffff00000000
//   |   └-- Our 4-byte padding.
//   └-- Our encoded u16 number.
```
Note that both the `padLeftCodec` and `padRightCodec` functions are simple wrappers around the `offsetCodec` …

refactor(experimental): add padLeftCodec and padRightCodec helpers to @solana/codecs-core

---

packages/rpc-types/src/__tests__/blockhash-test.ts
packages/rpc-types/src/blockhash.ts

Similar to the `AddressCodec` in `@solana/addresses`, we could use a typed
32-byte codec that can chain base64 encoding into its serialization, for
`Blockhash`.
Here I've added the same kind of combined codec as `getAddressCodec` to the
`blockhash` type in `@solana/rpc-types`.
Note: The implementation is almost identical, with the exception of the types,
and the tests are exactly the same as `getAddressCodec`.
I've also added some more assertions to `blockhash` to keep the API consistent.

refactor(experimental): add blockhash codec and type assertions

---

packages/rpc-types/package.json
packages/rpc-types/src/__tests__/lamports-test.ts
packages/rpc-types/src/lamports.ts
pnpm-lock.yaml

Similar to the commit before it, this change adds a codec to `@solana/rpc-types`
for working with the `LamportsUnsafeBeyond2Pow53Minus1` opaque type.
It's not enough to just use the `u64Codec` directly, since TypeScript won't just
infer `LamportsUnsafeBeyond2Pow53Minus1` from a `bigint`. So we have to set up a
`mapCodec` for this coercion.

refactor(experimental): add lamports codec

---

packages/sysvars/package.json
packages/sysvars/src/__tests__/__setup__.ts
packages/sysvars/src/__tests__/clock-test.ts
packages/sysvars/src/__tests__/sysvar-test.ts
packages/sysvars/src/__typetests__/sysvar-typetest.ts
packages/sysvars/src/clock.ts
packages/sysvars/src/index.ts
packages/sysvars/src/sysvar.ts
pnpm-lock.yaml

This commit introduces the `Clock` sysvar to the `@solana/sysvars` package.
It also introduces the `fetchSysvar` API, for fetching sysvar accounts.

refactor(experimental): sysvars package: clock

---

packages/sysvars/src/__tests__/epoch-schedule-test.ts
packages/sysvars/src/__tests__/sysvar-test.ts
packages/sysvars/src/__typetests__/sysvar-typetest.ts
packages/sysvars/src/epoch-schedule.ts
packages/sysvars/src/index.ts
packages/sysvars/src/sysvar.ts

This commit introduces the `EpochSchedule` sysvar to the `@solana/sysvars` package.

refactor(experimental): sysvars package: epoch schedule

---

packages/sysvars/src/__tests__/recent-blockhashes-test.ts
packages/sysvars/src/__tests__/sysvar-test.ts
packages/sysvars/src/__typetests__/sysvar-typetest.ts
packages/sysvars/src/index.ts
packages/sysvars/src/recent-blockhashes.ts
packages/sysvars/src/sysvar.ts

This commit introduces the `RecentBlockhashes` sysvar to the `@solana/sysvars` package.

refactor(experimental): sysvars package: recent blockhashes

---

packages/sysvars/src/__tests__/rent-test.ts
packages/sysvars/src/__tests__/sysvar-test.ts
packages/sysvars/src/__typetests__/sysvar-typetest.ts
packages/sysvars/src/index.ts
packages/sysvars/src/rent.ts
packages/sysvars/src/sysvar.ts

This commit introduces the `Rent` sysvar to the `@solana/sysvars` package.

refactor(experimental): sysvars package: rent

---

packages/sysvars/src/__tests__/slot-hashes-test.ts
packages/sysvars/src/__tests__/sysvar-test.ts
packages/sysvars/src/__typetests__/sysvar-typetest.ts
packages/sysvars/src/index.ts
packages/sysvars/src/slot-hashes.ts
packages/sysvars/src/sysvar.ts

This commit introduces the `SlotHashes` sysvar to the `@solana/sysvars` package.

refactor(experimental): sysvars package: slot hashes

---

packages/sysvars/src/__tests__/stake-history-test.ts
packages/sysvars/src/__tests__/sysvar-test.ts
packages/sysvars/src/__typetests__/sysvar-typetest.ts
packages/sysvars/src/index.ts
packages/sysvars/src/stake-history.ts
packages/sysvars/src/sysvar.ts

This commit introduces the `StakeHistory` sysvar to the `@solana/sysvars` package.

refactor(experimental): sysvars package: stake history

---

packages/library/README.md

Annoyingly, prettier changes make it difficult to review but essentially this PR remove the "Program Client" section from "Going Forward" and add the following documentation to the documented features.
---
Writing JavaScript clients for on-chain programs has been done manually up until now. Without an IDL for some of the native programs, this process has been necessarily manual and has resulted in clients that lag behind the actual capabilities of the programs themselves.
We think that program clients should be *generated* rather than written. Developers should be able to write Rust programs, compile the program code, and generate all of the JavaScript client-side code to interact with the program.
We use [Kinobi](https://github.com/metaplex-foundation/kinobi) to represent Solana programs …

refactor(experimental): update program client documentation in library README

---

packages/codecs-core/src/index.ts

I'm an idiot and forgot to export the file on my previous PR.

refactor(experimental): export missing pad-codec file

---

packages/rpc/src/rpc-request-coalescer.ts

There is a bug in the version of `undici` that ships with Node <21 that throws an unhandled exception when the `reason` property of an `AbortSignal` is a non-object. The request coalescer hits this bug because it uses a `Symbol` to differentiate between an internal abort and a user abort. `undici` chokes on that `Symbol`.
In this PR we capitulate and change it to an object.
See https://github.com/nodejs/undici/pull/2597 for more detail about the bug.
In every version of Node from 18-21, `undici` handles an object correctly.
```
~/src/solana-web3.js-git/packages/rpc$ sudo n 21 && pnpm node
copying : node/21.7.1
installed : v21.7.1 (with npm 10.5.0)
Welcome to Node.js v21.7.1.
Type ".help" for more information.
> await fetch('http://localhost', { signal: AbortSignal.abort({}) });
Uncaught …
```

Fix a bug in Node <21 that prevented the normal operation of the request coalescer

---

.changeset/heavy-students-relax.md
packages/codecs-data-structures/src/data-enum.ts
packages/codecs-data-structures/src/struct.ts
packages/codecs-data-structures/src/utils.ts

This PR aims to solve #2295 by wrapping codec type mappings with the suggested `DrainOuterGeneric`.
The TypeScript diagnostics on a complex codec — using both data enums and structs — changes as follows. As you can see we get a significant reduction of instantiations.
```
Files:                         204 -> 205
Lines of Library:            38131 -> 38131
Lines of Definitions:        52284 -> 52300
Lines of TypeScript:            81 -> 81
Lines of JavaScript:             0 -> 0
Lines of JSON:                   0 -> 0
Lines of Other:                  0 -> 0
Identifiers:                 92492 -> 92518
Symbols:                    111465 -> 111877
Types:                       55305 -> 55390
Instantiations:             603991 -> 362113    // -40%
Memory used:               187111K -> 189767K …
```

refactor(experimental): use DrainOuterGeneric helper on codec type mappings

---

.changeset/green-experts-hang.md
packages/codecs-data-structures/README.md
packages/codecs-data-structures/src/__tests__/tuple-test.ts
packages/codecs-data-structures/src/__typetests__/tuple-typetest.ts
packages/codecs-data-structures/src/map.ts
packages/codecs-data-structures/src/tuple.ts

This PR follows the footsteps of https://github.com/solana-labs/solana-web3.js/pull/2181 which improved the type inferences of `getStructCodec` and `getDataEnumCodec` by inferring the types from the provided codecs instead of inferring the other way around.
This PR does the same with the `getTupleCodec` and also makes use of the `DrainOuterGeneric` helper from the previous PR to reduce the amount of instantiations TypeScript does when resolving the codec types.

refactor(experimental): improve getTupleCodec type inferences

---

.changeset/wild-lobsters-kick.md
packages/addresses/src/program-derived-address.ts
packages/addresses/src/public-key.ts
packages/assertions/src/__tests__/subtle-crypto-test.ts
packages/assertions/src/subtle-crypto.ts
packages/keys/src/signatures.ts

`assertKeyGenerationIsAvailable()` definitely needs to be async because it feature-detects `Ed25519`. These other assertions don't seem to need to be async though; they just test for the _presence_ of a function.
Unless there's a good reason to yield the loop here, we should probably just make these checks sync for performance.
```
pnpm turbo test:typecheck test:unit:node test:unit:browser
```

Convert `SubtleCrypto` assertion methods to non-async

---

packages/keys/package.json
packages/keys/src/__benchmarks__/run.ts
pnpm-lock.yaml

Node LTS (20)
```
┌─────────┬───────────────────┬──────────┬───────────────────┬──────────┬─────────┐
│ (index) │ Task Name         │ ops/sec  │ Average Time (ns) │ Margin   │ Samples │
├─────────┼───────────────────┼──────────┼───────────────────┼──────────┼─────────┤
│ 0       │ 'generateKeyPair' │ '10,138' │ 98630.77218934878 │ '±2.25%' │ 5070    │
│ 1       │ 'signBytes'       │ '14,355' │ 69658.12245750854 │ '±2.16%' │ 7178    │
│ 2       │ 'verifySignature' │ '6,735'  │ 148476.5546318311 │ '±1.25%' │ 3368    │
└─────────┴───────────────────┴──────────┴───────────────────┴──────────┴─────────┘
```
Node 21
```
┌─────────┬───────────────────┬──────────┬────────────────────┬──────────┬─────────┐
│ (index) │ Task Name         │ ops/sec  │ Average Time (ns)  │ Margin   │ Samples │ …
```

A set of benchmarks for `@solana/keys`

---

.changeset/metal-radios-switch.md
packages/errors/package.json
packages/errors/src/__tests__/context-test.ts
packages/errors/src/__tests__/message-formatter-test.ts
packages/errors/src/cli.ts
packages/errors/src/context.ts
packages/errors/src/message-formatter.ts

Biggest reason for doing this is that terminal escaping is hard. Base64 is guaranteed not to have any problematic characters in it.
```shell
~/src/solana-web3.js-git/packages/errors$ npx . decode 2800000 'YWN0dWFsTGVuZ3RoPTM0NQ=='
[Decoded] Solana error code #2800000
- Expected base58 encoded address to decode to a byte array of length 32. Actual length: 345.
[Context]
{
"actualLength": "345"
}
```

Rewrite the error context encoder using base64 strings

---

package.json
patches/jest-runner-prettier@1.0.0.patch
pnpm-lock.yaml

I completely forgot about https://github.com/keplersj/jest-runner-prettier/issues/586 and this has been broken for a while.
This is why I love `pnpm`
```shell
pnpm patch jest-runner-prettier
pnpm patch-commit '/tmp/67d6a1a8e116289cd91a5e6eeb4f413d'
```
Break formatting in a file. `pnpm test:prettier`. Finally it registers.

Patch `jest-runner-prettier` to work with Prettier 3

---

packages/compat/package.json
packages/library-legacy-sham/package.json
packages/rpc-types/package.json
packages/sysvars/package.json
packages/transactions/package.json
pnpm-lock.yaml

Discovered these by running `compile:js` in each individual package, doing a `git clean -dfx .` between each.

Move dependencies out of `devDependencies` where they are used in the implementation

---

.changeset/breezy-items-reflect.md
packages/errors/README.md
packages/errors/src/__tests__/message-formatter-test.ts
packages/errors/src/message-formatter.ts

```
cd packages/errors/
pnpm turbo compile:js
npx . decode -- -32003
[Decoded] Solana error code #-32003
- Transaction signature verification failure
```
Closes #2357.

Negative error codes now get decoded correctly by the production error decoder

---

turbo.json

So many logs.
How would you folks feel about Turborepo showing _nothing_ unless there's an error?
```
• Packages in scope: @solana/accounts, @solana/addresses, @solana/assertions, @solana/build-scripts, @solana/codecs, @solana/codecs-core, @solana/codecs-data-structures, @solana/codecs-numbers, @solana/codecs-strings, @solana/compat, @solana/crypto-impl, @solana/errors, @solana/functional, @solana/instructions, @solana/keys, @solana/options, @solana/programs, @solana/rpc, @solana/rpc-api, @solana/rpc-graphql, @solana/rpc-parsed-types, @solana/rpc-spec, @solana/rpc-spec-types, @solana/rpc-subscriptions, @solana/rpc-subscriptions-api, @solana/rpc-subscriptions-spec, @solana/rpc-subscriptions-transport-websocket, @solana/rpc-transformers, @solana/rpc-transport-http, @solana/rpc-types, …
```

Show no Turbo logs except when there is an error

---

turbo.json

OK, this was a bit extreme, I guess. Also it disables it in CI, which seem bad.
This reverts commit 8af5427055d0a858e02061604f39907151778c01.

Revert "Show no Turbo logs except when there is an error (#2366)"

---

packages/signers/src/fee-payer-signer.ts
packages/transactions/src/blockhash.ts
packages/transactions/src/durable-nonce.ts
packages/transactions/src/fee-payer.ts
packages/transactions/src/instructions.ts
packages/transactions/src/unsigned-transaction.ts

This comment was orphaned when `getUnsignedTransaction()` was extracted

Move comments about signature busting to the callsites that bust the signatures

---

.changeset/violet-brooms-report.md
packages/codecs-data-structures/README.md
packages/codecs-data-structures/src/__tests__/data-enum-test.ts
packages/codecs-data-structures/src/__typetests__/data-enum-typetest.ts
packages/codecs-data-structures/src/data-enum.ts

This PR adds support for custom discriminator properties for `getDataEnumCodecs`.
```ts
// Before.
const codec = getDataEnumCodec([
['click', getStructCodec([[['x', u32], ['y', u32]]])],
['keyPress', getStructCodec([[['key', u32]]])]
]);
codec.encode({ __kind: 'click', x: 1, y: 2 });
codec.encode({ __kind: 'keyPress', key: 3 });
// After.
const codec = getDataEnumCodec([
['click', getStructCodec([[['x', u32], ['y', u32]]])],
['keyPress', getStructCodec([[['key', u32]]])]
], { discriminator: 'event' });
codec.encode({ event: 'click', x: 1, y: 2 });
codec.encode({ event: 'keyPress', key: 3 });
```
Note that, to make this work, this PR updates a few exported types such as `GetDataEnumKind` or `GetDataEnumKindContent` which is used by Kinobi. I'll make sure to have a PR ready on Kinobi's side …

refactor(experimental): support custom discriminator property for getDataEnumCodec

---

packages/rpc-subscriptions/src/__typetests__/rpc-subscriptions-clusters-typetest.ts
packages/rpc/src/__typetests__/rpc-clusters-typetest.ts

Whilst working on this stack I realised I used the word `[DEFINE]` in comments to mimic the Jest structure but what I meant to write was actually `[DESCRIBE]`. This PR fixes this.

refactor(experimental): nit: rename define to describe

---

pnpm-lock.yaml

Closes:
1. https://github.com/solana-labs/solana-web3.js/security/dependabot/83
2. https://github.com/solana-labs/solana-web3.js/security/dependabot/79
3. https://github.com/solana-labs/solana-web3.js/security/dependabot/80

chore: reinstall `mockttp` to bump all dependencies

---

pnpm-lock.yaml

Resolves https://github.com/solana-labs/solana-web3.js/security/dependabot/82.

chore: update `wait-on`

---

packages/library-legacy-sham/src/public-key.ts
packages/library-legacy-sham/src/versioned-transaction.ts
packages/transactions/src/__tests__/compile-transaction-test.ts
packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/__tests__/new-compile-transaction-test.ts
packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/__typetests__/transaction-typetests.ts
packages/transactions/src/compile-transaction.ts
packages/transactions/src/index.ts
packages/transactions/src/message.ts
packages/transactions/src/new-compile-transaction.ts
packages/transactions/src/serializers/__tests__/transaction-test.ts
packages/transactions/src/signatures.ts

This PR is the new bottom of the stack for splitting unsigned and signed transaction types.
I realised that #2387 is doing too much, by compiling the message and also handling signatures. This PR splits out the functionality to compile a transaction without any signing functionality.
It adds the `NewTransaction` type in `new-compile-transaction`. Eventually this will just be the `Transaction` type. It adds a new function `compileTransactionMessage` which takes a `CompilableTransaction` (will eventually be `CompilableTransactionMessage`) and returns a `NewTransaction`. This contains the compiled message bytes and an ordered map of signer address -> null signature.
I suggest that we split this from signing completely, you compile first with this function and then you partial sign/sign the …

Add support for compiling a TransactionMessage to a new Transaction type

---

packages/codecs-core/src/__tests__/codec-test.ts
packages/codecs-core/src/__tests__/combine-codec.ts
packages/codecs-core/src/__tests__/map-codec-test.ts
packages/codecs-core/src/__tests__/reverse-codec-test.ts
packages/codecs-core/src/assertions.ts
packages/codecs-core/src/bytes.ts
packages/codecs-core/src/codec.ts
packages/codecs-core/src/fix-codec.ts
packages/codecs-core/src/index.ts
packages/codecs-core/src/map-codec.ts
packages/codecs-core/src/offset-codec.ts
packages/codecs-core/src/readonly-uint8array.ts
packages/codecs-core/src/reverse-codec.ts
packages/codecs-data-structures/src/array.ts
packages/codecs-data-structures/src/bytes.ts
packages/codecs-data-structures/src/discriminated-union.ts
packages/codecs-data-structures/src/nullable.ts
packages/codecs-data-structures/src/struct.ts
packages/codecs-data-structures/src/tuple.ts
packages/codecs-data-structures/src/unit.ts
packages/codecs-numbers/src/short-u16.ts
packages/codecs-numbers/src/utils.ts
packages/codecs-strings/src/string.ts
packages/options/src/option-codec.ts
packages/sysvars/src/slot-history.ts

This PR adds the proposed `ReadonlyUint8Array` type to `codecs-core`. The `Decoder` interface is modified to allow decoding from a `ReadonlyUint8Array | Uint8Array`. This will allow us to use `ReadonlyUint8Array` for various byte encodings, while still being able to decode them as normal byte arrays.
The only place where I needed to add an extra copy is in `reverseCodec`, which was reversing the input bytes in place. It now creates and reverses a new Uint8Array from the input bytes. 
Addresses #2362.

Add ReadonlyUint8Array to codecs + allow decoding from it

---

packages/keys/src/signatures.ts
packages/transactions/src/new-compile-transaction.ts

This PR adds a shared `ReadonlyUint8Array` type and uses it for the input to `signBytes`. This will let us use it as the type of `messageBytes` in a signed transaction.
I haven't updated the sign output yet because I don't think it'll be necessary for my work and it'd be a larger change, but we probably should migrate more to readonly over time. 
See https://github.com/solana-labs/solana-web3.js/pull/2387#discussion_r1542038173
Addresses #2362.

Use readonly uint8array for sign input

---

packages/codecs-data-structures/README.md
packages/codecs-data-structures/src/__tests__/discriminated-union-test.ts
packages/codecs-data-structures/src/discriminated-union.ts
packages/errors/src/context.ts

This PR changes the custom values supported by `getDiscriminatedUnionCodec` from:
```ts
type DiscriminatorValue = number | string | symbol;
```
to:
```ts
type DiscriminatorValue = bigint | boolean | number | string | null | undefined;
```
Note that:
- We are dropping the `symbol` type since TypeScript doesn't make any distinctions between different symbols (i.e. `Symbol('A') | Symbol('B')` is typed as `symbol | symbol`).
- These values are now consistent with the new `getLiteralUnionCodec`.

refactor(experimental): support more scalar values in getDiscriminatedUnionCodec

---

.changeset/chatty-flies-end.md
packages/codecs-core/README.md
packages/codecs-core/src/__tests__/prefix-codec-test.ts
packages/codecs-core/src/__typetests__/prefix-codec-typetest.ts
packages/codecs-core/src/index.ts
packages/codecs-core/src/prefix-codec.ts
packages/codecs-data-structures/src/__tests__/bytes-test.ts
packages/codecs-data-structures/src/bytes.ts
packages/codecs-strings/src/string.ts
packages/codecs/README.md

This PR adds a new `prefixCodec` primitive to `@solana/codecs-core`. This primitives accepts any codec and prefixes its size using a `NumberCodec` provided as a second argument.
For instance:
```ts
const codec = prefixCodec(getBase58Codec(), getU32Codec());
codec.encode('hello world');
// 0x0b00000068656c6c6f20776f726c64
//   |       └-- Our encoded base-58 string.
//   └-- Our encoded u32 size prefix.
```
This PR also updates the `getStringCodec` and `getBytesCodec` as they can now use the `prefixCodec` primitive to simplify their internal logic.
P.S.: Now that `getStringCodec` and `getBytesCodec` are simple aggregator of `fixCodec` and `prefixCodec`, we should consider removing them or adjusting them further. (Pros: no default values => better tree-shakeability, Cons: slightly less …

refactor(experimental): add prefixCodec to @solana/codecs-core

---

packages/codecs-data-structures/src/__tests__/discriminated-union-test.ts
packages/codecs-data-structures/src/discriminated-union.ts

This PR refactors the implementation of `getDiscriminatedUnionCodec` (without changing its API or behaviour) so that it uses the new `getUnionCodec` helper under the hood.

refactor(experimental): refactor getDiscriminatedUnionCodec by using new getUnionCodec primitive

---

packages/codecs-data-structures/src/__tests__/nullable-test.ts
packages/codecs-data-structures/src/nullable.ts
packages/options/package.json
packages/options/src/__tests__/option-codec-test.ts
packages/options/src/option-codec.ts
pnpm-lock.yaml

This PR refactors the implementation of `getNullableCodec` and `getOptionCodec` so they use the new `getUnionCodec` internally.

refactor(experimental): refactor getNullableCodec and getOptionCodec to use getUnionCodec

---

.changeset/silly-months-happen.md
packages/codecs-data-structures/README.md
packages/codecs-data-structures/src/__tests__/bytes-test.ts
packages/codecs-data-structures/src/__typetests__/bytes-typetest.ts
packages/codecs-data-structures/src/bytes.ts
packages/codecs-data-structures/src/zeroable-nullable.ts
packages/options/src/zeroable-option-codec.ts
packages/transactions/src/serializers/instruction.ts
packages/transactions/src/serializers/transaction.ts

This PR removes the size option of `getBytesCodec`.
The `getBytesCodec` function now always returns a `VariableSizeCodec` that uses as many bytes as necessary to encode and/or decode byte arrays. In order to fix or prefix the size of a `getBytesCodec`, we may now use the `fixCodecSize` or `prefixCodecSide` accordingly. Here are some examples:
```ts
// Before.
getBytesCodec(); // Variable.
getBytesCodec({ size: 5 }); // Fixed.
getBytesCodec({ size: getU16Codec() }); // Prefixed.
// After
getBytesCodec(); // Variable.
fixCodecSize(getBytesCodec(), 5); // Fixed.
prefixCodecSize(getBytesCodec(), getU16Codec()); // Prefixed.
```
This has the following advantages:
- It avoids unnecessary API repetition.
- It makes the codec API more composable and more predicable — there is no longer two ways …

refactor(experimental): remove the size option of getBytesCodec

---

.changeset/famous-buttons-switch.md
packages/codecs-core/README.md
packages/codecs-numbers/README.md
packages/codecs-numbers/src/__tests__/f32-test.ts
packages/codecs-numbers/src/__tests__/f64-test.ts
packages/codecs-numbers/src/__tests__/i128-test.ts
packages/codecs-numbers/src/__tests__/i16-test.ts
packages/codecs-numbers/src/__tests__/i32-test.ts
packages/codecs-numbers/src/__tests__/i64-test.ts
packages/codecs-numbers/src/__tests__/u128-test.ts
packages/codecs-numbers/src/__tests__/u16-test.ts
packages/codecs-numbers/src/__tests__/u32-test.ts
packages/codecs-numbers/src/__tests__/u64-test.ts
packages/codecs-numbers/src/common.ts
packages/codecs-numbers/src/utils.ts

This PR uses capitalised variant names for the `Endian` enum in order to make the it more consistent with other enums in the library.
```ts
// Before.
Endian.BIG;
Endian.LITTLE;
// After.
Endian.Big;
Endian.Little;
```

refactor(experimental): nit: rename Endian enum variants

---

.changeset/tricky-fishes-pull.md
packages/library-legacy/src/connection.ts
packages/library-legacy/test/connection.test.ts
packages/rpc-transformers/package.json
packages/rpc-transformers/src/__tests__/params-transformer-test.ts
packages/rpc-transformers/src/params-transformer.ts
pnpm-lock.yaml

There's a bug in the `sendTransaction` RPC method where, when bypassing preflight, we nevertheless materially use the value of `preflightCommitment` to determine how to behave when sending the transaction.
If you supply _nothing_ – as you might think appropriate when _skipping_ preflight – then the default of `finalized` will be used. Far from irrelevant, such a value can actually affect the retry behaviour of the send-transaction-service (STS). Read https://github.com/anza-xyz/agave/pull/483 for more detail.
In this PR, we try to get ahead of https://github.com/anza-xyz/agave/pull/483 by setting this value to `processed` in the client. Until the server PR is deployed widely, this should cover those who choose to upgrade
Addresses https://github.com/anza-xyz/agave/issues/479
```
pnpm …
```

fix: downshift `preflightCommitment` to `processed` when bypassing preflight checks

---

packages/library/package.json
packages/library/src/index.ts
packages/transaction-messages/src/create-transaction-message.ts
packages/transaction-messages/src/index.ts
packages/transaction-messages/src/transaction-message.ts
pnpm-lock.yaml

Renamed TransactionVersion to NewTransactionVersion to avoid a clash with the transactions export
This will ensure that going forward there are no type duplicates between transactions and transaction-messages as I copy things over
I'll continue to add the `New` prefix and keeping existing code to make this non-destructive until everything is fully moved over

Add transaction-messages as a dependency of library + re-export

---

.changeset/short-toes-perform.md
packages/codecs-data-structures/src/__tests__/boolean-test.ts
packages/codecs-data-structures/src/__typetests__/boolean-typetest.ts
packages/codecs-data-structures/src/boolean.ts

Currently, whilst the TypeScript signature of `getBooleanCodec` suggest that we can use `VariableSizeCodecs` to define the size of the boolean, its implementation actually asserts against it.
This PR fixes this by removing this assertion, improving the function signature slightly and adding more tests for these scenarios.

refactor(experimental): allow variable-size number codecs in getBooleanCodec

---

packages/transaction-messages/package.json
packages/transaction-messages/src/codecs/__tests__/address-table-lookup-test.ts
packages/transaction-messages/src/codecs/address-table-lookup.ts
packages/transaction-messages/src/codecs/index.ts
packages/transaction-messages/src/compile/__tests__/address-table-lookups-test.ts
packages/transaction-messages/src/compile/address-table-lookups.ts
packages/transaction-messages/src/compile/index.ts
packages/transaction-messages/src/index.ts
packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/decompile-transaction.ts
packages/transactions/src/message.ts
packages/transactions/src/serializers/message.ts
pnpm-lock.yaml

This PR moves the logic to compile address lookup tables, and the associated codec, into transaction-messages

Move address table lookup compile + codec into transaction-messages

---

packages/transaction-messages/src/compile/__tests__/static-accounts-test.ts
packages/transaction-messages/src/compile/index.ts
packages/transaction-messages/src/compile/static-accounts.ts
packages/transactions/src/__tests__/message-test.ts
packages/transactions/src/message.ts

Again no codec to move since they just compile to an array of addresses

move static accounts compile into transaction-messages

---

packages/transaction-messages/src/codecs/__tests__/transaction-version-test.ts
packages/transaction-messages/src/codecs/index.ts
packages/transaction-messages/src/codecs/transaction-version.ts
packages/transactions/src/serializers/message.ts

This is the last piece before we can move compileMessage over + its codec

Move transaction-version codec to transaction-messages

---

packages/transactions/src/codecs/__tests__/signatures-encoder-test.ts
packages/transactions/src/codecs/__tests__/transaction-codec-test.ts
packages/transactions/src/codecs/signatures-encoder.ts
packages/transactions/src/codecs/transaction-codec.ts
packages/transactions/src/transaction.ts

This PR adds an encoder for the `NewTransaction` type. It concatenates the signatures (encoder added in parent PR) and the message bytes.
A future PR will add a decoder.

Add an encoder for the new transaction type

---

packages/compat/package.json
packages/compat/src/__tests__/transaction-test.ts
packages/compat/src/__typetests__/transaction-typetests.ts
packages/compat/src/transaction.ts
packages/transactions/src/codecs/transaction-codec.ts
pnpm-lock.yaml

This PR refactors the compat conversion from old web3js transactions to convert to the new Transaction type.
This is a massive simplification because it no longer needs to decompile the transaction - it just needs to include the serialized message bytes and convert the signatures. We already have helpers to decompile the transaction message if required, so there's no need to duplicate that here.

Refactor compat to convert to new transaction type

---

packages/transaction-messages/src/codecs/__tests__/message-test.ts
packages/transaction-messages/src/codecs/index.ts
packages/transaction-messages/src/codecs/message.ts
packages/transaction-messages/src/index.ts

*he sighs*
I forgot to export the new compiled transaction message codec, which is quite unhelpful
But the function names (`getCompiledMessageEncoder` etc) clash with the transactions serializer. So I've renamed them `getCompiledTransactionMessageEncoder` etc, which is probably the right name for them anyway.

Export the message codec, rename to getCompiledTransactionMessageEncoder etc to avoid clash

---

packages/signers/package.json
packages/signers/src/__tests__/fee-payer-signer-test.ts
packages/signers/src/fee-payer-signer.ts
pnpm-lock.yaml

This PR refactors the `setTransactionFeePayerSigner` function to operate on a `TransactionMessage` instead of an old transaction type.
One thing I want to flag is that I'm not sure why I needed to add these casts on the outputs to satisfy the type checker - but you can see that the tests behave exactly the same.

Refactor fee-payer-signer to use TransactionMessage

---

packages/signers/src/__tests__/__setup__.ts
packages/signers/src/__tests__/keypair-signer-test.ts
packages/signers/src/__tests__/noop-signer-test.ts
packages/signers/src/__tests__/transaction-partial-signer-test.ts
packages/signers/src/__tests__/transaction-signer-test.ts
packages/signers/src/keypair-signer.ts
packages/signers/src/noop-signer.ts
packages/signers/src/transaction-partial-signer.ts

This PR updates the `TransactionPartialSigner` type to also be able to sign `NewTransaction` objects. I've kept the current `signTransactions` function unchanged for now because it's used by yet to be refactored signer code. So this is just additive here, but will eventually replace `signTransactions`.

Refactor transaction-partial-signer to add newSignTransactions

---

packages/signers/src/__tests__/__setup__.ts
packages/signers/src/__tests__/transaction-modifying-signer-test.ts
packages/signers/src/__tests__/transaction-signer-test.ts
packages/signers/src/transaction-modifying-signer.ts

Again I've left the existing `modifyAndSignTransactions` for now because of code that uses it and hasn't yet been refactored, though this time it'll just be deleted and the new function has the correct name already. 
This is required to have the signature `NewTransaction -> NewTransaction` because of logic handling multiple modifying signers.

Add newModifyAndSignTransactions to modifying signer

---

packages/signers/src/__tests__/__setup__.ts
packages/signers/src/__tests__/transaction-sending-signer-test.ts
packages/signers/src/__tests__/transaction-signer-test.ts
packages/signers/src/transaction-sending-signer.ts

- Similar to with partial signers, this adds a new function for now for sending NewTransaction objects
- Will in future replace the existing signAndSendTransactions function
It's nice (from a web3js perspective at least...) that the signers package doesn't actually have the implementation of these types!

Refactor transaction-sending-signer to add newSignAndSendTransactions

---

packages/signers/src/__tests__/__setup__.ts
packages/signers/src/__tests__/account-signer-meta-test.ts
packages/signers/src/__tests__/transaction-with-single-sending-signer.ts
packages/signers/src/account-signer-meta.ts
packages/signers/src/transaction-with-single-sending-signer.ts

- The existing assert function is used by other code, so the existing version is kept for now

Add transaction message functions to transaction-with-single-sending-signer

---

packages/transactions/src/codecs/index.ts
packages/transactions/src/index.ts

I forgot to export this codec which is quite important! I haven't exported the message encoder for now because I think that will only be used internally, but the transaction codec is definitely external-facing.

Export the new transaction codec from transactions

---

packages/addresses/src/program-derived-address.ts

I'm getting the following error when updating Kinobi with the latest version of the new web3.js:
This is because we've updated everything to use `ReadonlyUint8Arrays` but not the PDA seeds so there is a type mismatch. This PR fixes this.

refactor(experimental): Use ReadonlyUint8Array on PDA seeds

---

packages/signers/src/__tests__/__setup__.ts
packages/signers/src/__tests__/sign-transaction-test.ts
packages/signers/src/sign-transaction.ts
packages/transactions/src/__tests__/new-compile-transaction-test.ts
packages/transactions/src/new-compile-transaction.ts

The signers now all take a `NewTransaction` as input. So these functions take a transaction message (with signers) and compile it to a `NewTransaction` before sending it to the signers.
I think this PR will enable me to remove the old signer functions and clean up/rename things back, but I'll do that in a separate PR to make it easier to review.

Refactor signers sign-transaction to use transaction messages

---

packages/signers/src/__typetests__/sign-transaction-typetest.ts
packages/signers/src/sign-transaction.ts
packages/signers/src/transaction-modifying-signer.ts
packages/transactions/src/__typetests__/signatures-typetests.ts
packages/transactions/src/new-signatures.ts

This PR updates the usages of `NewTransaction` to maintain the transaction lifetime. I should have realised we'd have to extend it!
- The sign functions in the `transactions` package now take a `T extends NewTransaction` and maintain the type T. This means that if you input a transaction with a lifetime, the output transaction will have the same lifetime.
- The signers now return `NewTransaction & TransactionWithLifetime`. I haven't calculated the diff here because they take a transaction message as input and call `compileTransactionMessage`, so their output isn't based on the transaction message input.

Maintain transaction lifetime on transactions

---

packages/fast-stable-stringify/.gitignore

We need to gitignore the dist/ directory
I've removed everything else since all our other packages just use dist/ but LMK if anything else needs to be there specific to this package!

Change gitignore of fast-stable-stringify to match other packages

---

.changeset/witty-camels-remember.md
packages/ws-impl/src/index.node.ts

Test Plan: run repro in #2461.
Closes #2461.

Use native `WebSocket` in server runtimes that support it

---

packages/fast-stable-stringify/LICENSE

I'm pretty sure we are supposed to add a copyright notice for us, but retain the existing one.

Restore original author to license file for `@solana/fast-stable-stringify`

---

.changeset/brave-chicken-own.md
packages/fast-stable-stringify/package.json
packages/fast-stable-stringify/src/__typetests__/index-typetest.ts
packages/fast-stable-stringify/src/index.ts
packages/fast-stable-stringify/tsconfig.declarations.json
packages/rpc-graphql/src/loaders/loader.ts

This thing returns a string always, unless you pass it `undefined` or a function.

Add types to `@solana/fast-stable-stringify`

---

.changeset/strong-pandas-marry.md

CI fails right now because one of our changesets refers to the legacy library when it is excluded from the packages changeset supports.

refactor(experimental): fix mixed changeset error on CI

---

packages/fast-stable-stringify/src/__tests__/index-test.ts
packages/fast-stable-stringify/src/index.ts

Support BigInt and added more tests. Putting Glyph outside the quote avoid collisions. 
```
s(100n) // "100"n
s({foo: 100n}) // {"foo":"100"n}
```
Closes #2496.

Add glyphs to fix Hash collision with bigint and string 

---

packages/library/src/send-transaction-internal.ts
packages/library/src/send-transaction.ts
packages/signers/src/__typetests__/sign-transaction-typetest.ts
packages/signers/src/sign-transaction.ts
packages/transaction-confirmation/src/__tests__/waiters-test.ts
packages/transaction-confirmation/src/waiters.ts
packages/transactions/src/__typetests__/compile-transaction-typetests.ts
packages/transactions/src/lifetime.ts
packages/transactions/src/new-compile-transaction.ts

I was repeating `NewTransaction & { lifetimeConstraint: X }` way too often
This PR adds helper types so we can include the lifetime constraints in types easier.

add TransactionWithXLifetime types

---

packages/library/src/__tests__/send-transaction-internal-test.ts
packages/library/src/send-transaction-internal.ts

This PR replaces the helpers for sending transactions to send `NewTransaction` objects, and to use the lifetime helpers.
We replace `SendableTransaction` with `FullySignedTransaction`, and mix in the lifetime constraints when required.

Refactor send-transaction to use NewTransaction

---

packages/rpc-api/package.json
packages/rpc-api/src/__tests__/get-fee-for-message-test.ts
packages/rpc-api/src/__typetests__/get-block-type-test.ts
packages/rpc-api/src/getBlock.ts
packages/rpc-api/src/getFeeForMessage.ts
packages/rpc-api/src/getTransaction.ts
packages/rpc-subscriptions-api/package.json
packages/rpc-subscriptions-api/src/__typetests__/block-notifications-type-test.ts
packages/rpc-subscriptions-api/src/block-notifications.ts
packages/transactions/src/index.ts
packages/transactions/src/transaction.ts
packages/transactions/src/types.ts
pnpm-lock.yaml

- New type TransactionMessageBytesBase64 in Transactions
- Replace TransactionVersion with NewTransactionVersion
This removes the need to export this `types` file from Transactions.

Replace uses of SerializedMessageBytesBase64 and TransactionVersion

---

packages/transactions/src/__tests__/signatures-test.ts
packages/transactions/src/compile-transaction.ts
packages/transactions/src/transaction.ts

Not sure what I was doing here, but OrderedMap is just used for SignaturesMap, and all the uses were just using it as that

Remove OrderedMap export and use SignaturesMap

---

packages/rpc-graphql/src/__tests__/__setup__.ts

@Hrushi20 here's the mock transaction payload I was talking about for testing.
Sets up for #2406.

refactor(experimental): graphql: add mock token-2022 transaction instructions to tests

---

packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's `InitializePermanentDelegate` extension
cc @Hrushi20.

refactor(experimental): graphql: token-2022 extensions: initialize-permanent-delegate

---

packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's `MetadataPointer` extension
cc @Hrushi20.

refactor(experimental): graphql: token-2022 extensions: metadata pointer

---

packages/signers/src/__tests__/account-signer-meta-test.ts
packages/signers/src/__tests__/fee-payer-signer-test.ts
packages/signers/src/__tests__/sign-transaction-test.ts
packages/signers/src/__typetests__/sign-transaction-typetest.ts
packages/signers/src/fee-payer-signer.ts
packages/signers/src/sign-transaction.ts

Clean up imports of `@solana/transactions` in signers, there were some leftover imports from `dist/types`. 
Rename `setTransactionFeePayerSigner` to `setTransactionMessageFeePayerSigner` to match the rest of the API

Rename setTransactionFeePayerSigner to setTransactionMessageFeePayerSigner

---

packages/transaction-messages/src/codecs/index.ts
packages/transaction-messages/src/codecs/message.ts
packages/transaction-messages/src/compile/index.ts
packages/transaction-messages/src/index.ts

- Most of `compile` is only used internally, but we do need to expose `compileTransactionMessage` for use in `@solana/transactions`
- Most codecs are only used internally, but message and transaction version are used by `@solana/transactions`
This roughly equates to what was previously exposed by `transactions`, which didn't expose its internal compile functions or intermediate codecs.

Remove unneeded exports from transaction-messages

---

packages/transaction-messages/README.md

Mostly pulled from the `transactions` readme and updated.

Add the readme for transaction-messages

---

packages/transactions/README.md

Mostly just removed all the `transaction-messages` stuff and updated to distinguish between transaction-messages and transactions.

Update the readme for transactions

---

packages/library/src/decode-transaction-message.ts

`CompilableTransactionMessage` is a more useful type because it makes more guarantees about the returned transaction message.
`decodeTransactionMessage` already returns this because `decompileTransactionMessage` returns it. This PR just updates the type to reflect this.

Return CompilableTransactionMessage from decodeTransactionMessage

---

.changeset/nine-pots-notice.md
packages/library/src/airdrop.ts
packages/library/src/send-transaction.ts
packages/transaction-confirmation/src/__tests__/confirmation-strategy-signature-test.ts
packages/transaction-confirmation/src/__typetests__/confirmation-strategy-recent-signature-typetests.ts
packages/transaction-confirmation/src/confirmation-strategy-recent-signature.ts

Following the effort to scope all `rpc` & `RpcSubscriptions` factories to specific clusters,
as outlined in #2534, this PR adds cluster scoping to
`createRecentSignatureConfirmationPromiseFactory`.

refactor(experimental): rpc scoping: `createRecentSignatureConfirmationPromiseFactory`

---

.changeset/poor-dogs-crash.md
packages/library/src/send-transaction.ts
packages/transaction-confirmation/src/__tests__/confirmation-strategy-nonce-test.ts
packages/transaction-confirmation/src/__typetests__/confirmation-strategy-nonce-typetests.ts
packages/transaction-confirmation/src/confirmation-strategy-nonce.ts

Following the effort to scope all `rpc` & `RpcSubscriptions` factories to specific clusters,
as outlined in #2534, this PR adds cluster scoping to
`createNonceInvalidationPromiseFactory `.

refactor(experimental): rpc scoping: `createNonceInvalidationPromiseFactory`

---

packages/library/src/__typetests__/send-and-confirm-durable-nonce-transaction-typetests.ts
packages/library/src/send-and-confirm-durable-nonce-transaction.ts

Following the effort to scope all `rpc` & `RpcSubscriptions` factories to specific clusters,
as outlined in #2534, this PR adds cluster scoping to
`sendAndConfirmDurableNonceTransactionFactory `.

refactor(experimental): rpc scoping: `sendAndConfirmDurableNonceTransactionFactory`

---

packages/library/src/__typetests__/send-and-confirm-transaction-typetests.ts
packages/library/src/send-and-confirm-transaction.ts

Following the effort to scope all `rpc` & `RpcSubscriptions` factories to specific clusters,
as outlined in #2534, this PR adds cluster scoping to
`sendAndConfirmTransactionFactory `.

refactor(experimental): rpc scoping: `sendAndConfirmTransactionFactory`

---

packages/codecs-strings/src/__benchmarks__/run.ts
packages/codecs-strings/src/base16.ts

Quick PR addressing the issue #2527;
~@steveluscher it makes total sense to me that this approach is faster as we go through the input less times, also we check the errors inside the transform code instead of doing a iteration, but how shall i go about testing this?~
```shell
┌─────────┬─────────────────┬─────────────┬───────────────────┬──────────┬─────────┐
│ (index) │    Task Name    │   ops/sec   │ Average Time (ns) │  Margin  │ Samples │
├─────────┼─────────────────┼─────────────┼───────────────────┼──────────┼─────────┤
│    0    │ 'Base58 decode' │  '37,649'   │ 26561.11945194077 │ '±0.70%' │  18825  │
│    1    │ 'Base58 encode' │  '37,581'   │ 26608.59333410035 │ '±0.60%' │  18791  │
│    2    │ 'Base16 encode' │ '1,411,479' │ 708.4763073389463 │ '±5.45%' │ 705740  │ …
```

[refactor] [experimental] Use optimised base16 encode strategy

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's TransferFeeExtension's InitializeTransferFeeConfig instruction
Todo: 
Need to add test.

graphql: token-2022 extensions: InitializeTransferFeeConfig

---

packages/library-legacy/package.json
pnpm-lock.yaml

`0.4.4` and `0.4.5` had broken CJS exports, so we should not be recommending them here.

chore: bump `@solana/spl-token` to `^0.4.6`

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's `GroupPointer` extension
cc @Hrushi20.

refactor(experimental): graphql: token-2022 extensions: group pointer

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's `GroupMemberPointer` extension
cc @Hrushi20.

refactor(experimental): graphql: token-2022 extensions: group member pointer

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's `TransferHook` extension
cc @Hrushi20.

refactor(experimental): graphql: token-2022 extensions: transfer hook

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's `DefaultAccountState` extension
cc @Hrushi20.

refactor(experimental): graphql: token-2022 extensions: default account state

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's `CpiGuard` extension
cc @Hrushi20.

refactor(experimental): graphql: token-2022 extensions: cpi guard

---

turbo.json

TIL that specifying an `input` clears unsets the defaults. You have to put them back.

Apply default input dependencies to every Turbo step

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's TransferFeeExtension's harvestWithheldTokensToMint and withdrawWithheldTokensFromAccounts instructions in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: harvestWithheldTokensToMint and WithdrawWithheldTokensFromAccounts

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's TransferFeeExtension's withdrawWithheldTokensFromMint instruction

 refactor(experimental): graphql: token-2022 extensions: withdrawWithheldTokensFromMint

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's TransferFeeExtension's TransferCheckedWithFee instruction

 refactor(experimental): graphql: token-2022 extensions: TransferCheckedWithFee

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's RequiredMemoTransfers instruction in the GraphQL schema for both enable and disable.

refactor(experimental): graphql: token-2022 extensions: RequiredMemoTransfers

---

packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's InitializeConfidentialTransferMint instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: InitializeConfidentialTransferMint 

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's InitializeInterestBearingConfig,UpdateInterestBearingConfig instructions in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: InitializeInterestBearingConfig, UpdateInterestBearingConfig

---

.changeset/thick-radios-appear.md
packages/transaction-messages/src/__tests__/blockhash-test.ts
packages/transaction-messages/src/__tests__/create-transaction-message-test.ts
packages/transaction-messages/src/__tests__/decompile-message-test.ts
packages/transaction-messages/src/__tests__/durable-nonce-test.ts
packages/transaction-messages/src/__tests__/instructions-test.ts
packages/transaction-messages/src/blockhash.ts
packages/transaction-messages/src/create-transaction-message.ts
packages/transaction-messages/src/decompile-message.ts
packages/transaction-messages/src/durable-nonce.ts
packages/transaction-messages/src/instructions.ts

- Freeze the instructions array when we append/prepend instructions
- Freeze the instructions array when we create a transaction message
- Freeze the instructions array and lifetime when adding a durable nonce
- Freeze the lifetime constraint when adding a blockhash
- Freeze instructions when decompiling a transaction message

Freeze instructions and lifetime in transaction message objects

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's ApproveConfidentialTransferAccount, EmptyConfidentialTransferAccount instructions in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: ApproveConfidentialTransferAccount, EmptyConfidentialTransferAccount

---

packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's ConfigureConfidentialTransferAccount instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: ConfigureConfidentialTransferAccount Instruction #2611

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `Clock` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: clock

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `EpochRewards` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: epoch rewards

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `EpochSchedule` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: epoch schedule

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `Fees` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: fees

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `LastRestartSlot` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: last restart slot

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `RecentBlockhashes` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: recent blockhashes

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `Rent` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: rent

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `SlotHashes` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: slot hashes

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `SlotHistory` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: slot history

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds support for parsed sysvar account `StakeHistory` to the GraphQL schema.
Ref: #2622.

refactor(experimental): graphql: sysvars: stake history

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's ApplyPendingConfidentialTransferBalance instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: ApplyPendingConfidentialTransferBalance

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `PermanentDelegate`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: permanent delegate

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `InterestBearingConfig`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: interest bearing config

---

.github/workflows/actions/install-dependencies/action.yml
.github/workflows/bundlesize.yml
.github/workflows/commit-lint.yml
package.json
pnpm-lock.yaml

In addition to blocklisting `npm`/`yarn`, I'd like to make the version of pnpm a requirement so that we don't keep thrashing the lockfile depending on who last touched the repo.

Strictly require project to use `pnpm` 9 or higher

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's DepositConfidentialTransfer  instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: DepositConfidentialTransfer

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's WithdrawConfidentialTransfer instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: WithdrawConfidentialTransfer

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's ConfidentialTransfer instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: ConfidentialTransfer

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's ConfidentialTransferWithSplitProofs instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: ConfidentialTransferWithSplitProofs

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's UpdateConfidentialTransferMint instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: UpdateConfidentialTransferMint

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's WithdrawWithheldConfidentialTransferTokensFromMint instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: WithdrawWithheldConfidentialTransferTokensFromMint

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `DefaultAccountState`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: default account state

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `TransferFeeConfig`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: transfer fee config

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `ConfidentialTransferMint`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: confidential transfer mint

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `ConfidentialTransferFeeConfig`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: confidential transfer fee config

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `MetadataPointer`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: metadata pointer

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `GroupPointer`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: group pointer

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `GroupMemberPointer`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: group member pointer

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `TokenMetadata`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: token metadata

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for `TokenGroup`.
Ref #2644.

refactor(experimental): graphql: token-2022 extensions account state: token group

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's WithdrawWithheldConfidentialTransferTokensFromFromAccounts instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: WithdrawWithheldConfidentialTransferTokensFromFromAccounts

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's HarvestWithheldConfidentialTransferTokensToMint instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: HarvestWithheldConfidentialTransferTokensToMint

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's EnableConfidentialTransferFeeHarvestToMint DisableConfidentialTransferFeeHarvestToMint instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: EnableConfidentialTransferFeeHarvestToMint DisableConfidentialTransferFeeHarvestToMint

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's InitializeConfidentialTransferFeeConfig instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: InitializeConfidentialTransferFeeConfig

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's InitializeTokenGroup instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: InitializeTokenGroup

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's UpdateGroupMaxSize instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: UpdateGroupMaxSize

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's UpdateGroupAuthority instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: UpdateGroupAuthority

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's InitializeTokenGroupMember instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: InitializeTokenGroupMember

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's InitializeMetadata instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: InitializeMetadata

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's UpdateField instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: UpdateField

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's RemoveKey instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: RemoveKey

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

This PR adds Token-2022 extension parsed account state support for ConfidentialTransferAccount.
Ref https://github.com/solana-labs/solana-web3.js/issues/2644.

refactor(experimental): graphql: token-2022 extensions account state: confidentialTransferAccount

---

packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/resolvers/account.ts
packages/rpc-graphql/src/schema/account.ts

- TransferFeeAmount
- ImmutableOwner
- MemoTransfer
- CpiGuard
- NonTransferableAccount
- ConfidentialTransferFeeAmount
- TransferHookAccount
Ref https://github.com/solana-labs/solana-web3.js/issues/2644.

Support SPL Token account state within the schema for Token Account 

---

packages/rpc-graphql/src/__tests__/__setup__.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/resolvers/instruction.ts
packages/rpc-graphql/src/schema/instruction.ts

This PR adds support for Token-2022's UpdateAuthority Emit instruction in the GraphQL schema.

refactor(experimental): graphql: token-2022 extensions: UpdateAuthority Emit

---

packages/library/README.md

As written there's a type error because the `createRpcApi` expects the methods object to extend `RpcApiMethods`:
This PR just updates the readme so the example `NftCollectionDetailsApi` extends `RpcApiMethods` which fixes the type error

Update library readme to include extending RpcApiMethods

---

packages/library-legacy/src/utils/makeWebsocketUrl.ts
packages/rpc-api/src/__tests__/get-cluster-nodes-test.ts
packages/rpc-api/src/__tests__/get-version-test.ts

See https://github.com/solana-labs/solana-web3.js/issues/2718 for why this broke.

Repair tests after #2717

---

packages/rpc-subscriptions-api/src/__typetests__/program-notifications-type-test.ts
packages/rpc-subscriptions-api/src/program-notifications.ts

This typespec was wrong. The `memcmp` filter is nested under `{ memcmp: /* ... */ }`

Repair the type of `getProgramAccounts` with respect to the `memcmp` filter

---

.changeset/chilly-seas-act.md
packages/library/src/__tests__/compute-limit-internal-test.ts
packages/library/src/compute-limit-internal.ts

Looking through recent updates to the monorepo, this caught my eye: https://github.com/anza-xyz/agave/issues/885
The simulation utility sets `u32::MAX`, which will fail once that feature is enabled.
Set `MAX_COMPUTE_UNITS`, hardcoded to 1,400,000, instead of `u32::MAX`.

Simulate with max compute units, not u32::MAX

---

packages/compat/src/transaction.ts
packages/signers/src/__tests__/sign-transaction-test.ts
packages/signers/src/keypair-signer.ts
packages/transaction-confirmation/src/__tests__/waiters-test.ts

Downstream build systems are choking on this relative import, and I'm not sure that this will fix it, but it can't hurt.

Pull in `ReadonlyUint8Array` as a type

---

packages/codecs-core/package.json
packages/codecs-core/src/__benchmarks__/run.ts
packages/codecs-core/src/__tests__/reverse-codec-test.ts
packages/codecs-core/src/reverse-codec.ts
pnpm-lock.yaml

This is, what I hope to be, the first of many performance PRs. In general, we've prioritized correctness and readability in the codecs up until this point. The next step is to unroll that a bit to achieve great performance.
* Copy as little as possible.
* Operate in-place wherever possible, like in this PR
* Everywhere else, replace every possible call to `slice()` with `subarray()` which creates a new view over the same underlying data
* Do as little math as possible
In this PR, we implement the reverse codec without using `reverse()` or cloning the source data. We instead write elements of the source into the target in reverse order.
* 7.5x speedup for decode
* 1.5x speedup for encode
```
> ./src/__benchmarks__/run.ts
┌─────────┬──────────────────┬─────────────┬───────────────────┬────── …
```

Turbocharge the `reverseCodec()`

---

.changeset/unlucky-pumpkins-itch.md
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc-request.ts

This provides flexibility for APIs that do not use an array of params. For example Helius' non-standard APIs expect `params` to be an object and don't use an array wrapper, like this:
```json
{
"jsonrpc": "2.0",
"id": "text",
"method": "getTokenAccounts",
"params": {
"owner": "some-address",
"limit": 100
}
}
```
This can be handled with a `parametersTransformer`:
```ts
const api = createRpcApi<HeliusDasApi>({
parametersTransformer: (params) => params[0],
});
```
But currently this is a type error, because `parametersTransformer` is required to return `unknown[]`. This PR allows it to just return `unknown` so that the above is no longer a type error.

Allow RpcRequest params to be of any type, instead of requiring an array

---

packages/library-legacy/src/connection.ts
packages/library-legacy/src/errors.ts

The rename to transactionLogs was breaking a downstream test and is not really necessary to be renamed.

chore: rename transactionLogs back to logs

---

packages/library-legacy/src/errors.ts

- Add a getter for logs with the old types to be a non breaking change

chore: Add getter for logs to sendTransactionError

---

.changeset/proud-poems-try.md
packages/errors/src/__tests__/message-formatter-test.ts
packages/errors/src/message-formatter.ts

@C-o-d-e-C-o-w-b-o-y and @lukecaan noticed that negative lookbehinds crash old versions of Safari (#2745).
This PR reimplements the message printer as a parser.
```
cd packages/errors/
```

fix: Rewrite the message printer as a parser to avoid problems with regexes in old browsers

---

packages/library-legacy/package.json
packages/library-legacy/rollup.config.mjs
packages/library-legacy/src/__forks__/browser/rpc-websocket-factory.ts
packages/library-legacy/src/__forks__/react-native/rpc-websocket-factory.ts
packages/library-legacy/src/rpc-websocket-factory.ts
packages/library-legacy/src/rpc-websocket.ts
pnpm-lock.yaml

Hopefully this solves folks' build pipeline problems, once and for all.
See https://github.com/elpheria/rpc-websockets/pull/164.

feat: upgrade to `rpc-websockets` v9

---

package.json
pnpm-lock.yaml
turbo.json

This is the same as #2798, but with the `GH_TOKEN` and `NPM_TOKEN` env passed through to the publish scripts.

chore: update to Turborepo 2.0.4-canary.2

---

.changeset/early-eyes-mix.md
packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
packages/rpc/src/rpc-request-coalescer.ts

If multiple consumers made the same RPC call, then all of them aborted, then another consumer made the same RPC call, all in the same runloop, you'd end up with zero inflight requests and the remaining callers would never recieve their response.

Fixed a bug where the RPC coalescer would leave the application with no request even though there were consumers

---

packages/react/src/__tests__/useSignAndSendTransaction-test.ts
packages/react/src/__tests__/useSignTransaction-test.ts
packages/react/src/__typetests__/useSignAndSendTransaction-typetest.ts
packages/react/src/__typetests__/useSignTransaction-typetest.ts
packages/react/src/useSignAndSendTransaction.ts
packages/react/src/useSignTransaction.ts
packages/react/src/useWalletAccountTransactionSendingSigner.ts
packages/react/src/useWalletAccountTransactionSigner.ts

When the chains were not known – as in the case of having a plain old `UiWalletAccount` – this invocation would fail to typecheck:
```ts
useSignTransaction(
account,
"solana:mainnet" // ERROR
);
```
This was because `OnlySolanaChains<IdentifierArray>` is `never`.
This PR fixes it so that you get both good autocomplete when the chains are known, and you can supply any `solana:*` chain in any case.

Repair the type of the `chain` argument to `useSignTransaction` and `useSignAndSendTransaction`

---

packages/rpc-graphql/src/resolvers/resolve-info/visitor.ts

As mentioned in [this review comment](https://github.com/solana-labs/solana-web3.js/pull/2643#discussion_r1597258324), the `onlyFieldsRequested` visitor
check - which evaluates if a query has only requested fields matching some
set of field names - is not configured to ignore GraphQL's default fields, such
as `__id` and `__typename`.
This PR adds those fields to the helper's "ignore list".

refactor(experimental): graphql: patch `onlyFieldsRequested` for GraphQL default fields

---

packages/rpc-graphql/README.md
packages/rpc-graphql/src/__tests__/account-test.ts
packages/rpc-graphql/src/__tests__/block-tests.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/__tests__/transaction-tests.ts
packages/rpc-graphql/src/index.ts
packages/rpc-graphql/src/loaders/__tests__/account-loader-test.ts
packages/rpc-graphql/src/loaders/__tests__/block-loader-test.ts
packages/rpc-graphql/src/loaders/__tests__/program-accounts-loader-test.ts
packages/rpc-graphql/src/loaders/__tests__/transaction-loader-test.ts
packages/rpc-graphql/src/resolvers/__tests__/account-resolver-test.ts
packages/rpc-graphql/src/resolvers/__tests__/block-inputs-test.ts
packages/rpc-graphql/src/resolvers/__tests__/block-resolver-test.ts
packages/rpc-graphql/src/resolvers/__tests__/program-accounts-resolver-test.ts
packages/rpc-graphql/src/resolvers/__tests__/transaction-resolver-test.ts
packages/rpc-graphql/src/schema/type-defs/index.ts
packages/rpc-graphql/src/schema/type-resolvers/index.ts

This PR supercedes #2613. As suggested by @steveluscher, I've instead opted to
export the necessary components for downstream users to stitch together their own
schemas using the Solana GraphQL schema defined in this library.
This is mostly made possible by refactoring `createRpcGraphQL` to accept a `schema`
input argument, and rolling a new `createSolanaRpcGraphQL` to create an `RpcGraphQL`
with the default Solana schema.
Everywhere in the library (tests, etc.) I'm using the default `createSolanaRpcGraphQL`, but
downstream users can now use `createSolanaGraphQLTypeDefs` and
`createSolanaGraphQLTypeResolvers`, stitched together with their own type definitions and
type resolvers, to feed `createRpcGraphQL` the required schema object.

refactor(experimental): graphql: export components for stitching schema

---

scripts/get-latest-validator-release-version.sh

Agave v1.18.15 is officially recommended for mainnet-beta, and has reached
supermajority adoption.
This PR updates Web3.js to use the test validator for 1.18, matching the running
version for mainnet-beta.

refactor(experimental): update test validator for mainnet-beta v1.18

---

.changeset/short-jokes-begin.md
packages/signers/README.md
packages/signers/src/sign-transaction.ts

Fixes https://github.com/solana-labs/solana-web3.js/issues/2818
This PR calls the `assertIsTransactionMessageWithSingleSendingSigner` inside the `signAndSendTransactionMessageWithSigners` so the end-user doesn't need to do it explicitly.
This is partly to improve the developer experience and partly because TS doesn't fail properly when the transaction message hasn't been asserted on prior to calling the sign and send function.
Note that I did not remove the `assertIsTransactionMessageWithSingleSendingSigner` and the `isTransactionMessageWithSingleSendingSigner` from the package's exports since they may still be useful for custom use-cases such as the one described in the documentation:
```ts
let transactionSignature: SignatureBytes;
if …
```

refactor(experimental): assert single sending signer inside signAndSend function

---

packages/signers/README.md
packages/signers/src/__tests__/sign-transaction-test.ts

Some of the functions and examples in the signers documentation (and some comments in the tests) hadn't been updating since the `transaction` to `transactionMessage` refactoring.

refactor(experimental): fix transaction references in signers documentation

---

.changeset/wicked-cougars-matter.md
packages/react/src/__tests__/useWalletAccountTransactionSendingSigner-test.ts
packages/react/src/__tests__/useWalletAccountTransactionSigner-test.ts
packages/react/src/useWalletAccountTransactionSendingSigner.ts
packages/react/src/useWalletAccountTransactionSigner.ts
packages/signers/src/__tests__/sign-transaction-test.ts
packages/signers/src/sign-transaction.ts
packages/signers/src/transaction-modifying-signer.ts
packages/signers/src/transaction-partial-signer.ts
packages/signers/src/transaction-sending-signer.ts
packages/signers/src/types.ts

Instead of the cumbersome `getOptions()` solution that requires callers of the hook to track transaction / context slot pairs and return a getter for them… just add `minContextSlot` to the options.
```
```
Closes #2846

Add `minContextSlot` as an option to `Transaction{Sending}SignerConfig`

---

packages/fetch-impl/LICENSE
packages/fetch-impl/package.json
packages/fetch-impl/src/__benchmarks__/run.ts
packages/fetch-impl/tsconfig.json
pnpm-lock.yaml

This code was mistakenly deleted in #2267. We still want to be able to run these benchmarks.
```
cd packages/fetch-impl/
pnpm i
pnpm benchmark
```

Rehabilitate the fetch benchmark

---

packages/library-legacy/src/connection.ts
packages/library-legacy/test/connection.test.ts

fix: `onProgramAccountChange()` and `onAccountChange()` now accept an encoding

---

.changeset/fast-cars-knock.md
packages/rpc-api/src/simulateTransaction.ts

This was returning `accounts: null` at the top level instead of inside `value`
See https://github.com/solana-labs/solana-web3.js/commit/7192f3d37e6cf65e144c8cd920fa20a71b2b1fe0

Correct the return type of `simulateTransaction` when accounts are not loaded

---

packages/library-legacy/src/connection.ts
packages/rpc-api/src/getStakeActivation.ts

This was deprecated in https://github.com/anza-xyz/agave/pull/69

fix: deprecate the `getStakeActivation` RPC method

---

packages/library-legacy/src/connection.ts

fix: add deprecation notice for `getConfirmedSignatureForAddress2` and update other deprecation notices' validator versions

---

.changeset/sour-mugs-press.md
packages/errors/src/json-rpc-error.ts

These names are camel-cased. This can't be imported from `@solana/rpc-types` because `@solana/errors` must be zero dependency.

Correct the type of `innerInstructions` in JSON RPC errors

---

packages/library-legacy/src/connection.ts

This PR aims to address the issue I've outlined in #2755 where the `innerInstructions` parameter is missing for transaction simulations

feat(simulated_transaction): Add Inner Instructions

---

packages/signers/src/__typetests__/fee-payer-typetest.ts
packages/signers/src/fee-payer-signer.ts
packages/transaction-messages/src/__typetests__/fee-payer-typetests.ts
packages/transaction-messages/src/fee-payer.ts

These functions would not accept a simple `CompilableTransactionMessage` as input. Furthermore, this type was intended to _unset_ the existing fee payer and replace it with the one passed in. Instead, this was producing the union of the old and new fee payers.
```
pnpm turbo compile:typedefs
```
Closes #2854.

`setTransactionMessageFeePayer{Signer}` now accepts a broader range of inputs

---

packages/rpc-api/src/getAccountInfo.ts

I have no idea if this stack is actually going to do us any material good, but here goes...
In many API definitions across `@solana/rpc-api`, we waffle between using the 
`SolanaRpcResponse` wrapper in the "base types" and in the method signatures.
This can make things _extremely_ difficult to follow when updating types. It's also
tricky to spot if we're accurately returning an RPC Response object on the methods
that should be.
This stack updates every delinquent method to use the same pattern:
- All base types are defined above the interface.
- Any methods that return an RPC Response declare so in the **method signature**.
The entire stack is the same, for each method in the title, so I'm not going to update
each PR's description.
👉 There is one method whose types were incorrect. It's …

refactor(experimental): type reconciliation: `GetAccountInfoApi`

---

packages/rpc-api/src/getTokenLargestAccounts.ts

This one's return type was actually incorrect. It was returning an array of `{ address: Address }` and then a `TokenAmount`.

refactor(experimental): type reconciliation: `GetTokenLargestAccountsApi`

---

.changeset/rare-goats-sell.md
packages/library/src/compute-limit.ts

Whoops. This `config` should have been optional and should not have contained `transactionMessage`

Correct the type of `getComputeUnitEstimateForTransactionMessage`

---

.changeset/rich-eggs-tease.md
packages/build-scripts/dev-flag.ts
packages/rpc-subscriptions-spec/src/__tests__/rpc-subscription-test.ts

A few folks have been caught out _not_ having _any_ setting for `NODE_ENV`. In cases like this, the `__DEV__` flag will be `false` because `NODE_ENV` is not `'development'`.
It would be preferable for development to be the default when there is no `NODE_ENV`. This means it will be harder to get ‘into’ production mode (you have to set an env variable) but it will mean that people fall into the pit of success when debug functionality is what they're looking for.
```
pnpm i
pnpm turbo compile:js
```
Observe that all of the `__DEV__` constants have been replaced with `process.env.NODE_ENV !== 'production'`

`__DEV__` logic is now ‘NODE_ENV is not production’

---

packages/library-legacy/src/validator-info.ts
packages/library-legacy/test/validator-info.test.ts

Adds iconUrl to validator `Info` type in` /library-legacy/src/validator-info.ts`.
As can be seen when running `solana -um validator-info get,` validators have already started adding it to their information.
I couldn't find code regarding this in the TP, but I'm happy to add it if I missed it.

feat: add `iconUrl` to `ValidatorInfo` type

---

turbo.json

Closes #2718.
```
pnpm turbo test:unit:node --filter=@solana/rpc-spec
pnpm turbo test:unit:node --filter=@solana/rpc-spec
nano .agave/active_release/version.yml  # Change version
pnpm turbo test:unit:node --filter=@solana/rpc-spec
```
Observe that first call is uncached, second is cached, and third is uncached.

Bust Turborepo cache when the test validator version changes

---

examples/react-app/src/routes/root.tsx

Previously, if you encountered an error (eg. some feature is not supported by some wallet / on some chain) the error message would never go away, even if you switched to a wallet that _did_ support it.
This PR resets the error boundary when the account/chain changes.
1. Select Trust wallet account, which does not support `signAndSendTransaction` on devnet/testnet.
2. Switch to Phantom wallet account.
Observe that the error is cleared and the sign and send feature panel appears.

Reset errors when changing account/chain

---

examples/react-app/src/components/ConnectWalletMenu.tsx
examples/react-app/src/components/Nav.tsx
examples/react-app/src/routes/root.tsx

Turns out, this mistake was the entire reason that I needed a `startTransition()` here where one didn't make any sense. The `fallback` here could, itself, suspend.
The only reason I stuck `<Balance />` in there was so that it would hold open the same height and not cause a layout shift. Bad move. Just draw the box the size it needs to be.
Select a bunch of wallets and change the cluster. Observe the balance spinner appear and disappear without causing layout shift.

Prevent the balance component's Suspense fallback from, itself, suspending

---

.changeset/fuzzy-lizards-end.md
packages/react/README.md
packages/react/src/__tests__/useSignIn-test.ts
packages/react/src/__typetests__/useSignIn-typetest.ts
packages/react/src/index.ts
packages/react/src/useSignIn.ts

This hook returns essentially the raw sign in function from the `solana:signIn` feature. It upcasts the returned `WalletAccount` to a `UiWalletAccount` usable with the rest of the `@solana/react` API.
Callers are responsible for verifying the signed message and its signature.
```
pnpm turbo test:unit:node test:unit:browser test:typecheck
```

A `useSignIn()` hook for accessing the Sign In With Solana feature

---

.github/workflows/publish-gh-pages.yml
.github/workflows/publish-legacy-package.yml
.github/workflows/publish-packages.yml
.github/workflows/publish-prerelease-packages.yml
.github/workflows/pull-requests.yml
package.json

We're regularly getting [failures in CI](https://github.com/solana-labs/solana-web3.js/actions/runs/9911023987/job/27382758824) of the form ‘test timed out.’ I suspect this is just resource starvation on our very weak GitHub actions runners.
This PR sets concurrency to 95.84%. This number is selfishly chosen so that the script runs with exactly 46/48 processors on my dev machine.
Looked at how Turborepo [computes concurrency](https://github.com/vercel/turbo/blob/be67cfd1dc388f636db3b3b598dd4ad286946b28/crates/turborepo-lib/src/opts.rs#L257). It basically rounds down.
```
// https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=46dcdbb0c3fc5ee183bc4fe30e42ec57
(48 as f64 * 95.84 / 100.0).max(1.0) as u32) // 46
```

Use fewer than all of the processors when running Turborepo

---

packages/library-legacy/src/connection.ts
packages/library-legacy/test/connection.test.ts

See https://github.com/anza-xyz/agave/pull/2050.

fix: apply default `memcmp` encoding (`base58`) when not supplied

---

.changeset/metal-bees-lick.md
packages/rpc-spec/package.json
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc.ts
packages/rpc-subscriptions-spec/src/__tests__/rpc-subscription-test.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions.ts
packages/rpc-transformers/package.json
packages/rpc-transformers/src/__tests__/response-transformer-test.ts
packages/rpc-transformers/src/response-transformer.ts
pnpm-lock.yaml

This PR does the following:
- `rpc-spec` no longer returns the `result` field of the transport. This means that a custom transport does not need to use this JSON RPC concept. 
- Instead the default transformer now operates on the `result` field, since its input is a JSON RPC transport. 
- `rpc-spec` no longer detects an `error` field and converts it to a `SolanaError`. This means that custom transports can have arbitrary error handling. It now throws any error from the transport as-is. 
- Instead the default transformer now detects an `error` field and converts it to a `SolanaError` using the same logic, so that our default RPC has the same error handling as before.
This removes the need for transports to implement parts of the JSON RPC spec. They are free to return any arbitrary data, …

RPC: Remove JSON RPC specific behaviour from rpc-spec, move into default transformer

---

.changeset/warm-pears-sip.md
packages/programs/src/__typetests__/program-error-typetest.ts
packages/programs/src/program-error.ts

This PR makes the `isProgramError` helper return `Readonly` objects as suggested in [this Kinobi PR](https://github.com/kinobi-so/kinobi/pull/127).

Tighten return type of isProgramError

---

packages/tsconfig/base.json

This is a runtime change from old TypeScript to that which ECMAScript decided upon. You can read all about it [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier).
It would probably be wise to be explicit about this setting, and furthermore to align it with the spec, just in case we change out bundlers later that have some behaviour different than `tsup`.
Modules.
```diff
var SolanaError = class extends Error {
+ context;
constructor(...[code, contextAndErrorOptions]) {
let context;
```
Browser bundle.
```diff
var SolanaError = class extends Error {
constructor(...[code, contextAndErrorOptions]) {
let context;
let errorOptions;
if (contextAndErrorOptions) {
const { cause, ...contextRest } …
```

Enable `useDefineForClassFields`

---

examples/transfer-lamports/src/example.ts
packages/errors/src/__typetests__/error-typetest.ts
packages/errors/src/codes.ts
packages/errors/src/error.ts

`SolanaErrors` with a nested `cause` now specify the `cause` property as `SolanaError | undefined`

---

.changeset/chilled-walls-scream.md
packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
packages/rpc/src/rpc-request-coalescer.ts

When an `AbortSignal` was supplied to the RPC request coalescer, it would fail to attach a rejection handler to the shim promise returned to the app.
```
cd packages/rpc/
```

The RPC request coalescer now throws exceptions whether you configure it with an `AbortSignal` or not

---

examples/deserialize-transaction/src/example.ts

Lest we lead anyone astray that this is denominated in SOL or that numbers are preferable over bigints.

Use `lamports()` in deserialize transaction example

---

packages/library/README.md

Fixes import reference for `getSetComputeUnitLimitInstruction` helper

fix: correct import for `getSetComputeUnitLimitInstruction` helper

---

packages/codecs-data-structures/src/__typetests__/enum-typetest.ts
packages/codecs-data-structures/src/__typetests__/literal-union-typetest.ts
packages/codecs-numbers/src/__tests__/__setup__.ts
packages/codecs-numbers/src/__tests__/f32-test.ts
packages/codecs-numbers/src/__tests__/f64-test.ts
packages/codecs-numbers/src/__tests__/i16-test.ts
packages/codecs-numbers/src/__tests__/i32-test.ts
packages/codecs-numbers/src/__tests__/i8-test.ts
packages/codecs-numbers/src/__tests__/short-u16-test.ts
packages/codecs-numbers/src/__tests__/u16-test.ts
packages/codecs-numbers/src/__tests__/u32-test.ts
packages/codecs-numbers/src/__tests__/u8-test.ts
packages/codecs-numbers/src/__typetests__/codecs.ts
packages/codecs-numbers/src/common.ts
packages/codecs-numbers/src/f32.ts
packages/codecs-numbers/src/f64.ts
packages/codecs-numbers/src/i16.ts
packages/codecs-numbers/src/i32.ts
packages/codecs-numbers/src/i8.ts
packages/codecs-numbers/src/short-u16.ts
packages/codecs-numbers/src/u16.ts
packages/codecs-numbers/src/u32.ts
packages/codecs-numbers/src/u8.ts
packages/rpc-types/src/__tests__/lamports-test.ts
packages/rpc-types/src/__typetests__/lamports-typetests.ts
packages/rpc-types/src/lamports.ts

This is a prerequisite for https://github.com/kinobi-so/kinobi/issues/141, as the `solAmountTypeNode` can be defined with any number type:
```json
"type": {
"kind": "solAmountTypeNode",
"number": {
"kind": "numberTypeNode",
"format": "u64",
"endian": "be"
}
}
```
In order to render this using `getLamportsEncoder` etc without restricting the wrapped number type, we need to allow passing an arbitrary number encoder/decoder as a lamports encoder.
This is enabled by generalising number encoders to all encode a `bigint | number`, instead of the smaller ones being restricted to only encoding numbers. They will still decode to only `number`. An existing range check restricts the values to the appropriate range. 
This means that any number encoder can receive a `bigint` value, ie a Lamports …

Refactor number codecs + allow offloading lamport codec to an inner codec

---

packages/rpc-types/src/__tests__/lamports-test.ts
packages/rpc-types/src/__typetests__/lamports-typetests.ts
packages/rpc-types/src/lamports.ts
packages/sysvars/src/fees.ts
packages/sysvars/src/recent-blockhashes.ts
packages/sysvars/src/rent.ts
packages/sysvars/src/stake-history.ts

Renames:
- getLamportsEncoder/Decoder/Codec -> getDefaultLamportsEncoder/Decoder/Codec
- getLamportsEncoderFromEncoder/DecoderFromDecoder/CodecFromCodec -> getLamportsEncoder/Decoder/Codec
Follow on PR from https://github.com/solana-labs/solana-web3.js/pull/2991#discussion_r1693942095

Rename eg getLamportsEncoder -> getDefaultLamportsEncoder

---

packages/rpc-spec/README.md

Update the README for `@solana/rpc-spec`

---

examples/rpc-custom-api/LICENSE
examples/rpc-custom-api/package.json
examples/rpc-custom-api/src/example.ts
examples/rpc-custom-api/tsconfig.json
packages/rpc-subscriptions/src/index.ts
packages/rpc-subscriptions/src/rpc-default-config.ts
packages/rpc-subscriptions/src/rpc-subscriptions.ts
packages/rpc/src/index.ts
pnpm-lock.yaml

Some JSON RPC servers implement additional methods, above and beyond the ones offered by the Solana JSON RPC API. We want developers to be able to mix these into their RPC instance commensurate with their RPC providers' capabilities.
In this PR we provide an example of how one might add a custom JSON RPC API method based on the `getAsset` method available on the public Solana Mainnet RPC server.
```
cd examples/rpc-custom-api/
pnpm start
> @solana/example-rpc-custom-api@ start /home/sol/src/solana-web3.js-git/examples/rpc-custom-api
> tsx src/example.ts
INFO (Custom JSON RPC API): [step 1] Solana RPC methods like `getLatestBlockhash` still work
blockhash: "C8Tqp653ZcyRcnPjnrwjRLfZBpwWPjSTFa5Fr8jA2iSL"
lastValidBlockHeight: 258841174
INFO (Custom JSON RPC API): [step 2] The custom …
```

An example that demonstrates how to add a custom JSON RPC API method to the base ones

---

packages/rpc/README.md
packages/rpc/src/index.ts
packages/rpc/src/rpc-clusters.ts
packages/rpc/src/rpc-transport.ts
packages/rpc/src/rpc.ts

Update the README for `@solana/rpc`

---

packages/compat/README.md

This was missed as part of the transaction refactor. Compat now only has a `fromVersionedTransaction` function which gives a `Transaction`, and you can convert that further to a transaction message separately if required. Therefore it makes no distinction between a blockhash and durable nonce transaction, which are concerns of transaction message only.

Update compat readme to only mention `fromVersionedTransaction`

---

packages/library-legacy/test/connection.test.ts

There are a number of tests here that presume the validator to have advanced past a certain slot. This PR baloons the test timeout when we discover that not to be the case.
Enable each one of these tests in isolation using `.only()` and run the tests with a fresh validator. Also run the non-live tests.

chore: make legacy connection tests resilient to the validator having just been spun up

---

README.md
packages/webcrypto-ed25519-polyfill/README.md
packages/webcrypto-ed25519-polyfill/src/index.ts

This PR changes the webcrypto polyfill to not use a default export for `install`.
It previously used a default import because `install` is the only export from the library, and that remains true. But this seems to be causing issues that we don't see when we use default exports, so I think it's worth just changing it to export like everything else instead of fighting it.
The rc has no types for the webcrypto library, I'm not sure why. See https://www.npmjs.com/package/@solana/webcrypto-ed25519-polyfill?activeTab=code (dist/types/index.d.ts)
```ts
export {};
//# sourceMappingURL=index.d.ts.map
```
Locally this isn't the case, the type looks correct. I'm guessing it might be a turbocache/some other build thing?
But even if this is fixed, it still doesn't work. Adding the polyfill as a …

Change webcrypto polyfill to not use a default export

---

.changeset/five-sloths-greet.md
packages/webcrypto-ed25519-polyfill/src/__tests__/secrets-test.ts
packages/webcrypto-ed25519-polyfill/src/secrets.ts

This PR enables the crypto polyfill package to export `CryptoKeys` as JSON Web Keys (JWK).
This means the following API will now work with the polyfill as long as we only use the `OKP` (octet key pair) key type and the `Ed25519` curve.
```ts
const { publicKey, privateKey } = await generateKeyPair();
const publicJwk = await crypto.subtle.exportKey('jwk', publicKey);
const privateJwk = await crypto.subtle.exportKey('jwk', privateKey);
```
Note that I used `atob`/`btoa` in order to convert from bytes to base64URL encoded strings as the JWK standard requires. I could have used/modified the more robust `getBase64Codec` but this required importing `@solana/codecs-strings` in the polyfill which felt like an overkill.

Add support for exporting keys as JWK in crypto polyfill

---

.changeset/quiet-hornets-look.md
packages/webcrypto-ed25519-polyfill/src/__tests__/secrets-test.ts
packages/webcrypto-ed25519-polyfill/src/secrets.ts

This PR enables the crypto polyfill package to import JSON Web Keys (JWK) as `CryptoKeys`.
This means the following API will now work with the polyfill as long as we only use the `OKP` (octet key pair) key type and the `Ed25519` curve.
```ts
const publicKey = await crypto.subtle.importKey(
'jwk',
{
crv /* curve */: 'Ed25519',
ext /* extractable */: true,
key_ops /* key operations */: ['verify'],
kty /* key type */: 'OKP' /* octet key pair */,
x /* public key x-coordinate (base64-URL encoded) */: "...",
},
'Ed25519',
true,
['verify'],
);
const privateKey = await crypto.subtle.importKey(
'jwk',
{
crv /* curve */: 'Ed25519',
d /* private key (base64-URL encoded) */: "...",
ext /* extractable */: false,
key_ops /* key operations */: ['sign'],
kty /* key type */: 'OKP' /* octet key pair */,
x …
```

Add support for importing JWK keys in crypto polyfill

---

.changeset/curvy-stingrays-attend.md
packages/keys/README.md
packages/keys/src/__tests__/key-pair-test.ts
packages/keys/src/__typetests__/key-pair-typetests.ts
packages/keys/src/key-pair.ts

This PR adds a `createKeyPairFromPrivateKeyBytes` helper that creates a keypair from the 32-byte private key bytes.
```ts
import { createKeyPairFromPrivateKeyBytes } from '@solana/keys';
const { privateKey, publicKey } = await createKeyPairFromPrivateKeyBytes(new Uint8Array([...]));
```
This can be useful when you have a private key but not the corresponding public key or when you need to derive key pairs from seeds. For instance, the following code snippet derives a key pair from the hash of a message.
```ts
import { getUtf8Encoder } from '@solana/codecs-strings';
import { createKeyPairFromPrivateKeyBytes } from '@solana/keys';
const message = getUtf8Encoder().encode('Hello, World!');
const seed = new Uint8Array(await crypto.subtle.digest('SHA-256', message));
const derivedKeypair = …
```

Add `createKeyPairFromPrivateKeyBytes` helper

---

.changeset/dry-glasses-roll.md
packages/signers/README.md
packages/signers/src/keypair-signer.ts

This PR adds a `createKeyPairSignerFromPrivateKeyBytes` helper that compose `createKeyPairFromPrivateKeyBytes` and `createSignerFromKeyPair`.
It also adds missing documentation for the `createKeyPairSignerFromBytes` function.

Add `createKeyPairSignerFromPrivateKeyBytes` helper

---

.changeset/silent-cooks-marry.md
packages/promises/README.md
packages/promises/src/__tests__/race-test.ts
packages/promises/src/abortable.ts
packages/promises/src/index.ts
packages/promises/src/race.ts

If a member of `Promise.race` never settles, every promise in the race will be retained indefinitely. This causes memory leaks. See https://github.com/nodejs/node/issues/17469 for much more information.
In this PR we fork the excellent work of @brainkim, @danfuzz, and @szakharchenko; a ‘safe’ version of `race` that ensures that each member of the race settles when the winner settles.
See next PR in this stack
Addresses #3069.

An implementation of `Promise.race` that prevents memory leaks

---

.changeset/plenty-plums-drop.md
packages/rpc-subscriptions/package.json
packages/rpc-subscriptions/src/rpc-subscriptions-coalescer.ts
packages/transaction-confirmation/README.md
packages/transaction-confirmation/package.json
packages/transaction-confirmation/src/confirmation-strategy-nonce.ts
packages/transaction-confirmation/src/confirmation-strategy-racer.ts
packages/transaction-confirmation/src/confirmation-strategy-recent-signature.ts
pnpm-lock.yaml

Nearly everything in this library that raced two or more promises together would leak memory if some of those promises never resolved.
One particularly bad case of this was in the subscriptions transport, where an ‘abort promise’ that may never actually abort would be raced with the promise for the next notification message. Unless the abort was eventually called, every promise would be retained forever and memory use would grow unbounded, eventually crashing the process.
Given this test script:
```ts
// test.mjs
import { createSolanaRpcSubscriptions } from "@solana/rpc-subscriptions";
const rpcSubscriptions = createSolanaRpcSubscriptions("ws://127.0.0.1:8900");
const slotMessages = await rpcSubscriptions.slotNotifications().subscribe({
// Never aborted.
abortSignal: AbortSignal.any([]), …
```

Replace all instances of `Promise.race` with a memory-leak-free version

---

.github/workflows/publish-canary-releases.yml
.github/workflows/publish-gh-pages.yml
.github/workflows/publish-packages.yml
.github/workflows/pull-requests.yml
package.json

GitHub Actions runners are anemic, and a new CPU-intensive test has made it impossible for CI to pass: https://github.com/solana-labs/solana-web3.js/actions/runs/10288741934/job/28474891140
I suspect this is because concurrent build tasks result in the CPU being starved for cycles. Let's try to put it back to 1 for CI only.

Build with a concurrency of 1 on CI

---

packages/rpc-spec/README.md

Corrected a duplicated word in the `PendingRpcRequest<TResponse>` section of the [README](https://github.com/solana-labs/solana-web3.js/blob/master/packages/rpc-spec/README.md).

Fix typo in rpc-spec/README.md 

---

.changeset/sixty-months-relate.md
packages/rpc-api/src/__tests__/get-program-accounts-test.ts
packages/rpc-graphql/src/__tests__/program-accounts-test.ts
packages/rpc-graphql/src/loaders/loader.ts
packages/rpc-graphql/src/loaders/program-accounts.ts
packages/rpc-graphql/src/resolvers/program-accounts.ts
packages/rpc-graphql/src/resolvers/resolve-info/program-accounts.ts
packages/rpc-graphql/src/schema/type-defs/root.ts
packages/rpc-graphql/src/schema/type-defs/types.ts
packages/rpc-graphql/src/schema/type-resolvers/types.ts

The filters input parameter for the GraphQL resolver is malformed. This PR brings it to parity with the Solana JSON RPC API as well as the `@solana/rpc-api` package's definition for program accounts filters.
First add some test coverage to `@solana/rpc-api` for program accounts filters to ensure everything is working properly.
Then, refactor the GraphQL API for the `programAccounts` query to correct the program accounts filters input. Finally, add some tests for GraphQL.
Since GraphQL doesn't allow unions as input types, I had to split the two types of filters into two separate filters for the GraphQL API, then coalesce them into the same `filters` argument for the RPC.

refactor(experimental): GraphQL: Refactor program accounts filters

---

src/programs/system.ts

As mentioned in #3118, using `==` or `!=` to compare two `PublicKey` objects will compare their references. This means the conditional will only evaluate to be a match if they are the same object. Additionally, if two build targets or versions of `@solana/web3.js` are being used, these will always be different objects, even if the keys are the same value.
We've encountered the latter issue before, and this appears to be the last place in the legacy library where we still do this conditional without using the `PublicKey.equals` method.
Run a search through the codebase for any public key comparisons using `==` or `!=` and update them to use `PublicKey.equals`. There's only one.
Closes #3118

fix: Compare public key values not references

---

.releaserc.json

As described in https://github.com/semantic-release/release-notes-generator/issues/657, add an override for `conventional-changelog-conventionalcommits` to fix the date parsing issue in semantic release.
The PR to update the dependency within `@commitlint/config-conventional` is still open.

chore: fix publish CI

---

.changeset/weak-peaches-fly.md
packages/keys/src/index.ts

Some complete idiot (me) forgot to export the `public-key` file from the `@solana/keys` package. This PR fixes it. Thanks SolAndy for pointing this out.

Fix missing export in `@solana/keys`

---

packages/rpc-subscriptions-transport-websocket/src/__typetests__/websocket-connection-typetest.ts
packages/rpc-subscriptions-transport-websocket/src/websocket-connection.ts

We want to return `Iterables` from here; it's not important that a generator itself is iterable.

Retrict the type of subscription iterables to `AsyncIterable`

---

packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-coalescer-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-coalescer.ts

What if a custom transport _returns_ its final value? Before this PR, the coalescer would not deliver the final message, if the `done` property and the `value` came in the same iteration.

The subscriptions coalescer now publishes the final message of the inner iterator

---

packages/rpc-api/src/index.ts
packages/rpc-subscriptions-api/src/index.ts

The point of this stack is to make `UnixTimestamp` a `bigint`, therefore it's no longer required to be permitted as `number`. See #3121.

refactor(experimental): remove `UnixTimestamp` from allowed numerical values

---

packages/errors/src/context.ts
packages/rpc-api/src/__typetests__/get-block-type-test.ts
packages/rpc-parsed-types/src/__typetests__/stake-accounts-test.ts
packages/rpc-parsed-types/src/__typetests__/sysvar-accounts-test.ts
packages/rpc-parsed-types/src/__typetests__/vote-accounts-test.ts
packages/rpc-subscriptions-api/src/__typetests__/block-notifications-type-test.ts
packages/rpc-types/src/__tests__/coercions-test.ts
packages/rpc-types/src/__tests__/unix-timestamp-test.ts
packages/rpc-types/src/__typetests__/coercions-typetests.ts
packages/rpc-types/src/unix-timestamp.ts

The Solana JSON RPC uses a Rust `i64` to represent a Unix Timestamp (see https://github.com/anza-xyz/agave/blob/acaf5b7d48e1b630cbaa4abc859393d8f59f0786/sdk/program/src/clock.rs#L169).
Until now, Web3.js was making the following assumptions:
- JavaScript's `Number.MAX_SAFE_INTEGER` (`2 ^ 53 -1`) as a Unix Timestamp lands us in the year 285,422,890.
- JavaScript's `Date` supports integers ranging from `- 8.64e15` to `8.64e15`.
Even though these date values are preposterous, since the RPC server can _technically_ vend a value outside of the ranges for `Number` and `Date`, it doesn't make sense to have these assumptions on the client. Instead, the JavaScript RPC client should exactly match the types that can be returned by the RPC.
For this reason, since the server's `UnixTimestamp` is a …

refactor(experimental): change `UnixTimestamp` to `bigint`

---

packages/errors/src/messages.ts
packages/rpc-types/README.md
packages/rpc-types/src/__tests__/coercions-test.ts
packages/rpc-types/src/__tests__/unix-timestamp-test.ts
packages/rpc-types/src/unix-timestamp.ts

Now that `UnixTimestamp` is a `bigint`, its supported integer range has increased. Following the RPC's limits for Rust's `i64`, the type now supports integer ranges from `- 2^63` to `2^63 - 1`.
https://doc.rust-lang.org/std/primitive.i64.html#associatedconstant.MAX
https://doc.rust-lang.org/std/primitive.i64.html#associatedconstant.MIN

refactor(experimental): adjust `UnixTimestamp` integer range

---

.changeset/gorgeous-foxes-type.md
packages/rpc-api/src/__tests__/get-stake-minimum-delegation-test.ts
packages/rpc-api/src/__tests__/is-blockhash-valid-test.ts
packages/rpc-spec-types/src/rpc-response.ts
packages/rpc-spec/src/rpc.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions.ts

The purpose of this PR stack is to refactor both the RPC and RPC Subscriptions packages such that they have better interfaces with their respective transports. In this first batch of PRs, we will start by focusing on the RPC packages whilst ensuring minimum changes on the RPC Subscriptions packages.
The end goal of this first part is to have the following interfaces for the RPC packages:
```ts
type RpcRequest<TParams = unknown> = {
readonly methodName: string;
readonly params: TParams;
}
type RpcResponse<TResponse = unknown> = {
readonly json: () => Promise<TResponse>;
readonly text: () => Promise<string>;
}
type RpcRequestTransformer = {
<TParams>(request: RpcRequest<unknown>): RpcRequest<TParams>;
};
type RpcResponseTransformer = {
<TResponse>(response: RpcResponse<unknown>, request: …
```

Rename `RpcResponse` to `RpcResponseData`

---

.changeset/fair-brooms-build.md
packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc-request.ts
packages/rpc-spec/src/rpc.ts

In this PR, we continue cleaning up the type namespace by renaming `RpcRequest` to `RpcApiRequestPlan`. This is because:
- `RpcRequest` will be used to define a proper request interface that will unify the RPC layers.
- `RpcApiRequestPlan` better describes what the type actually does. If you call `myRpcApi.myMethod({ foo: 42 })`, then you will be given an object that contains everything you need to send it to a transport without actually sending it to a transport. This is the role of the `Rpc` type which wraps the `RpcApi` proxy and transforms this `RpcApiRequestPlan` into a `PendingRpcRequest` which contains the desired `send` function.

Rename `RpcRequest` to `RpcApiRequestPlan`

---

.changeset/light-bugs-compare.md
packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-shared-test.ts
packages/rpc-spec/src/index.ts
packages/rpc-spec/src/rpc-shared.ts

Now that we've made room for these new types, we add the following:
- `RpcRequest`: The method name and the params are all we need to create a request. Combining them into a single object makes it easier to play with RPC requests. For instance, we can now have a `RpcRequestTransformer` instead of a `RpcParamsTransformer`.
- `RpcResponse`: This is the response abstraction that all the layers of the RPC packages will use moving forward. Instead of a simple `unknown` piece of data, the `RpcResponse` object contains two async methods:
- `json`: Returns the parsed piece of data.
- `text`: Returns the unparsed piece of data (as a string).
- `RpcRequestTransformer` and `RpcResponseTransformer`: Functions that take a request/response and return a new request/response respectively. Note that the …

Add new `RpcRequest`, `RpcResponse` types and their transformer types

---

.changeset/stupid-tomatoes-reflect.md
packages/rpc-api/src/__tests__/get-health-test.ts
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-transport.ts
packages/rpc-spec/src/rpc.ts
packages/rpc-transport-http/README.md
packages/rpc-transport-http/src/__tests__/http-transport-abort-test.ts
packages/rpc-transport-http/src/http-transport.ts
packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
packages/rpc/src/rpc-request-coalescer.ts

This PR updates the RPC Transport layer by making sure they return the new `RpcResponse` interface instead of returning the parsed response data directly.

Update RPC transports to use new types

---

.changeset/metal-spoons-matter.md
packages/rpc-api/src/index.ts
packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-api-test.ts
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc.ts
packages/rpc-subscriptions-api/src/index.ts
packages/rpc-transformers/src/__tests__/params-transformer-test.ts
packages/rpc-transformers/src/__tests__/response-transformer-test.ts
packages/rpc-transformers/src/params-transformer.ts
packages/rpc-transformers/src/response-transformer.ts

This PR updates the RPC Api layer such that they use the new `RpcRequest`, `RpcResponse`, `RpcRequestTransformer` and `RpcResponseTransformer` types.
Note that I had to duplicate the implementation of `getDefaultResponseTransformerForSolanaRpc` into `getDefaultResponseTransformerForSolanaRpcSubscriptions` in order to leave RPC Subscription packages unaffected by the refactoring. These will have their own dedicated PR stack further down the line.

Update RPC APIs to use new types

---

packages/rpc-spec/src/__tests__/rpc-api-test.ts
packages/rpc-spec/src/rpc-shared.ts

This PR fixes a previous mistake on this stack by moving the `TParam` generic type parameter from the `RpcRequest` return type to the `RpcRequest` argument.
```ts
// Before.
<TParams>(request: RpcRequest) => RpcRequest<TParams>;
// After.
<TParams>(request: RpcRequest<TParams>) => RpcRequest;
```
This is because when transforming requests, we want to assert on what we are getting. Whereas, when transforming responses, we want to assert on what we are returning. Note that this is how the parameter transformer used to work before this stack.

Use `RpcRequestTransformer` type parameter on request argument

---

packages/rpc-transformers/src/__tests__/request-transformer-test.ts
packages/rpc-transformers/src/index.ts
packages/rpc-transformers/src/request-transformer.ts

This PR refactors the internal fix for issue 479 as a request transformer called `getFixForIssue479RequestTransformer`. this is part of a series of effort to extract all transformers into their own helper so the default transformer can be a simple composition of all of them.

Refactor fix for issue 479 as a transformer

---

packages/rpc-spec/README.md
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc-shared.ts

This PR combines the `RpcResponseTransformer` and `RpcResponseTransformerFor` types by using an optional type parameter.
Initially, `RpcResponseTransformer` was defining a generic function (as opposed to a generic type that applies its type parameter to the function). However, this was only needed in the `rpc-api` file to do:
```ts
config.responseTransformer<TypeExpectationHere>;
```
The same can be achieved using:
```ts
config.responseTransformer as RpcResponseTransformer<TypeExpectationHere>;
```
Without loosening any types as `config.responseTransformer<T>` was equivalent to a type-cast.
This makes it less tedious to define response transformers as we don't have to always cast our return type to an abstract type `T` even when we know the real return type.

Combine `RpcResponseTransformer` and `RpcResponseTransformerFor`

---

.changeset/light-owls-own.md
packages/rpc-transformers/README.md
packages/rpc-transformers/src/index.ts
packages/rpc-transformers/src/response-transformer-bigint-upcast.ts
packages/rpc-transformers/src/response-transformer-result.ts
packages/rpc-transformers/src/response-transformer-throw-solana-error.ts
packages/rpc-transformers/src/response-transformer.ts
packages/rpc-transformers/src/tree-traversal.ts

This PR refactors the `getDefaultResponseTransformerForSolanaRpc` function by creating four new response transformers and delegating to them:
- `getThrowSolanaErrorResponseTransformer`: Throws a `SolanaError` if the RPC response is an error.
- `getResultResponseTransformer`: Access the `result` attribute of the RPC response.
- `getBigIntUpcastResponseTransformer`: Upcasts all numeric values to bigints unless they are within the provided allowed keypaths.
- `getTreeWalkerResponseTransformer`: Helper that creates response transformers from visitors.

Add more response transformers

---

.github/workflows/publish-gh-pages.yml
.github/workflows/pull-requests.yml

See discussion at https://github.com/actions/upload-artifact/issues/602.

Repair documentation site after Microsoft's breaking change to `upload-artifact`

---

.changeset/ten-buckets-search.md
packages/rpc-api/src/__tests__/get-cluster-nodes-test.ts
packages/rpc-api/src/getClusterNodes.ts

This PR updates the response's type and test expectations of the `getClusterNodes` RPC method to keep it in sync with the latest RPC changes.
See https://github.com/anza-xyz/agave/pull/1637

Update `getClusterNodes` response

---

.changeset/plenty-eyes-kick.md
packages/rpc-api/src/getRecentPerformanceSamples.ts

`PerformanceSample` type, used to define the return values from the `getRecentPerformanceSamples` RPC Method incorrectly includes a `numNonVoteTransaction` field but the RPC call itself returns `numNonVoteTransactions` (with an "s").
In the core the fields called [`num_non_vote_transactions`](https://github.com/solana-labs/solana/blob/master/core/src/sample_performance_service.rs#L84) but you can see it should be mapped to `numNonVoteTransactions`, as [tested here](https://github.com/solana-labs/solana/blob/master/rpc-client-api/src/response.rs#L614). The pluralise spelling is also consistent with the other fields (`numSlots`, `numTransactions`, etc.).
And, of course, `numNonVoteTransactions` is what's actually being returned. See for yourself:
```sh
curl https://api.devnet.solana.com -X …
```

Fixing misnamed field in `PerformanceSample` return type

---

.changeset/beige-files-travel.md
packages/rpc-subscriptions-api/src/__tests__/index-test.ts
packages/rpc-subscriptions-api/src/__typetests__/rpc-subscriptions-api-type-test.ts
packages/rpc-subscriptions-api/src/account-notifications.ts
packages/rpc-subscriptions-api/src/block-notifications.ts
packages/rpc-subscriptions-api/src/logs-notifications.ts
packages/rpc-subscriptions-api/src/program-notifications.ts
packages/rpc-subscriptions-api/src/root-notifications.ts
packages/rpc-subscriptions-api/src/signature-notifications.ts
packages/rpc-subscriptions-api/src/slot-notifications.ts
packages/rpc-subscriptions-api/src/slots-updates-notifications.ts
packages/rpc-subscriptions-api/src/vote-notifications.ts
packages/rpc-subscriptions-spec/src/__typetests__/rpc-subscriptions-api-typetest.ts
packages/rpc-subscriptions-spec/src/__typetests__/rpc-subscriptions-typetest.ts

Same idea as #3213 but for subscriptions
Also added a typetest to verify that keys of RpcSubscriptions are now correctly typed

Clean up SolanaRpcSubscriptionsApi: no longer extend RpcApiSubscriptionsMethods 

---

.changeset/tasty-cups-think.md
packages/rpc-transformers/src/__tests__/request-transformer-test.ts
packages/rpc-transformers/src/request-transformer.ts

This PR removes the temporary request transformer that was waiting for [this PR](https://github.com/anza-xyz/agave/pull/483) to be merged and available on mainnet-beta.

Remove temporary fix for Agave issue 479

---

.changeset/slow-dragons-add.md
packages/rpc-transport-http/README.md
packages/rpc-transport-http/src/__tests__/http-transport-from-json-test.ts
packages/rpc-transport-http/src/__tests__/http-transport-to-json-test.ts
packages/rpc-transport-http/src/http-transport.ts

This PR adds two new optional functions to the `createHttpTransport` configs.
- `fromJson`: When provided, replaces the logic that transforms the response from a JSON string into a JSON value.
- `toJson`: When provided, replaces the logic that transforms the request payload from a JSON value into a JSON string.
This will enable us to wrap this transport and create a new Solana-RPC-specific HTTP transport that do not loose range/precision when `bigint` values are transmitted over the wire.

Add `fromJson` and `toJson` options to HTTP transport

---

packages/rpc-transport-http/src/__tests__/stringify-json-with-bigints-test.ts
packages/rpc-transport-http/src/stringify-json-with-bigints.ts

This PR adds a new `stringifyJsonWithBigInts` helper function that supports rendering `bigints` as unsafe numerical values.
This will be used — in a subsequent PR — to create a new Solana-RPC-specific HTTP transport that prevents loss of precision for large integers, in both the request and the response of the RPC cycle.

Add `stringifyJsonWithBigInts` helper

---

.changeset/bright-snakes-search.md
packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-transport-test.ts
packages/rpc-spec/src/__typetests__/rpc-transport-typetest.ts
packages/rpc-spec/src/rpc-transport.ts
packages/rpc/src/rpc-request-deduplication.ts

This PR extracts and exposes the `isJsonRpcPayload` helper method into the `rpc-spec` package. This is because we're going to need this function in multiple places going forward in order to inspect in a given `unknown` payload is a JSON RPC one (with a method name and parameters).

Extract `isJsonRpcPayload` method to `rpc-spec`

---

packages/rpc-transport-http/src/__tests__/is-solana-request-test.ts
packages/rpc-transport-http/src/is-solana-request.ts

This PR adds a new `isSolanaRequest` helper function that checks if a given `RpcRequest` comes from the Solana RPC API.
This will be used — in a subsequent PR — to create a new Solana-RPC-specific HTTP transport that prevents loss of precision for large integers.

Add `isSolanaRequest` helper

---

.changeset/forty-ravens-train.md
packages/rpc-transport-http/README.md
packages/rpc-transport-http/src/__tests__/http-transport-for-solana-rpc-test.ts
packages/rpc-transport-http/src/http-transport-for-solana-rpc.ts
packages/rpc-transport-http/src/index.ts

This PR creates a new HTTP transport specific to the Solana RPC API that prevents loss of precision for large integers, in both the request and the response of the RPC cycle.
It does so by using the previously added helpers:
- `isSolanaRequest`: to figure out if we should customise the way we parse/stringify the response/request respectively.
- `parseJsonWithBigInts`: for our custom `fromJson` option, if a Solana request has been identified.
- `stringifyJsonWithBigInts`: for our custom `toJson` option, if a Solana request has been identified.

Add `createHttpTransportForSolanaRpc` function

---

packages/errors/src/context.ts
packages/rpc-api/src/__tests__/__setup__.ts
packages/rpc-api/src/__tests__/get-account-info-test.ts
packages/rpc-api/src/__tests__/get-balance-test.ts
packages/rpc-api/src/__tests__/get-block-height.ts
packages/rpc-api/src/__tests__/get-epoch-info-test.ts
packages/rpc-api/src/__tests__/get-fee-for-message-test.ts
packages/rpc-api/src/__tests__/get-inflation-reward-test.ts
packages/rpc-api/src/__tests__/get-latest-blockhash-test.ts
packages/rpc-api/src/__tests__/get-multiple-accounts-test.ts
packages/rpc-api/src/__tests__/get-program-accounts-test.ts
packages/rpc-api/src/__tests__/get-signatures-for-address-test.ts
packages/rpc-api/src/__tests__/get-slot-leader-test.ts
packages/rpc-api/src/__tests__/get-slot-test.ts
packages/rpc-api/src/__tests__/get-stake-activation-test.ts
packages/rpc-api/src/__tests__/get-token-accounts-by-delegate-test.ts
packages/rpc-api/src/__tests__/get-token-accounts-by-owner-test.ts
packages/rpc-api/src/__tests__/get-transaction-count-test.ts
packages/rpc-api/src/__tests__/send-transaction-test.ts
packages/rpc-api/src/__tests__/simulate-transaction-test.ts
packages/rpc-transformers/src/response-transformer-bigint-upcast.ts
packages/rpc-transport-http/src/http-transport-for-solana-rpc.ts
packages/rpc/src/__tests__/rpc-transport-header-config-test.ts
packages/rpc/src/rpc-transport.ts

This PR uses the brand new `createHttpTransportForSolanaRpc` function within the default transport for Solana RPCs.

Use `createHttpTransportForSolanaRpc` in default transport

---

packages/rpc-api/src/getBlock.ts
packages/rpc-subscriptions-api/src/block-notifications.ts

The documentation for `blockTime` is a duplicate of `blockHeight`.
Change it to the correct documentation from the [RPC docs](https://solana.com/docs/rpc/http/getblock).
Closes #3228

chore: update `blockTime` doc

---

packages/rpc-spec/src/__tests__/rpc-api-test.ts
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc.ts

This PR removes the unnecessary `request` argument from the API plan's `responseTransformer` function. This is because the plan already knows the `request` so it can inject it to the `responseTransformer` provided in its config.

Remove request arg in API plan's response transformer

---

.changeset/small-cougars-smoke.md
packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-api-test.ts
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc.ts

This PR alters the boundaries of the RPC API layer by making the `RpcApiRequestPlan` return a `payload` of type `unknown` instead of `methodName` and `params`. This means, it is now the responsibility of the RPC API to crunch the request into a payload. The outer RPC layer now simply need to forward that `payload` to the RPC transport.

Make API plans return payloads

---

.changeset/warm-dolls-yell.md
README.md
packages/rpc-api/src/index.ts
packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-api-test.ts
packages/rpc-spec/src/__typetests__/rpc-api-typetest.ts
packages/rpc-spec/src/__typetests__/rpc-typetest.ts
packages/rpc-spec/src/rpc-api.ts

This PR renames `createRpcApi` to `createJsonRpcApi` since this function is now responsible for converting the `RpcRequest` into a `payload` compatible with the JSON RPC v2 spec.

Rename `createRpcApi` to `createJsonRpcApi`

---

packages/addresses/src/__tests__/address-test.ts
packages/addresses/src/address.ts

When supplied with a non-base58 encoded string the function would unexpectedly throw. 
This PR updates it to return `false` instead and adds similar tests as `assertIsAddress`

Update `isAddress` to not throw

---

packages/rpc-api/src/getFeeForMessage.ts

Looking at server code this is definitely measured in Lamports, seems more helpful to use that type here

Change return type of getFeeForMessage to Lamports

---

packages/subscribable/src/__typetests__/data-publisher-typetest.ts
packages/subscribable/src/data-publisher.ts

My final change to #3301 caused some pretty structural damage to the consumers of this type. We'll have to try again later.

Revert ‘no argument’ conditional type from #3301

---

packages/rpc-subscriptions/README.md
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-json-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-json.ts

The new web socket channel speaks in strings/buffers. For general use in the JSON RPC Subscriptions API we need it to take in JavaScript objects, send JSON strings over the wire, and parse the strings that come back as JSON.
This is a higher-order component that wraps a `RpcSubscriptionsChannel` that speaks in strings, and makes it speak in JavaScript objects.

A channel augmenter that encodes and decodes messages as JSON

---

packages/rpc-subscriptions/README.md
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-channel-pool-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-channel-pool-internal.ts
packages/rpc-subscriptions/src/rpc-subscriptions-channel-pool.ts

This is a special `RpcSubscriptionsChannelCreator` that creates a pool of underlying channels up to `minChannels`, reuses them evenly up to `maxSubscriptionsPerChannel`, and tears the channels down when all of its subscribers abort.

A channel pool

---

packages/subscribable/README.md
packages/subscribable/src/__tests__/demultiplex-test.ts
packages/subscribable/src/demultiplex.ts
packages/subscribable/src/index.ts

In this PR, we create an efficient way of fanning notifications out to the subscribers that care about them. Instead of making _every_ subscriber responsible for transforming the response and dropping the ones it's not interested in, we make this demultiplexer transform the payload at the source, and publish it to a new channel with the subscriber id in it.

A channel message demultiplexer

---

packages/rpc-subscriptions-spec/README.md
packages/rpc-subscriptions-spec/package.json
packages/rpc-subscriptions-spec/src/__tests__/rpc-subscriptions-pubsub-plan-test.ts
packages/rpc-subscriptions-spec/src/index.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions-pubsub-plan.ts
pnpm-lock.yaml

There is a song and dance that you need to do with the server to set up a subscription, like making a request for a specially named method, waiting for the subscription id to come back in the response, and then listening for notifications having that subscription id. This `RpcSubscriptionsPlan` implements all of that.

A subscription plan that implements the Solana JSON WebSocket subscription API

---

packages/rpc-subscriptions/README.md
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-autopinger-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-autopinger.ts

RPC web socket channels will go down if there hasn't been any chatter over the wire in a while. This higher-order function wraps a channel, and sends a ping message if there has been no activity in `intervalMs`.

A channel augmenter that autopings the channel

---

pnpm-lock.yaml

1. Add `"rollup": "^4.24.0"` to `"overrides"`
2. `pnpm i`
3. Remove the override
Don't know why it works, but it does.

Update `rollup` to 4.24.0

---

.changeset/six-olives-hang.md
packages/rpc-transport-http/src/__tests__/http-transport-headers-test.ts
packages/rpc-transport-http/src/http-transport-headers.ts
packages/rpc/src/__tests__/rpc-transport-header-config-test.ts
packages/rpc/src/rpc-transport.ts

The `fetch` API in browsers automatically requests the wire compression encoding that the browser supports, in the order it wants it. Node's `fetch` API does not.
In this PR we add all of the default algorithms supported by Node LTS at the time of writing.
Closes #3338.
1. Install Node LTS (`n lts`)
2. Test that it actually supports these
```
> await (await fetch('https://httpbin.org/deflate', {headers:{'Accept-Encoding': 'deflate', 'Content-Type': 'application/json'}})).json()
{
deflated: true,
headers: {
Accept: '*/*',
'Accept-Encoding': 'deflate',
'Accept-Language': '*',
'Content-Type': 'application/json',
Host: 'httpbin.org',
'Sec-Fetch-Mode': 'cors',
'User-Agent': 'node',
'X-Amzn-Trace-Id': 'Root=1-67020914-22d36c347b3b8b0f356d9a98'
},
method: 'GET',
origin: '145.40.88.235'
}
> await …
```

The default RPC transport now requests wire compression in Node

---

packages/rpc-transport-http/src/__benchmarks__/run.ts

The noted issue was fixed in `undici`.

Enable HTTP/2 benchmarks in `rpc-transport-http`

---

packages/build-scripts/package.json
packages/build-scripts/register-node-globals.cjs
packages/codecs-core/src/__benchmarks__/run.ts
packages/codecs-strings/src/__benchmarks__/run.ts
packages/fetch-impl/src/__benchmarks__/run.ts
packages/keys/src/__benchmarks__/run.ts
packages/rpc-transport-http/src/__benchmarks__/run.ts

Because we moved a build-time contstant to the top level in #3340, we can no longer run these scripts without replacing the build time constants. That means that running this with `tsx` will yield a `__NODEJS__ is not defined` error.
In this PR, we change the benchmarks to run on the built source, and teach Turborepo to build it beforehand. You now run benchmarks with `pnpm turbo benchmark`.

Repair benchmarks

---

.changeset/forty-bananas-bow.md
packages/transaction-confirmation/src/__tests__/confirmation-strategy-blockheight-test.ts
packages/transaction-confirmation/src/confirmation-strategy-blockheight.ts

I noticed that my application was getting blockheight exceedence errors when there definitely was not one. Turns out the reason was because my application was aborting the confirmation, which would cause all of this code to fall through to the `BLOCKHEIGHT_EXCEEDENCE` exception.
This PR introduces a throw of the abort after every `await`. After this change, this existing text becomes consequential:
https://github.com/solana-labs/solana-web3.js/blob/e9d137651792172e16548ec9e8bbd6824c9e7189/packages/transaction-confirmation/src/__tests__/waiters-test.ts#L146-L157

Prevent false blockheight exceedence errors when transaction confirmations are aborted

---

packages/rpc-subscriptions/README.md
packages/rpc-subscriptions/package.json
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-coalescer-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-coalescer.ts
packages/rpc-subscriptions/src/rpc-subscriptions-transport.ts
pnpm-lock.yaml

Given two identical subscriptions, we should not send the request to the server twice. This higher-order transport watches for identical subscriptions over the same transport and returns the same `DataPublisher` to both.
> [!NOTE]
> It is true that the server coalesces subscriptions on the backend, but coalescing them on the client is still worthwhile in that it reduces chatter over the wire (ie. the subsequent subscription requests don't even get made) and speeds up subscription time on the client for identical subscriptions.

A subscriptions transport coalescer

---

packages/rpc-subscriptions-channel-websocket/src/__tests__/websocket-channel-test.ts
packages/rpc-subscriptions-channel-websocket/src/websocket-channel.ts

Before this PR, we were only publishing `error` messages through the websocket channel when the disconnection was ‘unclean.’ We _also_ want to publish errors from the remote end when the connection closed cleanly, but for a reason other than we asked it to. One example of this could be a ‘rate limit’ error.

Publish errors through the web socket channel for clean errors other than ‘normal closure’

---

packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
packages/rpc/src/rpc-request-coalescer.ts

The `queueMicrotask` API is well-supported enough now to use for this use case. https://caniuse.com/mdn-api_queuemicrotask

Replace abuse of promises with the `queueMicrotask` API in the RPC request coalescer

---

packages/rpc-subscriptions/README.md
packages/rpc-subscriptions/src/rpc-subscriptions-channel.ts

When you make ‘too many’ subscriptions over a single channel/connection/socket, RPC providers will throw errors. The idea behind this PR is to set the default subscriptions-per-channel low enough so as to avoid running afoul of even the most restrictive provider's limit.
This was determined experimentally by hitting various nodes with [this script](https://gist.github.com/steveluscher/717d3ac535e862314ae3f9f4d0310c14).
- Triton Public Mainnet (`api.mainnet-beta.solana.com`): 100
- Helius: ~1450
- QuickNode: ~4500
The ground truth is this:
1. Some nodes have definite limits set, like the public Triton mainnet node.
2. Some nodes _don't_ have limits set, but unceremoniously close the connection _roughly_ around the same number of subscriptions.
The right thing to do here would be for …

Configure the channel pool to open a new channel when all of the currently open channels reach 100 subscriptions each

---

src/connection.ts

Some message from websocket contain error 
```json
{
"id": 59,
"jsonrpc": "2.0",
"error": {
"code": -32601,
"message": "Subscriptions unsupported for this network"
}
}
```
Which not present any where, just add console log for represent error for developer

fix: cover logs error for ws message

---

.github/workflows/pull-requests.yml

**Context**: Two days ago Node officially released version 23 and updated the `Current` alias to point to this new stable version.
**Problem**: This is causing our CI to fail in the following way: when running Jest unit tests, we get `No tests found, exiting with code 1`.
It looks like `testMatch` gets some matches but `testRegex` no longer does. The reason this only starts failing in PRs (and not on the `master` branch) is because of Turbo caching. I tested this by created a new PR that only adds a comment to a package and that package CI now fails.
**Workaround**: One temporary workaround is to comment out the current version on the CI Node matrix until Node v23 and Jest learn how to play nicely with each other. This is what this PR does.

Temporarily disable Node 23 CI tests

---

packages/rpc-subscriptions-spec/src/rpc-subscriptions-request.ts

This PR removes the `RpcSubscriptionsRequest` which was used in the previous implementation of RPC Subscriptions but no longer is.

Remove unused RpcSubscriptionsRequest type

---

.changeset/giant-seals-mix.md
packages/library/package.json
packages/library/src/index.ts
packages/rpc-spec-types/README.md
packages/rpc-spec-types/src/index.ts
packages/rpc-spec-types/src/rpc-request.ts
packages/rpc-spec-types/src/rpc-response.ts
packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-api-test.ts
packages/rpc-spec/src/index.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc-transport.ts
packages/rpc-transformers/package.json
packages/rpc-transformers/src/__tests__/request-transformer-test.ts
packages/rpc-transformers/src/__tests__/response-transformer-test.ts
packages/rpc-transformers/src/request-transformer-default-commitment.ts
packages/rpc-transformers/src/request-transformer-integer-overflow.ts
packages/rpc-transformers/src/request-transformer.ts
packages/rpc-transformers/src/response-transformer-result.ts
packages/rpc-transformers/src/response-transformer-throw-solana-error.ts
packages/rpc-transformers/src/response-transformer.ts
packages/rpc-transformers/src/tree-traversal.ts
packages/rpc-transport-http/README.md
packages/rpc-transport-http/package.json
packages/rpc-transport-http/src/http-transport.ts
packages/rpc/package.json
packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
packages/rpc/src/rpc-request-coalescer.ts
pnpm-lock.yaml

One of the goals of this stack is to eventually make `RpcRequestTransformers` and `RpcResponseTransformers` usable on both RPC and RPC Subscriptions architectures. This was the original intention of the `rpc-transformers` package which already hosts request and response transformers for both but with inconsistent types.
As such, this PR aims to get closer to this goal by moving the `RpcRequest`, `RpcResponse`, `RpcRequestTransformer` and `RpcResponseTransformer` types from the `rpc-spec` package to the `rpc-spec-types` package.
As a reminder the `rpc-spec` and `rpc-subscriptions-spec` packages define the interfaces of the RPC and RPC Subscriptions architectures respectively, whereas, the `rpc-spec-types` package is a utility package that is imported by both of the former packages.
Note …

Move RpcRequest and RpcResponse types to rpc-spec-types

---

.changeset/wet-colts-exist.md
packages/rpc-spec-types/src/__tests__/rpc-message-test.ts
packages/rpc-spec-types/src/rpc-message.ts
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions-pubsub-plan.ts

This PR changes the arguments of the `createRpcMessage` helper function so that it accepts an `RpcRequest` directly instead of accepting all the components inside a request (i.e. `methodName` and `params`).
We discussed this a little while ago with @mcintyre94 as, without this change, you sometimes need to express a request as an object and sometimes as its deconstructed version. This PR stack aims to embrace the `RpcRequest` object wherever applicable.

Use RpcRequest in createRpcMessage helper

---

packages/rpc-subscriptions-api/src/__tests__/index-test.ts
packages/rpc-subscriptions-api/src/index.ts
packages/rpc-subscriptions-spec/README.md
packages/rpc-subscriptions-spec/src/__tests__/rpc-subscriptions-pubsub-plan-test.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions-pubsub-plan.ts

This PR changes the configs of the `executeRpcPubSubSubscriptionPlan` function such that it accepts a "Subscribe Request" as a `RpcRequest` object instead of a `subscribeMethodName` and `subscribeParams` duo.
This mean we can now use the `RpcRequestTransformer` provided in a more idiomatic way.
Note: A changeset for this PR is included in https://github.com/solana-labs/solana-web3.js/pull/3407.

Use RpcRequest in PubSubSubscriptionPlan

---

packages/rpc-subscriptions-spec/src/rpc-subscriptions-pubsub-plan.ts
packages/rpc-transformers/src/response-transformer.ts

This PR refactors the definition of a Response Transformer in the RPC Subscriptions architecture from `<T>(response: unknown, notificationName: string) => T;` to `RpcResponseTransformer`.
That way, both the RPC and RPC Subscriptions architectures use the same interfaces for transforming requests and responses which means we can refactoring helper method like `getDefaultResponseTransformerForSolanaRpcSubscriptions` in a more composable way (using the `pipe` function like we did with default RPC Response Transformer).
Note: A changeset for this PR is included in https://github.com/solana-labs/solana-web3.js/pull/3407.

Use RpcResponseTransformer in PubSubSubscriptionPlan

---

packages/rpc-subscriptions-api/src/index.ts
packages/rpc-subscriptions-spec/src/__tests__/rpc-subscriptions-api-test.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions-api.ts

This PR replaces the `notificationName` and `params` arguments of the `RpcSubscriptionsPlanExecutor` function by a single `request` argument of type `RpcRequest`. This request argument is meant to represent the user intent to request a subscription from the RPC Subscriptions packages.
Note: A changeset for this PR is included in https://github.com/solana-labs/solana-web3.js/pull/3407.

Use RpcRequest in PlanExecutor configs

---

.changeset/cool-bears-taste.md

This PR adds a changeset combining several smaller changes in the previous PRs of this stack. That way, we provide a slightly more digest changelog.

Add changeset for using RpcRequest and RpcResponse in RPC Subscriptions

---

.changeset/silly-wombats-switch.md
packages/rpc-subscriptions-api/package.json
packages/rpc-subscriptions-api/src/index.ts
packages/rpc-subscriptions-spec/src/__tests__/rpc-subscriptions-api-test.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions-api.ts
packages/rpc-subscriptions/README.md
packages/rpc-subscriptions/package.json
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-coalescer-test.ts
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-transport-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-coalescer.ts
pnpm-lock.yaml

This PR replaces the `subscriptionConfigurationHash` attribute from the `RpcSubscriptionsPlan` type by a `request` attribute of type `RpcRequest` representing the user intent to request to an RPC Subscription.
The main issue with having a `subscriptionConfigurationHash` attribute defined in the interfaces of RPC Subscriptions is that it is mainly useful to create a coalescer transport decorator and, therefore, is application-specific. By providing the full `RpcRequest` instead, transports can decide to use this information however they see fit. For instance, a coalescer transport may hash all of the request data whereas a sharding transport may only use the method name of the request. Notice how the `@solana/fast-stable-stringify` package has now moved from the API package to the package …

Replace subscriptionConfigurationHash with RpcRequest in RpcSubscriptionsPlan

---

packages/rpc-spec/src/rpc-transport.ts

This stack aims to change the interfaces of the RPC API layer in a way that not only simplifies the RPC API boundaries but also allows the RPC API to do more than it currently can.
This change was inspired by the new RPC Subscriptions API design which offers a plan executor function instead of a data object. As such, this stack will make the RPC architecture more consistent with the RPC Subscriptions architecture.
Here are two diagrams showing the current state of the RPC architecture and the proposed state implemented by this stack.
As you can see, the new implementation simplifies the interfaces by wrapping the RPC Transport layer inside the RPC API layer. This enables the RPC API do things like: not calling the transport at all for caching purposes or calling the transport multiple …

Rename internal `RpcTransportRequest` type to `Config`

---

.changeset/flat-ways-love.md
packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc.ts

This PR renames the `RpcApiRequestPlan` type to `RpcPlan` in order to stay consistent with the `RpcSubscriptionsPlan` of the RPC Subscriptions architecture.

Rename `RpcApiRequestPlan` to `RpcPlan`

---

packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-api-test.ts
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts

Now we're getting in the fun bit.
This PR adds an `execute` function to the `RpcPlan` type whose entire purpose is to dictate how the request should be forwarded to the transport and how its response should be transformed.
Note that the following PR will remove the `payload` and `responseTransformer` attributes from the plan as they are no longer necessary.
Also note that a follow-up PR will add a changeset for these changes.

Add `execute` function to `RpcPlan`

---

packages/rpc-spec/README.md
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-spec/src/rpc-api.ts
packages/rpc-spec/src/rpc.ts

This PR replaces the usage of `payload` and `responseTransformer` in favour of the new `execute` function.
Note that, this PR removes some `responseTransformer`-specific tests from the RPC tests since the outer RPC layer no longer cares about transformers. This is fine since we’re already got `responseTransformer` tests for the `createJsonRpcApi` function.
Also note that a follow-up PR will add a changeset for these changes.

Remove `payload` and `responseTransformer` from `RpcPlan`

---

.changeset/tricky-walls-doubt.md
packages/rpc-subscriptions-api/src/__tests__/__setup__.ts
packages/rpc-subscriptions-api/src/__tests__/index-test.ts
packages/rpc-subscriptions-spec/src/__tests__/rpc-subscriptions-api-test.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions-api.ts
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-coalescer-test.ts
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-transport-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-transport.ts

This PR renames the `executeSubscriptionPlan` function of the `RpcSubscriptionsPlan` type to `execute` to be consistent with the `RpcPlan`. This means we can now call the plan by running `subscriptionsPlan.execute(...)` instead of the more redundant `subscriptionsPlan.executeSubscriptionPlan(...)`.

Rename `executeSubscriptionPlan` to `execute` in `RpcSubscriptionsPlan`

---

pnpm-lock.yaml

Had to lock these versions because of https://github.com/radix-ui/themes/issues/619.

Fix Radix menus in React example

---

.github/workflows/pull-requests.yml

Node 23.1.0 is out.
Reverts solana-labs/solana-web3.js#3395

Revert "Temporarily disable Node 23 CI tests"

---

package.json
packages/crypto-impl/package.json
packages/ws-impl/package.json
pnpm-lock.yaml
turbo.json

Apparently `types` does not get used if it comes after `require` or `imports` here. A warning from `tsup` led me here.

Put `types` before `require` and `import` in `exports`

---

examples/react-app/src/context/ChainContext.tsx
examples/react-app/src/context/ChainContextProvider.tsx
examples/react-app/src/context/RpcContext.tsx
examples/react-app/src/context/RpcContextProvider.tsx
examples/react-app/src/context/SelectedWalletAccountContext.tsx
examples/react-app/src/context/SelectedWalletAccountContextProvider.tsx
examples/react-app/src/main.tsx

See https://github.com/ArnaudBarre/eslint-plugin-react-refresh/issues/53.

Make React context in the example app work with hot module replacement

---

.changeset/late-ravens-cross.md
packages/rpc-subscriptions-spec/README.md
packages/rpc-subscriptions-spec/src/__tests__/rpc-subscriptions-channel-test.ts
packages/rpc-subscriptions-spec/src/rpc-subscriptions-channel.ts

This PR adds the following two helper functions for `RpcSubscriptionsChannels`:
- `transformChannelInboundMessages(channel, transform)`: returns a new channel such that incoming messages are going through the provided transform function. Note that this does not affect incoming error messages.
- `transformChannelOutboundMessages(channel, transform)`: returns a new channel such that outgoing messages are going through the provided transform function.
These helper functions will be used in a follow-up refactoring.

Add helpers to transform channel messages

---

packages/rpc-subscriptions/src/rpc-subscriptions-json.ts

This PR uses the new `transformChannelInboundMessages` and `transformChannelOutboundMessages` helpers to refactor the existing `getRpcSubscriptionsChannelWithJSONSerialization` function.

Use channel message transformers for JSON serialization

---

.changeset/rotten-sloths-raise.md
packages/rpc-subscriptions/README.md
packages/rpc-subscriptions/package.json
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-json-bigint-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-json-bigint.ts
pnpm-lock.yaml

This PR adds a new `getRpcSubscriptionsChannelWithBigIntJSONSerialization` function that acts the same as the existing `getRpcSubscriptionsChannelWithJSONSerialization` function except that it uses the `parseJsonWithBigints` and `stringifyJsonWithBigints` function internally instead of the native `JSON.parse` and `JSON.stringify`.

Add JSON channel decorator with BigInt support

---

packages/rpc-subscriptions/src/rpc-subscriptions.ts

This PR removes the unused `DefaultRpcSubscriptionsTransportConfig` type from the `DefaultRpcSubscriptionsConfig` type. The former simply provides a `createChannel` attribute that is never used within the default subscription helpers because they provide their own `createChannel` to the underlying default transport.

Fix unused `createChannel` option

---

.changeset/orange-squids-think.md
README.md
packages/rpc-subscriptions/README.md
packages/rpc-subscriptions/src/rpc-subscriptions-channel.ts
packages/rpc-subscriptions/src/rpc-subscriptions.ts

This PR offers a new `createDefaultSolanaRpcSubscriptionsChannelCreator` function that works similarly to `createDefaultRpcSubscriptionsChannelCreator` but with some Solana-specific defaults.
Namely, it uses the brand new `getRpcSubscriptionsChannelWithBigIntJSONSerialization` function to stringify and parse messages to and from the server.

Use BigInt JSON serialization in Solana RPC Subscriptions

---

.changeset/red-moose-flash.md
examples/signers/src/example.ts
packages/library/src/__tests__/compute-limit-internal-test.ts
packages/signers/src/__tests__/fee-payer-signer-test.ts
packages/signers/src/fee-payer-signer.ts
packages/transaction-messages/src/__tests__/decompile-message-test.ts
packages/transaction-messages/src/__tests__/fee-payer-test.ts
packages/transaction-messages/src/compile/__tests__/message-test.ts
packages/transaction-messages/src/compile/message.ts
packages/transaction-messages/src/fee-payer.ts

This PR changes the `feePayer` type for transaction messages from `Address` to `{ address: Address }`. This allows us, in a follow-up PR, to use the same `feePayer` attribute to store `TransactionSigners` which, in turn, allows us to override `TransactionSigners` with non-signer fee payers and vice-versa.
Addresses https://github.com/solana-labs/solana-web3.js/issues/2899.

Wrap `feePayer` attribute in an object

---

.changeset/violet-eggs-whisper.md
packages/signers/src/__tests__/account-signer-meta-test.ts
packages/signers/src/__tests__/fee-payer-signer-test.ts
packages/signers/src/account-signer-meta.ts
packages/signers/src/fee-payer-signer.ts

Now that the `feePayer` attribute is defined as `{ address: Address }` and that all `TransactionSigners` are compatible with that type, we can use the `feePayer` attribute of the transaction message directly to store fee payer signer.
This allows us to have a single point of failure for defining fee payers.
Address https://github.com/solana-labs/solana-web3.js/issues/2899.

Use `feePayer` attribute for `TransactionSigners`

---

.changeset/warm-lizards-report.md
packages/signers/src/__tests__/fee-payer-signer-test.ts
packages/signers/src/fee-payer-signer.ts

This PR changes the `setTransactionMessageFeePayerSigner` helper function such that, it will always override the fee payer even when the address of the existing `TransactionSigner` matches the one provided. This is because users may want to provide a different wallet from the same address.
Addresses https://github.com/solana-labs/solana-web3.js/issues/2897.

Override `feePayer` signer with matching address

---

.changeset/strange-oranges-hang.md
examples/deserialize-transaction/src/example.ts
packages/library/README.md
packages/library/src/__tests__/decompile-transaction-message-fetching-lookup-tables-test.ts
packages/library/src/decompile-transaction-message-fetching-lookup-tables.ts
packages/library/src/index.ts

This function had a confusing name, the new name better describes its functionality. It uses the passed in RPC to fetch lookup tables, and then passes them to `decompileTransactionMessage`.

Rename decodeTransactionMessage to decompileTransactionMessageFetchingLookupTables

---

packages/rpc-subscriptions/package.json
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-functional-test.ts
pnpm-lock.yaml

In rc2 there's a bug where `await rpcSubscriptions.anyNotifications().subscribe()` hangs. Unlike `rpc-api` [all tests in `rpc-subscriptions-api` are currently commented out.  ](https://github.com/solana-labs/solana-web3.js/blob/master/packages/rpc-subscriptions-api/src/__tests__/account-notifications-test.ts)
This PR adds a (currently failing) test to subscribe to notifications against the localhost test validator.
Notes:
- I've put this test in `rpc-subscriptions` rather than `rpc-subscriptions-api` because it relies on transport functions from `rpc-subscriptions`. If we wanted to build a full suite of `rpc-subscriptions-api` tests later then we should probably move these transport functions to a different package where they could be a dependency of `rpc-subscriptions-api`. We currently …

Add a failing test that verifies we can subscribe to an RPC subscription method

---

.changeset/funny-weeks-smash.md
packages/rpc-spec-types/src/__tests__/rpc-message-test.ts
packages/rpc-spec-types/src/rpc-message.ts
packages/rpc-spec-types/src/rpc-response.ts
packages/rpc-spec/src/__tests__/rpc-test.ts
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-functional-test.ts

- Still an autoincrementing integer, but sent to the server as a string
- This means the server will return it to us as a string, and we don't need to worry about number/bigint upcasting
- This fixes the bug in subscriptions, caused by upcasting the ID to a bigint

Use string for RPC message IDs

---

packages/errors/src/__tests__/instruction-error-test.ts
packages/errors/src/__tests__/json-rpc-error-test.ts
packages/errors/src/__tests__/transaction-error-test.ts

I've encountered a new issue with the latest RC when updating program clients.
Functions like `isProgramError` that check the custom error code for the program are no longer working because the relevant `SolanaError` context now contains `bigint` error codes or instruction indices instead of the `number` type defined in their context.
Unfortunately, we cannot rely on numeric keypaths for these errors because these only transform successful responses.
Since we already have error factories that, given some RPC error message returns a proper `SolanaError`, we can adjust the logic of these functions such that they return a consistent output no matter if they receive `bigint` or `number` codes or indices.
These methods are:
- `getSolanaErrorFromJsonRpcError`: The main RPC error entry point. …

Add failing tests for bigints in RPC errors

---

.changeset/silver-otters-doubt.md
packages/errors/src/__tests__/instruction-error-test.ts
packages/errors/src/__tests__/json-rpc-error-test.ts
packages/errors/src/__tests__/transaction-error-test.ts
packages/errors/src/instruction-error.ts
packages/errors/src/json-rpc-error.ts
packages/errors/src/transaction-error.ts
packages/rpc-transport-http/src/http-transport-for-solana-rpc.ts

This PR makes the failing tests introduced in the previous PR pass.
See https://github.com/solana-labs/solana-web3.js/pull/3518.

Accept bigints in RPC error factories

---

.changeset/hot-hotels-sort.md
packages/codecs-data-structures/src/index.ts

Add missing export for `*` from `literal-union.ts` to `@solana/codecs-data-structures`.

Add missing export for LiteralUnionCodec

---

.changeset/empty-wombats-guess.md
package.json
packages/addresses/package.json
packages/assertions/package.json
packages/codecs-core/package.json
packages/codecs-data-structures/package.json
packages/codecs-numbers/package.json
packages/codecs-strings/package.json
packages/compat/package.json
packages/errors/package.json
packages/keys/package.json
packages/options/package.json
packages/react/package.json
packages/signers/package.json
packages/subscribable/package.json
packages/sysvars/package.json
packages/transaction-confirmation/package.json
packages/webcrypto-ed25519-polyfill/package.json

- removes unnecesary + misleading `engine` field in all package manifests (this field should serve no purpose and differs from the actual `engines` field specified in all of these manifests)
- remove `engineStrict` field from root manifest (outdated + overwritten by `engine-strict = true` in .npmrc regardless)
- update root manifest `engines.node` to `>=20.18.0`

manifest fixes 

---

.changeset/silent-wolves-cry.md
packages/errors/src/context.ts
packages/rpc-transport-http/src/__tests__/http-transport-test.ts
packages/rpc-transport-http/src/http-transport.ts

Sometimes the response headers have useful information, like your rate limit status. Your program might like access to those headers to decide what to do next.
```ts
try {
const { value: latestBlockhash } = await rpc.getLatestBlockhash().send();
} catch (e) {
if (isSolanaError(e, SOLANA_ERROR__RPC__TRANSPORT_HTTP_ERROR)) {
if (e.context.code === 429 /* rate limit error */) {
const retryAfterHeaderValue = e.context.headers.get("Retry-After");
if (retryAfterHeaderValue != null) {
// ...
}
}
}
}
```
Fixes #3563.
```
cd packages/rpc-transport-http
```

Add `Response#headers` to errors thrown from the HTTP transport

---

.changeset/nervous-emus-move.md
packages/accounts/src/__tests__/decode-account-test.ts
packages/accounts/src/__tests__/fetch-account-test.ts
packages/accounts/src/__tests__/parse-account-test.ts
packages/accounts/src/account.ts
packages/accounts/src/parse-account.ts
packages/library/src/__tests__/decompile-transaction-message-fetching-lookup-tables-test.ts
packages/rpc-types/src/account-info.ts

This PR adds the missing `space` attribute to:
- The `AccountInfoBase` type from `@solana/rpc-types`.
- The `BaseAccount` type from `@solana/accounts`.
In terms of tests, I just needed to update some existing one that were using mock data but all the ones using a local validator (including `jsonParsed` fetches) are already asserting that we get a `space` attribute. We were just not capturing it in the types.
I believe this is a `patch` change because, even though this is _adding_ a type attribute, the data was already there so we are just _fixing_ our type representation to match the data correctly. Lmk if you agree with this as we're figuring out our stance of versioning/releasing.
---
Addresses #3569

Add missing space attribute to accounts

---

src/connection.ts

Tackles the issue (#3091) 
Done proper linting , built and complied properly , also tested to see if programId returns as expected ,
also added the screenshots
Please tell me if I am missing something and Thank you for being patient and helping me through this.

Added programId field in TokenBalance type

---

packages/rpc-api/src/__tests__/get-largest-accounts-test.ts

Updated test cases for getLargestAccounts with improved promises and stricter equality checks

test: update test cases for getLargestAccounts with improved promises and stricter equality checks

---

.changeset/spicy-parrots-raise.md
examples/deserialize-transaction/src/example.ts
packages/errors/src/context.ts
packages/instructions/package.json
packages/instructions/src/__typetests__/instruction-typetest.ts
packages/instructions/src/instruction.ts
packages/transaction-messages/src/compile/instructions.ts
packages/transaction-messages/src/durable-nonce.ts
pnpm-lock.yaml

This PR modifies the `data` field of `IInstruction` to use `ReadonlyUint8Array`. This means that you can create an `IInstruction` using bytes output from an encoder as input.

Change IInstruction to use ReadonlyUint8Array for data

---

.changeset/six-zoos-explode.md
packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-autopinger-test.ts
packages/rpc-subscriptions/src/rpc-subscriptions-autopinger.ts

In the isolated Content Scripts environment, `globalThis.window` is apparently not a thing. In this PR we eliminate that nesting and presume that the event target for listening to online/offline events is `globalThis` itself.
Tested that `globalThis.addEventListener('offline', () => {})` fires the callback in Brave when the network connection goes down. Presumed that the same is true for all other browsers.
Fixes #3652.

The online/offline checker now presumes that `globalThis` is the event target

---

packages/rpc-subscriptions-channel-websocket/package.json
packages/rpc-subscriptions-spec/package.json
packages/rpc-subscriptions/package.json
packages/rpc/package.json
packages/subscribable/package.json
packages/transaction-confirmation/package.json
pnpm-lock.yaml

These, after all, don't exist on npm.

Inlined dependencies must live in `devDependencies` so that they don't appear as dependencies in the published package

---

.mergify.yml

We haven't really made use of this community reviewers' group in a few years. The core team of maintainers pretty regularly goes through community contributions as part of their normal work.

Remove Mergify rule that adds community reviewers group to community PRs

---

README.md

Adding a basic fail-over example to abstract a list of RPC transport providers. It contains a delay in between fail-overs.

Add failover RPC transport example

---

eslint.config.mjs
examples/react-app/eslint.config.mjs
examples/react-app/src/components/Balance.tsx

This PR intends to fix a small part of issue #3465 
Specifically, it changes the rule @typescript-eslint/restrict-template-expressions, which is currently set to off, to error.

Enable rule @typescript-eslint/restrict-template-expressions and fix the only error

---

examples/deserialize-transaction/src/example.ts
packages/errors/src/message-formatter.ts
packages/rpc-transport-http/src/__tests__/http-transport-test.ts

While I was adding an extra eslint rule, I realized that there were a few extra linting errors from restrict-template-expressions rule. 
One of them I had to comment it because when it gets stringified, it leaks relevant information. Probably it should be sanitized first.

Enable eslint restrict-template-expressions plugin has a few extra linting errors

---

packages/transaction-messages/README.md

Add compressTransactionMessageUsingAddressLookupTables to transation-messages readme

---

src/connection.ts
test/connection.test.ts

With the upcoming upgrade from 1.18 to 2.0 on Solana mainnet-beta, deprecated RPC methods have been removed, therefore they will no longer be available through Web3.js client requests.
The [Agave 2.0 Migration Guide](https://github.com/anza-xyz/agave/wiki/Agave-v2.0-Transition-Guide) lists semi-equivalent RPC method counterparts for each of the removed methods.
Replace `getConfirmedBlock` with `getBlock`. This method was already requiring a confirmation level of `confirmed` or `finalized`, so the behavior should be unchanged.

feat: Agave v2 RPC: replace `getConfirmedBlock` with `getBlock`

---

src/connection.ts
test/connection.test.ts

With the upcoming upgrade from 1.18 to 2.0 on Solana mainnet-beta, deprecated RPC methods have been removed, therefore they will no longer be available through Web3.js client requests.
The [Agave 2.0 Migration Guide](https://github.com/anza-xyz/agave/wiki/Agave-v2.0-Transition-Guide) lists semi-equivalent RPC method counterparts for each of the removed methods.
Replace `getConfirmedTransaction` with `getTransaction`. This method was already requiring a confirmation level of `confirmed` or `finalized`, so the behavior should be unchanged.

feat: Agave v2 RPC: replace `getConfirmedTransaction` with `getTransaction`

---

src/connection.ts
test/connection.test.ts
test/mocks/rpc-http.ts

With the upcoming upgrade from 1.18 to 2.0 on Solana mainnet-beta, deprecated RPC methods have been removed, therefore they will no longer be available through Web3.js client requests.
The [Agave 2.0 Migration Guide](https://github.com/anza-xyz/agave/wiki/Agave-v2.0-Transition-Guide) lists semi-equivalent RPC method counterparts for each of the removed methods.
Replace `getRecentBlockhash` with `getLatestBlockhash`. This method still vends a blockhash, but the field `lamportsPerSignature` cannot be served, so accessing it throws an error. However, if apps use the deprecated `getRecentBlockhash` method and only access the `blockhash` field, they will not see an error, and the request is served by `getLatestBlockhash`.

feat: Agave v2 RPC: replace `getRecentBlockhash` with `getLatestBlockhash`
