- src/budget-program.js
- src/system-program.js
> Catch up to latest Transaction ABI changes

- src/budget-program.js
This was the only place that "S" was capitalized.
> Rename TimeStamp to Timestamp

- module.flow.js
- src/budget-program.js
- src/loader.js
- src/system-program.js
- src/token-program.js
- src/transaction.js
- test/native-loader.test.js
Part of https://github.com/solana-labs/solana/issues/1582
> feat: add room in the API for Transactions with multiple Instructions

- examples/bpf-c-noop/src/noop.c
Depends-on: https://github.com/solana-labs/solana/pull/1685
> fix: update bpf sdk header

- examples/budget-timestamp.js
- examples/budget-two-approvers.js
- module.flow.js
- src/bpf-loader.js
- src/connection.js
- src/loader.js
- src/native-loader.js
- src/token-program.js
- src/transaction.js
- src/util/send-and-confirm-transaction.js
- test/bpf-loader.test.js
- test/connection.test.js
- test/native-loader.test.js
Fixes #https://github.com/solana-labs/solana/issues/1823
> fix: support multiple Transaction signatures

- bin/localnet.sh
- examples/bpf-c-noop/src/noop.c
Also `fix: surface system_program info logs by default`
> fix: adapt to SolKeyedAccount name change

- css/theme.css
custom css theme implemented for web3 js doc to support common style among all Solana docs
> custom css theme

- css/theme.css
css fix to render code style properly
> minor css fix

- css/theme.css
found another issue with code style. you can see it here (black colored code):
https://solana-labs.github.io/solana-web3.js/
> code highlight style change

- module.flow.js
- src/connection.js
- test/connection.test.js
cc: https://github.com/solana-labs/solana/pull/2807
> fix: getConfirmationTime() was removed upstream

- module.flow.js
- src/budget-program.js
- src/connection.js
- src/loader.js
- src/system-program.js
- src/timing.js
- src/token-program.js
- src/transaction.js
- test/bpf-loader.test.js
- test/connection.test.js
- test/token-program.test.js
Catch-up to https://github.com/solana-labs/solana/pull/3282
> fix: rename userdata to data

- module.flow.js
- package-lock.json
- src/connection.js
- src/util/send-and-confirm-raw-transaction.js
- src/util/send-and-confirm-transaction.js
- test/connection.test.js
- test/native-loader.test.js
- test/transaction.test.js
cc: https://github.com/solana-labs/solana/pull/3940
> feat: add getSlotLeader()/getClusterNodes()

- src/bpf-loader.js
- src/budget-program.js
- src/native-loader.js
- src/token-program.js
https://github.com/solana-labs/solana/pull/4001
> fix: adapt to program id changes

- src/connection.js
- test/mockrpc/get-recent-blockhash.js
Depends-on: https://github.com/solana-labs/solana/pull/4222
> fix: adapt to GetRecentBlockhash RPC API signature change

- examples/bpf-rust-noop/Cargo.toml
- src/connection.js
Depends-on: https://github.com/solana-labs/solana/pull/4778
> fix: add {min,max}LamportsPerSignature fields

- .eslintignore
- .travis.yml
- commitlint.config.js
- package-lock.json
- package.json
> Add commitlint

- module.flow.js
- src/connection.js
- test/mockrpc/get-recent-blockhash.js
cc: https://github.com/solana-labs/solana/pull/4818
> fix: add burnPercent field to FeeCalculator

- src/connection.js
cc: https://github.com/solana-labs/solana/pull/4918
> doc: commission is now a u8

- module.flow.js
- src/validator-info.js
- test/validator-info.test.js
Follows https://github.com/solana-labs/solana/pull/5165
Tag: @jstarry , this will conflict with https://github.com/solana-labs/blockexplorer/pull/199
> fix: Update keybaseId to keybaseUsername

- module.flow.js
- package-lock.json
- src/connection.js
- test/connection.test.js
Required by https://github.com/solana-labs/solana/pull/5543
> fix: Update from getEpochVoteAccounts to getVoteAccounts rpc

- module.flow.js
- src/connection.js
- test/connection.test.js
Depends on https://github.com/solana-labs/solana/pull/6337
> fix: update node exit rpc to match solana changes

- module.flow.js
- src/connection.js
- test/connection.test.js
PROBLEM:
* we'd like to access the get_epoch_schedule rpc 🕐 
SOLUTION:
* implement the JS rpc 🕐
> feat: get_epoch_schedule rpc

- src/connection.js
Airdrop's tx may take a bit to clear even if balance reports the correct account balance, wait a bit.
> fix: wait for airdrop

- examples/budget-timestamp.js
- examples/budget-two-approvers.js
- src/loader.js
- src/system-program.js
Fixes: #551 
Summary of changes:
* Modify CreateAccount to make `to` signable
* Modify `sendAndConfirmTransaction` calls to add second account for signing.
> make to account key as signer

- module.flow.js
- src/connection.js
- test/connection.test.js
Useful for determining if the connected testnet supports certain RPC apis
> feat: add getVersion method

- flow-typed/superstruct.js
- src/connection.js
- test/connection.test.js
Will add issue to update getBlock test on upstream updates
> fix: add getBlock Connection method

- module.flow.js
- src/connection.js
Problem:
* need to update API for new RPC response format 🔧 
Solution:
* update the API 🌈 
Fixes: #556
> feat: implement new response format for __WithCommitment() methods

- module.flow.js
- src/connection.js
- test/connection.test.js
I don't know why this passed CI before :(
> fix: getConfirmedBlock result pattern fixup

- test/bpf-loader.test.js
- test/connection.test.js
> fix: fix rent in various tests

- module.flow.js
- src/index.js
- test/connection.test.js
- test/transaction-payer.test.js
Rename mirrors https://github.com/solana-labs/solana/pull/7641
> Fix sol-to-lamport ratio and const name

- module.flow.js
- package-lock.json
module.flow.rs was missing:
`getMinimumBalanceForRentException`
`getBlock`
> fix: add getMinimumBalanceForRentExemption and getBlock to flow

- module.flow.js
> fix: Remove GetBlock from module flow

- src/connection.js
- src/index.js
- src/nonce-account.js
- src/system-program.js
- src/sysvar.js
- src/transaction.js
- test/nonce.test.js
- test/system-program.test.js
- test/transaction.test.js
Depends on https://github.com/solana-labs/solana/pull/7645 
Closes https://github.com/solana-labs/solana/issues/7583
and addresses web3 concern of https://github.com/solana-labs/solana/issues/7700
> Add Nonce functionality to solana-web3

- src/connection.js
- src/transaction.js
- test/transaction.test.js
> fix: update getConfirmedBlock json-rpc formatting

- examples/bpf-c-noop/src/noop/noop.c
- examples/bpf-rust-noop/src/lib.rs
- module.flow.js
- src/connection.js
- src/stake-program.js
- test/connection.test.js
- test/stake-program.test.js
* redeemVoteCredits no longer exists
* delegateStake needs stake history
> fix: update stake program api

- src/connection.js
It's possible to send duplicate subscription messages due to a race condition in the subscription code. While `await`ing a subscription, if `updateSubscriptions` is called, the `subscriptionId` will still be `null`.
* Temporarily set `subscriptionId` to a special value as a lock
* Consolidate subscription methods using type generics
> fix: race condition in rpc websocket subscriptions

- module.d.ts
- module.flow.js
* Add `SystemInstruction`
* Add `Transaction.from`
> fix: add missing apis to flow and ts definitions

- test/connection.test.js
- test/url.js
Adjust test to account for disabled epoch warmups
> fix: epochSchedule test and lint

- examples/bpf-rust-noop/Cargo.toml
- examples/bpf-rust-noop/src/lib.rs
- package.json
> fix: update rust example to latest solana sdk

- module.d.ts
- module.flow.js
- package.json
- src/connection.js
- src/fee-calculator.js
- test/mockrpc/get-recent-blockhash.js
> fix: update feeCalculator layout 

- .flowconfig
- .travis.yml
- module.d.ts
- module.flow.js
- package-lock.json
- package.json
* TypeScript definition file shipped with type errors
* Add CI check for TypeScript def file and Flow def file
* Fix TypeScript definition file
> fix: add def checks and fix typescript def

- module.d.ts
- module.flow.js
- src/fee-calculator.js
- src/nonce-account.js
- src/system-program.js
- test/nonce.test.js
- test/system-program.test.js
A new structure for Nonce accounts just landed on Solana master and v1.0
Fix js apis to accommodate new format. Also, make nonceSpace definition less magical.
> fix: update NonceAccount to upstream changes

- module.d.ts
- module.flow.js
- TypeScript definition was not updated for already released SystemInstruction API changes
- Flow definition was missing a SystemProgram method for decoding instruction type
- Fix type definitions
- Reorganize type definitions to make diffing the two (TS/Flow) easier
> fix: update TS SystemInstruction API and add missing flow method

- module.d.ts
- module.flow.js
- src/connection.js
- src/transaction.js
- src/util/send-and-confirm-raw-transaction.js
- src/util/send-and-confirm-transaction.js
- test/connection.test.js
- test/transaction-payer.test.js
Changes:
* Added context to pubsub notification callbacks
* Updated `getSignatureStatus` return type to include slot
* Added `getSignatureStatusBatch` method
> Address latest RPC API breaking changes

- module.d.ts
- module.flow.js
- src/connection.js
- src/util/send-and-confirm-raw-transaction.js
- src/util/send-and-confirm-transaction.js
- test/connection.test.js
- test/transaction-payer.test.js
Depends on https://github.com/solana-labs/solana/pull/9069
> feat: update getSignatureStatus api

- module.d.ts
- module.flow.js
- src/connection.js
- test/connection.test.js
Adds support for the new root subscription RPC API
> feat: add root subscription api

- module.d.ts
- module.flow.js
- test/connection.test.js
Fixes: https://github.com/solana-labs/solana-web3.js/issues/794
> fix: add getNonce method to defs

- src/connection.js
Give a more descriptive error when a connection operation fails.
fixes: #809
> fix: improve error messaging

- src/util/send-and-confirm-transaction.js
- Attempt to wait for at least one confirmation
- Bail the resend loop immediately on error
- If some status is received rest the status counter to wait for confirmations
fixes: https://github.com/solana-labs/example-helloworld/issues/9
> fix: adjust status retry algorithm

- module.d.ts
- module.flow.js
- src/connection.js
- test/connection.test.js
* Add support and tests for `getConfirmedTransaction` and `getConfirmedSignaturesForAddress`
> feat: add getConfirmedTransaction and getConfirmedSignaturesForAddress

- test/connection.test.js
Error type for malformed signatures changed upstream. Update tests to match.
> fix: update expected signature-status error

- module.d.ts
- module.flow.js
- src/connection.js
- test/connection.test.js
Fixes #921 
RPC has new commitment level; enable it for JS use.
> feat: add singleGossip commitment level

- src/publickey.js
- test/publickey.test.js
Add function to derive Program Addresses
fixes: #909
> feat: add createProgramAddress

- src/connection.js
- test/connection.test.js
The internal blockhash cache inside `Connection` was using the `Date.getSeconds()` API to determine if 30s had passed since the last blockhash fetch. That API doesn't return the number of seconds from epoch as was probably expected, instead it returns seconds % 60. This means that the connection could erroneously believe it's cache was still fresh long after it had expired.
- Use epoch timestamp to determine cache expiration
- Add tests
> fix: fix blockhash cache reuse

- src/connection.js
well, it took a while to reason this odd port handling.
to unblock: https://github.com/solana-labs/solana/pull/12245
> Add some comment to clarify 5b4aa213

- .mergify.yml
Copying over useful rules from the monorepo.
> Update Mergify configuration

- .mergify.yml
`commit-lint` was renamed to `Validate commit message`
> Fix automerge

- packages/test-config/jest-dev.config.ts
- packages/test-config/package.json
- pnpm-lock.yaml
> test: add branch, project, and typeahead plugins to Jest for a better `pnpm dev` experience

- packages/test-config/jest-lint.config.ts
- packages/test-config/jest-prettier.config.ts
- packages/test-config/jest-unit.config.browser.ts
- packages/test-config/jest-unit.config.common.ts
- packages/test-config/jest-unit.config.node.ts
https://github.com/facebook/jest/issues/13913 👀
> test: actually actually fix the types of the Jest project configs

- .gitignore
- README.md
- package.json
- packages/library-legacy/.eslintignore
- packages/library-legacy/.gitignore
- packages/library-legacy/.prettierignore
- packages/library-legacy/README.md
- packages/library-legacy/package.json
- pnpm-lock.yaml
- turbo.json
chore: remove codecov
Summary: Never once have a made use of the information coming out of this thing. Despite that, it adds complexity and slows down the build.
> chore: remove codecov

- packages/library-legacy/src/connection.ts
- packages/library-legacy/test/connection.test.ts
There is no sense having more than one of these calls in flight at any one time; once there's a single call in flight, all callers should share the result.
For much more on why this is necessary, see #1182.
Fixes #1182.
```shell
```
> feat: coalesce calls to `getBlockHeight`

- .github/ISSUE_TEMPLATE/0_bug.md
- .github/ISSUE_TEMPLATE/config.yml
Add template for reporting bugs
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1217).
* __->__ #1217
* #1216
> Add template for reporting bugs

- packages/library-legacy/test/program-tests/compute-budget.test.ts
test: repair compute budget test by adding at least one instruction before `requestHeapFrame`
I believe that what's going on here is that you can no longer `requestHeapFrame` if the transaction consumes no compute units.
```
pnpm test:live-with-test-validator
```
> test: repair compute budget test by adding at least one instruction before `requestHeapFrame`

- packages/library-legacy/test/program-tests/compute-budget.test.ts
> test: re-enable compute budget test

- package.json
chore: update required pnpm version to 8.5.1
Fixes #1295.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1310).
* #1311
* __->__ #1310
> chore: update required pnpm version to 8.5.1

- packages/instructions/README.md
refactor(experimental): update the README for `@solana/instructions`
Adding in all the work about roles and the changes to `IInstruction`
> refactor(experimental): update the README for `@solana/instructions`

- .github/workflows/cicd.yml
- .github/workflows/pull-requests.yml
This seems to resolve flakiness in CI
> ci: add concurrency limit to turbo in CI (default was 10)

- packages/transactions/src/__tests__/blockhash-test.ts
test: move blockhash tests into package where they belong
> test: move blockhash tests into package where they belong

- packages/transactions/src/__tests__/durable-nonce-test.ts
- packages/transactions/src/durable-nonce.ts
refactor(experimental): a function to turn a transaction into a durable nonce transaction
A durable nonce transaction is one whose:
1. Lifetime constraint is that of a durable nonce
2. First instruction is an `AdvanceNonceAccount` instruction against the system program
Use this function to turn a transaction into a durable nonce transaction by adding those two things.
```
```
> refactor(experimental): a function to turn a transaction into a durable nonce transaction

- packages/library-legacy/src/connection.ts
> fix: getRecentPrioritizationFees works with commitment specified

- packages/rpc-core/src/rpc-methods/__tests__/get-minimum-balance-for-rent-exemption-test.ts
- packages/rpc-core/src/rpc-methods/getMinimumBalanceForRentExemption.ts
- packages/rpc-core/src/rpc-methods/index.ts
the test is kind of perfunctory im not sure what else wed want to look at tho
> refactor(experimental): add getMinimumBalanceForRentExemption

- packages/rpc-core/src/rpc-methods/__tests__/get-fee-for-message-test.ts
- packages/rpc-core/src/rpc-methods/__tests__/get-signature-statuses-test.ts
Cleans up a [missed log message](https://github.com/solana-labs/solana-web3.js/pull/1504#discussion_r1300693445) and [improper return value of undefined signature](https://github.com/solana-labs/solana-web3.js/pull/1498#discussion_r1300685360)
> test: cleanup

- packages/rpc-core/src/rpc-methods/__tests__/get-version-test.ts
test: get genesis hash from logfile with `readLines` API
> test: get version info from logfile with `readLines` API

- packages/rpc-core/src/rpc-methods/__tests__/get-cluster-nodes-test.ts
test: get node info from logfile with `readLines` API
> test: get node info from logfile with `readLines` API

- packages/rpc-core/src/rpc-methods/common.ts
- packages/rpc-core/src/rpc-methods/getInflationGovernor.ts
- packages/rpc-core/src/rpc-methods/getInflationRate.ts
refactor(experimental): added unsafe f64 type
> refactor(experimental): added unsafe f64 type

- packages/rpc-core/src/rpc-methods/getGenesisHash.ts
refactor(experimental): change genesis hash type to blockhash
> refactor(experimental): change genesis hash type to blockhash

- packages/rpc-core/src/rpc-methods/__tests__/get-identity-test.ts
- packages/rpc-core/src/rpc-methods/__tests__/get-leader-schedule-test.ts
This should solve some typecheck issues with tests reading the local validator's keypair file
> test: use `readLines` for keypair reads

- packages/addresses/src/base58.ts
- packages/keys/src/signatures.ts
- packages/rpc-core/src/response-patcher-types.ts
- packages/rpc-core/src/rpc-methods/common.ts
- packages/rpc-core/src/stringified-bigint.ts
- packages/rpc-core/src/stringified-number.ts
- packages/rpc-core/src/transaction-signature.ts
- packages/rpc-core/src/unix-timestamp.ts
- packages/transactions/src/accounts.ts
- packages/transactions/src/blockhash.ts
- packages/transactions/src/durable-nonce.ts
- packages/transactions/src/signatures.ts
- packages/transactions/src/wire-transaction.ts
refactor(experimental): rename all unique symbols to __brand
> refactor(experimental): rename all unique symbols to __brand

- packages/library/src/__tests__/rpc-websocket-autopinger-test.ts
- packages/library/src/rpc-websocket-autopinger.ts
refactor(experimental): teach the auto-pinger *not* to ping the connection when you're offline
There is zero point to slamming ping messages down a socket if the server can't hear them. At most we should send a ping the moment we come back online, then resume as normal.
```
```
1. Paste [this](https://gist.github.com/steveluscher/4254aba293222daded59bdceafbdaa4c) code into a Chrome console.
2. Toggle the network between ‘no throttling’ and ‘offline’
3. Observe the ping behavior, as described in the unit tests
> refactor(experimental): teach the auto-pinger *not* to ping the connection when you're offline

- packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
- packages/rpc-transport/src/json-rpc-subscription.ts
refactor(experimental): make sure that subscriptions clean themselves up no matter how the connection closes
The bug here was that, if the connection closes for a non-fatal reason (eg. it was explicitly aborted) we want to unhook the subscription abort signal unconditionally. This prevents a situation where aborting a subscription after the connection has dropped runs the unsubscribe logic.
```
cd packages/rpc-transport
```
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1611).
* #1613
* #1612
* __->__ #1611
> refactor(experimental): make sure that subscriptions clean themselves up no matter how the connection closes

- packages/addresses/package.json
- packages/addresses/tsconfig.json
- packages/assertions/package.json
- packages/fetch-impl/tsconfig.json
- packages/functional/package.json
- packages/functional/tsconfig.json
- packages/instructions/package.json
- packages/keys/package.json
- packages/library/package.json
- packages/rpc-core/package.json
- packages/rpc-core/tsconfig.json
- packages/rpc-transport/package.json
- packages/transactions/package.json
- packages/transactions/tsconfig.json
- packages/webcrypto-ed25519-polyfill/package.json
- packages/webcrypto-ed25519-polyfill/src/__tests__/index-test.ts
- packages/webcrypto-ed25519-polyfill/tsconfig.json
- packages/ws-impl/tsconfig.json
- pnpm-lock.yaml
refactor(experimental): TypeScript 5.2.x
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1616).
* #1591
* __->__ #1616
> refactor(experimental): TypeScript 5.2.x

- packages/transactions/src/__tests__/signatures-test.ts
- packages/transactions/src/signatures.ts
Modifies the `signTransaction` function to take multiple signers instead of one.
Closes #1615
> refactor(experimental): make signTransaction take multiple keypairs

- packages/transactions/src/__tests__/signatures-test.ts
- packages/transactions/src/signatures.ts
The signature of the fee payer is by definition the signature of the transaction. This is a helper that makes you not have to think about that fact.
```
```
> refactor(experimental): a function you can use to get a transaction's signature

- packages/library/src/transaction-confirmation.ts
This PR installs the conventional web3.js transaction confirmation strategy implementations. People who don't wish to customize them can create a confirmer according to the defaults, and can use it to confirm transactions.
```
```
Also, this integration test! ([link](https://gist.github.com/steveluscher/9244301b2f7fa3a1bd04308bfb0f0855))
```js
const {
createSolanaRpc,
createSolanaRpcSubscriptions,
createDefaultRpcTransport,
createDefaultRpcSubscriptionsTransport,
createDefaultTransactionConfirmer,
generateKeyPair,
getAddressFromPublicKey,
} = require('@solana/web3.js');
const { lamports } = require('@solana/rpc-core');
function synthesizeTransactionFromAirdrop(publicKey, signature) {
return {
feePayer: publicKey, …
```
> refactor(experimental): the default transaction confirmation strategy

- packages/rpc-graphql/src/__tests__/block-tests.ts
- packages/rpc-graphql/src/rpc.ts
- packages/rpc-graphql/src/schema/block/index.ts
- packages/rpc-graphql/src/schema/block/query.ts
- packages/rpc-graphql/src/schema/block/types.ts
- packages/rpc-graphql/src/schema/inputs.ts
- packages/rpc-graphql/src/schema/transaction/types.ts
A block query/schema for fetching blocks from RPC using GraphQL.
> refactor(experimental): a block GraphQL query

- LICENSE
- packages/addresses/LICENSE
- packages/assertions/LICENSE
- packages/codecs-core/LICENSE
- packages/codecs-data-structures/LICENSE
- packages/codecs-numbers/LICENSE
- packages/codecs-strings/LICENSE
- packages/compat/LICENSE
- packages/fetch-impl/LICENSE
- packages/functional/LICENSE
- packages/instructions/LICENSE
- packages/keys/LICENSE
- packages/library-legacy/LICENSE
- packages/library/LICENSE
- packages/options/LICENSE
- packages/rpc-core/LICENSE
- packages/rpc-graphql/LICENSE
- packages/rpc-transport/LICENSE
- packages/text-encoding-impl/LICENSE
- packages/transactions/LICENSE
- packages/webcrypto-ed25519-polyfill/LICENSE
- packages/ws-impl/LICENSE
> updated licenses to 2023 #1602

- packages/transactions/package.json
- packages/transactions/src/serializers/__tests__/header-test.ts
- packages/transactions/src/serializers/header.ts
- packages/transactions/src/serializers/message.ts
- pnpm-lock.yaml
- Refactor to use a memoized u8 encoder/decoder/codec
> refactor(experimental): use codecs packages for message header codec

- packages/webcrypto-ed25519-polyfill/src/__tests__/secrets-test.ts
> refactor(experimental): fix test description for extractability test of `generateKey`

- packages/transactions/src/__tests__/signatures-test.ts
- packages/transactions/src/serializers/__tests__/address-table-lookup-test.ts
- packages/transactions/src/serializers/address-table-lookup.ts
- packages/transactions/src/serializers/message.ts
> refactor(experimental): use codecs package for address table lookup

- packages/library/src/__tests__/airdrop-test.ts
- packages/library/src/airdrop.ts
I regret not applying the factory pattern for the airdrop helper as well. This new design will allow other devs to create their _own_ airdrop helpers with custom RPC and transaction confirimation strategies, should they wish to. Everyone else can use the default RPCs and create a default airdrop helper.
```
```
Related to #1579.
> refactor(experimental): follow creator pattern for airdrop helper

- packages/transactions/package.json
- packages/transactions/src/serializers/__tests__/message-test.ts
- packages/transactions/src/serializers/__tests__/transaction-test.ts
- packages/transactions/src/serializers/message.ts
- packages/transactions/src/serializers/transaction.ts
- packages/transactions/src/signatures.ts
- pnpm-lock.yaml
- Refactor to use encoders/decoders throughout
> refactor(experimental): use codecs for message de/serialization

- packages/library/src/send-transaction.ts
It's conceivable that, despite the fact that the send-and-confirm helpers use subscriptions internally, you might want to be lazy and not manage cancellation. This is so because transaction confirmation is short-lived-ish.
To save you a few keystrokes, and at your own peril, we make `abortSignal` optional in the method signature of `sendAndConfirmTransaction` and `sendAndConfirmDurableNonceTransaction`.
```
cd packages/library/
```
> refactor(experimental): make `abortSignal` optional on send-and-confirm-transaction helpers

- packages/test-config/jest-lint.config.ts
- packages/test-config/jest-prettier.config.ts
This is causing some CI annoyance.
> refactor(experimental): remove README from lint and prettier

- packages/library/README.md
Example shows a simple retrying transport that will retry up to `MAX_ATTEMPTS`. Would appreciate any feedback regarding implementation, as I wasn't too sure how much error handling would be best to show, for example.
Thanks! Super excited to start using this!
> docs(experimental): add custom retry logic example

- packages/rpc-graphql/src/loaders/account.ts
- packages/rpc-graphql/src/loaders/block.ts
- packages/rpc-graphql/src/loaders/program-accounts.ts
- packages/rpc-graphql/src/loaders/transaction.ts
This PR adds "normalizing" of RPC configs in order to set defaults and ensure
proper overlap of cache keys.
Note: I've elected to default to "confirmed" rather than "finalized" for
`commitment`. Although this diverges from the Solana JSON RPC API, there are
several other areas that this GraphQL library specifically makes opinionated
decisions, such as object structure and omitted RPC request configs.
This election will require less specifying of `encoding` at the query level and
should make most queries less verbose.
> refactor(experimental): normalize GraphQL loader args and cache keys

- packages/rpc-graphql/src/__tests__/account-test.ts
- packages/rpc-graphql/src/__tests__/block-tests.ts
- packages/rpc-graphql/src/__tests__/program-accounts-test.ts
- packages/rpc-graphql/src/__tests__/transaction-tests.ts
- packages/rpc-graphql/src/schema/account.ts
- packages/rpc-graphql/src/schema/block.ts
- packages/rpc-graphql/src/schema/common/inputs.ts
- packages/rpc-graphql/src/schema/common/scalars.ts
- packages/rpc-graphql/src/schema/common/types.ts
- packages/rpc-graphql/src/schema/instruction.ts
- packages/rpc-graphql/src/schema/transaction.ts
This PR adds some type aliases and other niceties to the GraphQL type spec!
> refactor(experimental-graphql): roll some new type aliases

- packages/codecs-numbers/tsconfig.json
- packages/crypto-impl/package.json
- packages/library/src/rpc-websocket-autopinger.ts
- packages/library/tsconfig.json
- packages/options/tsconfig.json
- packages/rpc-types/tsconfig.json
- packages/signers/tsconfig.json
- pnpm-lock.yaml
```
git clean -dfx .
pnpm i
pnpm turbo test:typecheck --force
```
> refactor(experimental): fix type errors everywhere

- packages/rpc-graphql/src/__tests__/transaction-tests.ts
- packages/rpc-graphql/src/loaders/block.ts
- packages/rpc-graphql/src/loaders/transaction.ts
- packages/rpc-graphql/src/loaders/transformers/block.ts
- packages/rpc-graphql/src/loaders/transformers/transaction.ts
- packages/rpc-graphql/src/schema/instruction.ts
- packages/rpc-graphql/src/schema/transaction.ts
This PR introduces similar changes to its parent commit, this time to
transaction instructions.
It also serves as a space to discuss a proper revision to the transaction
instruction schema.
> refactor(experimental-graphql): revise transaction instructions schema (again)

- packages/compat/README.md
- packages/library-legacy/README.md
- packages/library/README.md
I've made a few updates to our documentation and code examples that I'd like to share. These are small but important corrections aimed at improving clarity and accuracy.
1. **Spelling and Syntax Fixes in Library README:** Updated the spelling of 'applications' and removed extra parentheses in the transport URLs in the `library` README. These changes should enhance readability and correctness. (Commit: 08838cf5a6571e86678118dd2d4da93a5cb5c25c)
2. **Typo Correction in Development Environment Setup:** In the `library-legacy` README, I've corrected a typo from "excute" to "execute" in the unit tests section. (Commit: b547cc1f20b8708d234878fc3f52c81618da5404)
3. **Correction in Import Statement for `compat` Package:** Fixed an incorrect function name in the import statement, changing …
> Minor Corrections and Improvements to Code Examples and Documentation

- README.md
- packages/addresses/README.md
- packages/library/README.md
- packages/rpc-types/README.md
> chore: fix typos

- packages/rpc-graphql/src/schema/account.ts
- packages/rpc-graphql/src/schema/block.ts
- packages/rpc-graphql/src/schema/instruction.ts
- packages/rpc-graphql/src/schema/transaction.ts
Refactors the GraphQL doc comments so they show up on the playground!
> refactor(experimental): refactor GraphQL doc comments

- packages/library/src/__tests__/rpc-request-coalescer-test.ts
- packages/library/src/rpc-request-coalescer.ts
The coalescing transport uses _one_ underlying transport to serve one or more subscribers. When the last subscriber aborts, the underlying transport is aborted.
The problem is that the `AbortError` that results when the underlying transport is aborted was bubbling up through people's programs, uncaught. In this PR, we catch and ignore it, since aborting the underlying transport is a mere implementation detail of how the coalescing transport works.
The test plan is ‘upon making that test synchronous, the test no longer blows up.’ Without the change in behaviour, the Jest test would not even finish.
The edge case in transaction confirmation was confirmed using this:
```diff
diff --git a/packages/library/src/transaction-confirmation-strategy-recent-signature.ts …
```
> The coalescing transport no longer double-throws `AbortError` when the last subscriber aborts

- packages/codecs-core/README.md
- packages/codecs-data-structures/README.md
- packages/codecs-numbers/README.md
- packages/codecs-strings/README.md
- packages/codecs/README.md
- packages/options/README.md
This PR documents the `options` package and all `codecs-*` packages.
> refactor(experimental): Document codec packages

- packages/rpc-graphql/src/loaders/transaction.ts
This code makes a backup fetch for `jsonParsed` every time you fetch a transaction. Previous to this PR those fetches were done in serial with any existing `base58`/`base64`/`json` fetches.
> Parallelize `loadTransaction` in the GraphQL resolver

- packages/rpc-core/src/rpc-methods/index.ts
Continuing the work from the cluster-level transports. Here I'm establishing the different cluster-specific
Solana APIs (no airdrop on mainnet, that's it). This sets up `createSolanaRpcApi()` to return pass-through
API type definitions, like `createJsonRpcApi()`.
> refactor(experimental): add cluster level API for rpc-core

- README.md
- packages/library-legacy/README.md
Someone's gotta do the hard stuff 😄
> Update Readme broken link to rpc docs

- packages/rpc-graphql/src/loaders/block.ts
- packages/rpc-graphql/src/loaders/loader.ts
- packages/rpc-graphql/src/loaders/program-accounts.ts
- packages/rpc-graphql/src/loaders/transaction.ts
Updates the `FIXME` comments to point to the relevant TypeScript issue.
> refactor(experimental): graphql: update fix-me comments

- packages/library-legacy/package.json
- pnpm-lock.yaml
Closes https://github.com/solana-labs/solana-web3.js/security/dependabot/76
> chore: update `start-server-and-test`

- packages/rpc-transport-http/README.md
created an example for the failover transport 👍
> add failover transport example

- packages/errors/src/context.ts
> refactor(experimental): errors: context: sort keys

- packages/errors/src/codes.ts
Creates an RPC error group with its own code range.
> refactor(experimental): group RPC errors

- .github/workflows/actions/install-dependencies/action.yml
- .github/workflows/actions/setup-validator/action.yml
- .github/workflows/bundlesize.yml
- .github/workflows/cicd.yml
- .github/workflows/commit-lint.yml
- .github/workflows/pull-requests.yml
TIL about composite actions, inputs, and outputs.
> chore: divide workflows into reusable pieces

- packages/sysvars/src/__tests__/epoch-rewards-test.ts
- packages/sysvars/src/__tests__/sysvar-test.ts
- packages/sysvars/src/__typetests__/sysvar-typetest.ts
- packages/sysvars/src/epoch-rewards.ts
- packages/sysvars/src/index.ts
- packages/sysvars/src/sysvar.ts
This commit introduces the `EpochRewards` sysvar to the `@solana/sysvars` package.
> refactor(experimental): sysvars package: epoch rewards

- packages/library/README.md
- packages/rpc-graphql/README.md
Since @steveluscher has been laying down the start of our TypeDoc and Docusaurus
support, I remembered the documentation for `@solana/rpc-graphql` was outdated
since the last major update to the library.
Here's the revised documentation.
> refactor(experimental): graphql: update documentation

- packages/codecs-data-structures/src/__tests__/array-test.ts
This PR adds a couple of tests for offsetted arrays as [suggested here](https://github.com/solana-labs/solana-web3.js/pull/2294#pullrequestreview-1935521514).
> refactor(experimental): add tests for offsetted array codecs

- README.md
> add installing node modules section in README.md

- packages/transaction-messages/package.json
- packages/transaction-messages/src/__tests__/durable-nonce-test.ts
- packages/transaction-messages/src/__typetests__/transaction-message-typetests.ts
- packages/transaction-messages/src/durable-nonce.ts
- pnpm-lock.yaml
Implementation + tests from @solana/transactions
> add setTransactionMessageLifetimeUsingDurableNonce

- packages/transaction-messages/src/__tests__/fee-payer-test.ts
- packages/transaction-messages/src/__typetests__/transaction-message-typetests.ts
- packages/transaction-messages/src/fee-payer.ts
- packages/transaction-messages/src/index.ts
Implementation + tests copied from @solana/transactions
> add setTransactionMessageFeePayer

- packages/transaction-messages/src/__tests__/instructions-test.ts
- packages/transaction-messages/src/__typetests__/transaction-message-typetests.ts
- packages/transaction-messages/src/index.ts
- packages/transaction-messages/src/instructions.ts
Implementation + tests copied from @solana/transactions
> add append/prepend tx message instruction

- packages/signers/src/__tests__/add-signers-test.ts
- packages/signers/src/account-signer-meta.ts
- packages/signers/src/add-signers.ts
Very occasionally, things are actually straightforward.
> Refactor add-signers to use TransactionMessage

- packages/signers/README.md
- update names of functions where I've renamed them
- identify where we refer to transaction messages vs transactions
> Update signers README after refactoring

- packages/signers/src/__tests__/keypair-signer-test.ts
- packages/signers/src/keypair-signer.ts
- packages/signers/src/sign-transaction.ts
- packages/transaction-confirmation/src/waiters.ts
- packages/transactions/src/__tests__/signatures-test.ts
- packages/transactions/src/__typetests__/signatures-typetests.ts
- packages/transactions/src/index.ts
- packages/transactions/src/signatures.ts
Remove the `new` prefix from the functions
> Rename the file from new-signatures Remove the `new` prefix from the functions

- .changeset/purple-forks-rest.md
- packages/options/src/index.ts
> refactor(experimental): fix missing export of Zeroable Option codecs

- .github/workflows/bundlesize.yml
- packages/codecs-strings/src/__benchmarks__/run.ts
- packages/fetch-impl/src/__benchmarks__/run.ts
- packages/keys/src/__benchmarks__/run.ts
- packages/rpc-transport-http/src/__benchmarks__/run.ts
I heard this is [deprecated](https://github.com/orgs/pnpm/discussions/5590).
> [refactor] [experimental] Use optimised base16 encode strategy (#2552)

- packages/library/package.json
- pnpm-lock.yaml
This PR exports the `@solana/sysvars` package from the main Web3.js 2.0 library.
> refactor(experimental): export sysvars from main library

- packages/functional/README.md
- packages/library/README.md
- packages/transaction-messages/README.md
I did not test these code snippets at all; I just eyeballed them.
> Update web3.js README for new TransactionMessage API

- .github/workflows/actions/setup-validator/action.yml
- .gitignore
- scripts/get-latest-validator-release-version.sh
- scripts/setup-test-validator.sh
- scripts/start-shared-test-validator.sh
See https://github.com/anza-xyz/agave/wiki/Agave-Transition
Closes #2716.
> Migrate to Agave test validator

- .changeset/stupid-trees-exist.md
- packages/library-legacy/src/connection.ts
- packages/library-legacy/src/errors.ts
- packages/library-legacy/src/utils/send-and-confirm-raw-transaction.ts
- packages/library-legacy/src/utils/send-and-confirm-transaction.ts
- packages/library-legacy/test/connection.test.ts
- Added transaction logs to error case in sendAndConfirmRawTransaction
- Added transaction logs to error case in sendAndConfirmTransaction
- Added for skipPreflight and dont skipPreflight simulation log cases
> Added transaction logs to send transaction functions

- packages/library-legacy/src/connection.ts
- packages/library-legacy/src/errors.ts
- packages/library-legacy/src/utils/send-and-confirm-raw-transaction.ts
- packages/library-legacy/src/utils/send-and-confirm-transaction.ts
Reverted TransactionError types and added transactionMessage and logs directly into the SendTransactionError
> chore: Fixed sendTransactionError types

- .github/workflows/publish-packages.yml
- .github/workflows/publish-prerelease-packages.yml
- .github/workflows/pull-requests.yml
- package.json
- pnpm-lock.yaml
- turbo.json
I like using all 48 cores for these. How about you folks?
> Use all cores for Turbo builds

- packages/rpc-graphql/src/schema/type-resolvers/account.ts
Fixes a bad rebase from #2642, which should fix the CI failures.
> refactor(experimental): graphql: fix bad rebase from #2642

- examples/react-app/src/components/Nav.tsx
- examples/react-app/src/components/SignInMenu.tsx
- examples/react-app/src/components/SignInMenuItem.tsx
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/lE1zD7Jpg6mWNv3djNKZ/7c4d3567-6aec-4a32-b9f3-626ef2f54a3d.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/lE1zD7Jpg6mWNv3djNKZ/7c4d3567-6aec-4a32-b9f3-626ef2f54a3d.mov">Screen Recording 2024-07-10 at 3.24.53 PM.mov</video>
> Added Sign In With Solana to the example app

- examples/deserialize-transaction/package.json
- examples/deserialize-transaction/src/example.ts
- examples/deserialize-transaction/tsconfig.json
- packages/transaction-messages/src/compress-transaction-message.ts
- pnpm-lock.yaml
This PR adds an example of how to use web3js to decode/inspect/parse transactions. It starts by creating a transaction, partially signing it, and encoding it as base64. It then demonstrates:
- Decoding it to a `Transaction`
- Inspecting the signatures of a `Transaction`
- Verifying a signature on a `Transaction`
- Decoding the message bytes to a `CompiledTransactionMessage`
- Decoding to a `TransactionMessage`, resolving the lookup tables
- Parsing the data of a transfer SOL instruction
- Parsing the data of a memo instruction
Example output:
```
INFO (Deserialize): [setup] Setting lookup table address
address: "2JPQuT3dHtPjrdcbUQyrrT4XYRYaWpWfmAJ54SUapg6n"
INFO (Deserialize): [setup] Got a blockhash
blockhash: "28zB6pcMaWZtUmpMPTGHYUy6T1AawusvogCrWA2emhK7"
lastValidBlockHeight: 152903 …
```
> An example of how to use the new `@solana/web3.js` to deserialize and parse a transaction

- packages/rpc-api/README.md
> Update the README for `@solana/rpc-api`

- examples/rpc-transport-throttled/package.json
- examples/rpc-transport-throttled/src/example.ts
- examples/rpc-transport-throttled/tsconfig.json
- pnpm-lock.yaml
This PR introduces an example of a simple wrapper around a transport that prevents that transport from making more than _n_ requests per second. This demonstrates how transports can be composed to add new functionality.
```
cd examples/rpc-transport-throttled/
pnpm start
> @solana/example-rpc-transport-throttled@ start /home/sol/src/solana-web3.js-git/examples/rpc-transport-throttled
> start-server-and-test '../../scripts/start-shared-test-validator.sh' http://127.0.0.1:8899/health run:example
1: starting server using command "../../scripts/start-shared-test-validator.sh"
and when url "[ 'http://127.0.0.1:8899/health' ]" is responding with HTTP status code 200
running tests using command "npm run run:example"
Started test validator (PID 20904)
> run:example
> tsx src/example.ts …
```
> An example of creating a custom transport to implement rate-limiting logic on the client

- SECURITY.md
- examples/deserialize-transaction/src/example.ts
- examples/rpc-transport-throttled/src/example.ts
Hello
I found and fixed several spelling issues.
Br, Elias.
> chore: fix spelling issues

- package.json
- pnpm-lock.yaml
Going off of the recommendations in https://github.com/semantic-release/release-notes-generator/issues/660, I _think_ this will work?
> chore: fix CI publish again

- .changeset/shaggy-seas-end.md
I have no idea if this changeset makes sense with the release candidate, but I felt like this was at least a minor (breaking) change.
> refactor(experimental): changeset for unix timestamp bigint changes

- packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-autopinger-test.ts
This will be necessary higher up in the stack when we add consequential promise handling to `channel.send()`.
> Asyncify all of the autopinger tests.

- packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-autopinger-test.ts
The online/offline event handler would never unhook after these tests ran. Instead of unhooking them, let's mock the entire `window.addEventListener` plumbing.
> Test the online/offline feature of the autopinger in a way that prevents the event listeners from leaking

- packages/rpc-subscriptions/src/__tests__/rpc-subscriptions-autopinger-test.ts
- packages/rpc-subscriptions/src/rpc-subscriptions-autopinger.ts
A developer noticed that if the autopinger is the next thing in line to send a message, _right_ as the connection has died, the ‘connection closed’ error will bubble up through the `sendPing()` message, unhandled, and will crash the app.
In this PR we make changes to this:
1. Any error is handled and discarded
2. Furthermore, if that error is a ‘connection closed’ error, we stop the pinger
> Errors in the autopinger when sending pings no longer bubble up unhandled

- README.md
- packages/rpc-transport-http/README.md
> `s/getRecentBlockhash/getLatestBlockhash/` in the docs

- .changeset/nine-owls-roll.md
This PR adds a changeset combining the changes of the two previous PR in order to provide a more digest changelog.
> Add changeset for `RpcPlan` changes

- examples/rpc-custom-api/src/example.ts
This PR fixes a failing example due to a recent refactoring that uses an `execute` function as the RPC Plan returned by the RPC API.
> Update failing RPC example

- examples/react-app/package.json
- pnpm-lock.yaml
Had to lock these versions because of radix-ui/themes#619.
> Actually fix Radix menus in React example

- packages/codecs-data-structures/src/__tests__/boolean-test.ts
- packages/rpc-graphql/src/resolvers/transaction.ts
- packages/rpc-graphql/src/schema/type-defs/transaction.ts
- packages/rpc-subscriptions-api/src/__typetests__/account-notifications-type-test.ts
- packages/rpc-subscriptions-api/src/__typetests__/logs-notifications-type-test.ts
- packages/rpc-subscriptions-api/src/__typetests__/program-notifications-type-test.ts
- packages/rpc-subscriptions-api/src/__typetests__/root-notifications-type-test.ts
- packages/rpc-subscriptions-api/src/__typetests__/signature-notifications-type-test.ts
- packages/rpc-subscriptions-api/src/__typetests__/slot-notifications-type-test.ts
- packages/rpc-subscriptions-api/src/__typetests__/slots-updates-notifications-type-test.ts
- packages/rpc-subscriptions-api/src/__typetests__/vote-notifications-type-test.ts
- packages/rpc-subscriptions/src/rpc-subscriptions.ts
- packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
I merged a stack of PR shortly after Eslint was updated so this PR fixes the new Eslint errors that occurred upon merging the stack.
> Fix Eslint errors

- examples/react-app/package.json
- pnpm-lock.yaml
Reverts solana-labs/solana-web3.js#3527
> Revert "chore: bump @radix-ui/react-dropdown-menu from 2.1.1 to 2.1.2"

- .changeset/nasty-buckets-hear.md
- .changeset/pre.json
- .github/workflows/publish-packages.yml
This will cause Changeset to release 2.0.0 when #3531 is landed.
> Drop the Release Candidate label and exit prerelease mode

- package.json
- pnpm-lock.yaml
```
pnpm dlx @turbo/codemod@latest update
```
> Upgrade to Turborepo 2.3.3
